{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:51:30 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-0.9316455,-2.527221,4.891139,1.935437);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(30.39053);
   
   TH1F *dRmin_taujet_stack_11 = new TH1F("dRmin_taujet_stack_11","stack",50,0,10);
   dRmin_taujet_stack_11->SetBinContent(51,0.4873724);
   dRmin_taujet_stack_11->SetBinError(51,0.2041309);
   dRmin_taujet_stack_11->SetMinimum(0.003647812);
   dRmin_taujet_stack_11->SetMaximum(51.55898);
   dRmin_taujet_stack_11->SetEntries(7);
   dRmin_taujet_stack_11->SetStats(0);
   dRmin_taujet_stack_11->SetFillColor(4);
   dRmin_taujet_stack_11->SetLineColor(4);
   dRmin_taujet_stack_11->SetLineWidth(2);
   dRmin_taujet_stack_11->SetMarkerColor(4);
   dRmin_taujet_stack_11->SetMarkerStyle(21);
   dRmin_taujet_stack_11->SetMarkerSize(0.8);
   dRmin_taujet_stack_11->GetXaxis()->SetTitle("#Delta R_{min}(#tau,tag)");
   dRmin_taujet_stack_11->GetXaxis()->SetRange(1,23);
   dRmin_taujet_stack_11->GetXaxis()->SetLabelFont(42);
   dRmin_taujet_stack_11->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet_stack_11->GetXaxis()->SetLabelSize(0);
   dRmin_taujet_stack_11->GetXaxis()->SetTitleSize(0);
   dRmin_taujet_stack_11->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet_stack_11->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet_stack_11->GetXaxis()->SetTitleFont(42);
   dRmin_taujet_stack_11->GetYaxis()->SetTitle("Events");
   dRmin_taujet_stack_11->GetYaxis()->SetLabelFont(42);
   dRmin_taujet_stack_11->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet_stack_11->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet_stack_11->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet_stack_11->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet_stack_11->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet_stack_11->GetYaxis()->SetTitleFont(42);
   dRmin_taujet_stack_11->GetZaxis()->SetLabelFont(42);
   dRmin_taujet_stack_11->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet_stack_11->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet_stack_11->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet_stack_11->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet_stack_11->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(dRmin_taujet_stack_11);
   
   
   TH1F *dRmin_taujet = new TH1F("dRmin_taujet","dRmin_taujet",50,0,10);
   dRmin_taujet->SetBinContent(51,0.4873724);
   dRmin_taujet->SetBinError(51,0.2041309);
   dRmin_taujet->SetMinimum(0.01);
   dRmin_taujet->SetMaximum(30.39053);
   dRmin_taujet->SetEntries(7);
   dRmin_taujet->SetStats(0);
   dRmin_taujet->SetFillColor(4);
   dRmin_taujet->SetLineColor(4);
   dRmin_taujet->SetLineWidth(2);
   dRmin_taujet->SetMarkerColor(4);
   dRmin_taujet->SetMarkerStyle(21);
   dRmin_taujet->SetMarkerSize(0.8);
   dRmin_taujet->GetXaxis()->SetTitle("#Delta R_{min}(#tau,tag)");
   dRmin_taujet->GetXaxis()->SetRange(1,23);
   dRmin_taujet->GetXaxis()->SetLabelFont(42);
   dRmin_taujet->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetXaxis()->SetLabelSize(0);
   dRmin_taujet->GetXaxis()->SetTitleSize(0);
   dRmin_taujet->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet->GetXaxis()->SetTitleFont(42);
   dRmin_taujet->GetYaxis()->SetTitle("Events");
   dRmin_taujet->GetYaxis()->SetLabelFont(42);
   dRmin_taujet->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet->GetYaxis()->SetTitleFont(42);
   dRmin_taujet->GetZaxis()->SetLabelFont(42);
   dRmin_taujet->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet,"HIST");
   
   TH1F *dRmin_taujet = new TH1F("dRmin_taujet","dRmin_taujet",50,0,10);
   dRmin_taujet->SetBinContent(51,25.35158);
   dRmin_taujet->SetBinError(51,4.116735);
   dRmin_taujet->SetEntries(47);
   dRmin_taujet->SetStats(0);
   dRmin_taujet->SetFillColor(5);
   dRmin_taujet->SetLineColor(5);
   dRmin_taujet->SetLineWidth(2);
   dRmin_taujet->SetMarkerColor(5);
   dRmin_taujet->SetMarkerStyle(21);
   dRmin_taujet->SetMarkerSize(0.8);
   dRmin_taujet->GetXaxis()->SetLabelFont(42);
   dRmin_taujet->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet->GetXaxis()->SetTitleFont(42);
   dRmin_taujet->GetYaxis()->SetLabelFont(42);
   dRmin_taujet->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet->GetYaxis()->SetTitleFont(42);
   dRmin_taujet->GetZaxis()->SetLabelFont(42);
   dRmin_taujet->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet,"");
   
   TH1F *dRmin_taujet = new TH1F("dRmin_taujet","dRmin_taujet",50,0,10);
   dRmin_taujet->SetBinContent(51,53.87446);
   dRmin_taujet->SetBinError(51,5.495171);
   dRmin_taujet->SetEntries(126);
   dRmin_taujet->SetStats(0);
   dRmin_taujet->SetFillColor(6);
   dRmin_taujet->SetLineColor(6);
   dRmin_taujet->SetLineWidth(2);
   dRmin_taujet->SetMarkerColor(6);
   dRmin_taujet->SetMarkerStyle(21);
   dRmin_taujet->SetMarkerSize(0.8);
   dRmin_taujet->GetXaxis()->SetLabelFont(42);
   dRmin_taujet->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet->GetXaxis()->SetTitleFont(42);
   dRmin_taujet->GetYaxis()->SetLabelFont(42);
   dRmin_taujet->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet->GetYaxis()->SetTitleFont(42);
   dRmin_taujet->GetZaxis()->SetLabelFont(42);
   dRmin_taujet->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet,"");
   
   TH1F *dRmin_taujet = new TH1F("dRmin_taujet","dRmin_taujet",50,0,10);
   dRmin_taujet->SetBinContent(1,0.02094372);
   dRmin_taujet->SetBinContent(15,0.01956691);
   dRmin_taujet->SetBinContent(17,0.06735591);
   dRmin_taujet->SetBinContent(18,0.0177491);
   dRmin_taujet->SetBinContent(51,8.163524);
   dRmin_taujet->SetBinError(1,0.02094372);
   dRmin_taujet->SetBinError(15,0.01956691);
   dRmin_taujet->SetBinError(17,0.03954363);
   dRmin_taujet->SetBinError(18,0.0177491);
   dRmin_taujet->SetBinError(51,0.4127736);
   dRmin_taujet->SetEntries(461);
   dRmin_taujet->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   dRmin_taujet->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   dRmin_taujet->SetLineColor(ci);
   dRmin_taujet->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   dRmin_taujet->SetMarkerColor(ci);
   dRmin_taujet->SetMarkerStyle(21);
   dRmin_taujet->SetMarkerSize(0.8);
   dRmin_taujet->GetXaxis()->SetLabelFont(42);
   dRmin_taujet->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet->GetXaxis()->SetTitleFont(42);
   dRmin_taujet->GetYaxis()->SetLabelFont(42);
   dRmin_taujet->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet->GetYaxis()->SetTitleFont(42);
   dRmin_taujet->GetZaxis()->SetLabelFont(42);
   dRmin_taujet->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet,"");
   
   TH1F *dRmin_taujet = new TH1F("dRmin_taujet","dRmin_taujet",50,0,10);
   dRmin_taujet->SetStats(0);
   dRmin_taujet->SetFillColor(3);
   dRmin_taujet->SetLineColor(3);
   dRmin_taujet->SetLineWidth(2);
   dRmin_taujet->SetMarkerColor(3);
   dRmin_taujet->SetMarkerStyle(21);
   dRmin_taujet->SetMarkerSize(0.8);
   dRmin_taujet->GetXaxis()->SetLabelFont(42);
   dRmin_taujet->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet->GetXaxis()->SetTitleFont(42);
   dRmin_taujet->GetYaxis()->SetLabelFont(42);
   dRmin_taujet->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet->GetYaxis()->SetTitleFont(42);
   dRmin_taujet->GetZaxis()->SetLabelFont(42);
   dRmin_taujet->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet,"");
   
   TH1F *dRmin_taujet = new TH1F("dRmin_taujet","dRmin_taujet",50,0,10);
   dRmin_taujet->SetBinContent(10,0.2026035);
   dRmin_taujet->SetBinContent(14,0.01566963);
   dRmin_taujet->SetBinContent(16,0.08120943);
   dRmin_taujet->SetBinContent(51,0.5612751);
   dRmin_taujet->SetBinError(10,0.2026035);
   dRmin_taujet->SetBinError(14,0.01566963);
   dRmin_taujet->SetBinError(16,0.08120943);
   dRmin_taujet->SetBinError(51,0.2101922);
   dRmin_taujet->SetEntries(13);
   dRmin_taujet->SetStats(0);
   dRmin_taujet->SetFillColor(3);
   dRmin_taujet->SetLineColor(3);
   dRmin_taujet->SetLineWidth(2);
   dRmin_taujet->SetMarkerColor(3);
   dRmin_taujet->SetMarkerStyle(21);
   dRmin_taujet->SetMarkerSize(0.8);
   dRmin_taujet->GetXaxis()->SetLabelFont(42);
   dRmin_taujet->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet->GetXaxis()->SetTitleFont(42);
   dRmin_taujet->GetYaxis()->SetLabelFont(42);
   dRmin_taujet->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet->GetYaxis()->SetTitleFont(42);
   dRmin_taujet->GetZaxis()->SetLabelFont(42);
   dRmin_taujet->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet,"");
   
   TH1F *dRmin_taujet = new TH1F("dRmin_taujet","dRmin_taujet",50,0,10);
   dRmin_taujet->SetBinContent(4,0.006768879);
   dRmin_taujet->SetBinContent(15,0.006007128);
   dRmin_taujet->SetBinContent(16,0.01271871);
   dRmin_taujet->SetBinContent(17,0.03644229);
   dRmin_taujet->SetBinContent(18,0.01627133);
   dRmin_taujet->SetBinContent(51,0.1775634);
   dRmin_taujet->SetBinError(4,0.006768879);
   dRmin_taujet->SetBinError(15,0.006007128);
   dRmin_taujet->SetBinError(16,0.0089248);
   dRmin_taujet->SetBinError(17,0.01512493);
   dRmin_taujet->SetBinError(18,0.01154472);
   dRmin_taujet->SetBinError(51,0.03565302);
   dRmin_taujet->SetEntries(41);
   dRmin_taujet->SetStats(0);
   dRmin_taujet->SetFillColor(3);
   dRmin_taujet->SetLineColor(3);
   dRmin_taujet->SetLineWidth(2);
   dRmin_taujet->SetMarkerColor(3);
   dRmin_taujet->SetMarkerStyle(21);
   dRmin_taujet->SetMarkerSize(0.8);
   dRmin_taujet->GetXaxis()->SetLabelFont(42);
   dRmin_taujet->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet->GetXaxis()->SetTitleFont(42);
   dRmin_taujet->GetYaxis()->SetLabelFont(42);
   dRmin_taujet->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet->GetYaxis()->SetTitleFont(42);
   dRmin_taujet->GetZaxis()->SetLabelFont(42);
   dRmin_taujet->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet,"");
   stack->Draw("hist");
   
   TH1F *dRmin_taujet = new TH1F("dRmin_taujet","dRmin_taujet",50,0,10);
   dRmin_taujet->SetBinContent(51,55);
   dRmin_taujet->SetBinError(51,7.416198);
   dRmin_taujet->SetEntries(55);
   dRmin_taujet->SetStats(0);
   dRmin_taujet->SetFillColor(1);
   dRmin_taujet->SetFillStyle(0);
   dRmin_taujet->SetLineWidth(3);
   dRmin_taujet->SetMarkerStyle(20);
   dRmin_taujet->SetMarkerSize(1.3);
   dRmin_taujet->GetXaxis()->SetLabelFont(42);
   dRmin_taujet->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet->GetXaxis()->SetTitleFont(42);
   dRmin_taujet->GetYaxis()->SetLabelFont(42);
   dRmin_taujet->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet->GetYaxis()->SetTitleFont(42);
   dRmin_taujet->GetZaxis()->SetLabelFont(42);
   dRmin_taujet->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet->GetZaxis()->SetTitleFont(42);
   dRmin_taujet->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiSIGNAL_CJVfail");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("dRmin_taujet","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("dRmin_taujet","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-0.9316455,-0.653951,4.891139,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *dRmin_taujet = new TH1F("dRmin_taujet","dRmin_taujet",50,0,10);
   dRmin_taujet->SetBinContent(51,0.6240894);
   dRmin_taujet->SetBinError(51,0.09724536);
   dRmin_taujet->SetMinimum(0);
   dRmin_taujet->SetMaximum(2);
   dRmin_taujet->SetStats(0);
   dRmin_taujet->SetFillStyle(0);
   dRmin_taujet->SetMarkerStyle(20);
   dRmin_taujet->SetMarkerSize(0.8);
   dRmin_taujet->GetXaxis()->SetTitle("#Delta R_{min}(#tau,tag)");
   dRmin_taujet->GetXaxis()->SetRange(1,23);
   dRmin_taujet->GetXaxis()->SetLabelFont(42);
   dRmin_taujet->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetXaxis()->SetLabelSize(0.1);
   dRmin_taujet->GetXaxis()->SetTitleSize(0.12);
   dRmin_taujet->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet->GetXaxis()->SetTitleFont(42);
   dRmin_taujet->GetYaxis()->SetTitle("Data/MC");
   dRmin_taujet->GetYaxis()->SetNdivisions(505);
   dRmin_taujet->GetYaxis()->SetLabelFont(42);
   dRmin_taujet->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetYaxis()->SetLabelSize(0.1);
   dRmin_taujet->GetYaxis()->SetTitleSize(0.12);
   dRmin_taujet->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet->GetYaxis()->SetTitleOffset(0.55);
   dRmin_taujet->GetYaxis()->SetTitleFont(42);
   dRmin_taujet->GetZaxis()->SetLabelFont(42);
   dRmin_taujet->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet->GetZaxis()->SetTitleFont(42);
   dRmin_taujet->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
