{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:51:20 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-1.336709,-2.531349,7.017722,1.9799);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(33.32183);
   
   TH1F *dRmin_taujet1_stack_11 = new TH1F("dRmin_taujet1_stack_11","stack",50,0,10);
   dRmin_taujet1_stack_11->SetBinContent(51,0.4873724);
   dRmin_taujet1_stack_11->SetBinError(51,0.2041309);
   dRmin_taujet1_stack_11->SetMinimum(0.003621398);
   dRmin_taujet1_stack_11->SetMaximum(56.79859);
   dRmin_taujet1_stack_11->SetEntries(7);
   dRmin_taujet1_stack_11->SetStats(0);
   dRmin_taujet1_stack_11->SetFillColor(4);
   dRmin_taujet1_stack_11->SetLineColor(4);
   dRmin_taujet1_stack_11->SetLineWidth(2);
   dRmin_taujet1_stack_11->SetMarkerColor(4);
   dRmin_taujet1_stack_11->SetMarkerStyle(21);
   dRmin_taujet1_stack_11->SetMarkerSize(0.8);
   dRmin_taujet1_stack_11->GetXaxis()->SetTitle("#Delta R_{min}(#tau,tag1)");
   dRmin_taujet1_stack_11->GetXaxis()->SetRange(1,33);
   dRmin_taujet1_stack_11->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1_stack_11->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1_stack_11->GetXaxis()->SetLabelSize(0);
   dRmin_taujet1_stack_11->GetXaxis()->SetTitleSize(0);
   dRmin_taujet1_stack_11->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1_stack_11->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1_stack_11->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1_stack_11->GetYaxis()->SetTitle("Events");
   dRmin_taujet1_stack_11->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1_stack_11->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1_stack_11->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1_stack_11->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1_stack_11->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1_stack_11->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1_stack_11->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1_stack_11->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1_stack_11->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1_stack_11->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1_stack_11->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1_stack_11->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1_stack_11->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(dRmin_taujet1_stack_11);
   
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(51,0.4873724);
   dRmin_taujet1->SetBinError(51,0.2041309);
   dRmin_taujet1->SetMinimum(0.01);
   dRmin_taujet1->SetMaximum(30.39053);
   dRmin_taujet1->SetEntries(7);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(4);
   dRmin_taujet1->SetLineColor(4);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(4);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetTitle("#Delta R_{min}(#tau,tag1)");
   dRmin_taujet1->GetXaxis()->SetRange(1,33);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetTitle("Events");
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"HIST");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(51,25.35158);
   dRmin_taujet1->SetBinError(51,4.116735);
   dRmin_taujet1->SetEntries(47);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(5);
   dRmin_taujet1->SetLineColor(5);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(5);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(51,53.87446);
   dRmin_taujet1->SetBinError(51,5.495171);
   dRmin_taujet1->SetEntries(126);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(6);
   dRmin_taujet1->SetLineColor(6);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(6);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(1,0.02094372);
   dRmin_taujet1->SetBinContent(15,0.01956691);
   dRmin_taujet1->SetBinContent(17,0.01950672);
   dRmin_taujet1->SetBinContent(18,0.0177491);
   dRmin_taujet1->SetBinContent(19,0.02830716);
   dRmin_taujet1->SetBinContent(22,0.01954203);
   dRmin_taujet1->SetBinContent(51,8.163524);
   dRmin_taujet1->SetBinError(1,0.02094372);
   dRmin_taujet1->SetBinError(15,0.01956691);
   dRmin_taujet1->SetBinError(17,0.01950672);
   dRmin_taujet1->SetBinError(18,0.0177491);
   dRmin_taujet1->SetBinError(19,0.02830716);
   dRmin_taujet1->SetBinError(22,0.01954203);
   dRmin_taujet1->SetBinError(51,0.4127736);
   dRmin_taujet1->SetEntries(461);
   dRmin_taujet1->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   dRmin_taujet1->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   dRmin_taujet1->SetLineColor(ci);
   dRmin_taujet1->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   dRmin_taujet1->SetMarkerColor(ci);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(3);
   dRmin_taujet1->SetLineColor(3);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(3);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(14,0.01566963);
   dRmin_taujet1->SetBinContent(19,0.08120943);
   dRmin_taujet1->SetBinContent(22,0.2026035);
   dRmin_taujet1->SetBinContent(51,0.5612751);
   dRmin_taujet1->SetBinError(14,0.01566963);
   dRmin_taujet1->SetBinError(19,0.08120943);
   dRmin_taujet1->SetBinError(22,0.2026035);
   dRmin_taujet1->SetBinError(51,0.2101922);
   dRmin_taujet1->SetEntries(13);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(3);
   dRmin_taujet1->SetLineColor(3);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(3);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(4,0.006768879);
   dRmin_taujet1->SetBinContent(15,0.006007128);
   dRmin_taujet1->SetBinContent(16,0.0126208);
   dRmin_taujet1->SetBinContent(17,0.03644229);
   dRmin_taujet1->SetBinContent(18,0.00746392);
   dRmin_taujet1->SetBinContent(20,0.008807413);
   dRmin_taujet1->SetBinContent(23,9.790847e-05);
   dRmin_taujet1->SetBinContent(51,0.1775634);
   dRmin_taujet1->SetBinError(4,0.006768879);
   dRmin_taujet1->SetBinError(15,0.006007128);
   dRmin_taujet1->SetBinError(16,0.008924263);
   dRmin_taujet1->SetBinError(17,0.01512493);
   dRmin_taujet1->SetBinError(18,0.00746392);
   dRmin_taujet1->SetBinError(20,0.008807414);
   dRmin_taujet1->SetBinError(23,9.790846e-05);
   dRmin_taujet1->SetBinError(51,0.03565302);
   dRmin_taujet1->SetEntries(41);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(3);
   dRmin_taujet1->SetLineColor(3);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(3);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   stack->Draw("hist");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(51,55);
   dRmin_taujet1->SetBinError(51,7.416198);
   dRmin_taujet1->SetEntries(55);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(1);
   dRmin_taujet1->SetFillStyle(0);
   dRmin_taujet1->SetLineWidth(3);
   dRmin_taujet1->SetMarkerStyle(20);
   dRmin_taujet1->SetMarkerSize(1.3);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   dRmin_taujet1->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiSIGNAL_CJVfail");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("dRmin_taujet1","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("dRmin_taujet1","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet1","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet1","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet1","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet1","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-1.336709,-0.653951,7.017722,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(51,0.6240894);
   dRmin_taujet1->SetBinError(51,0.09724536);
   dRmin_taujet1->SetMinimum(0);
   dRmin_taujet1->SetMaximum(2);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillStyle(0);
   dRmin_taujet1->SetMarkerStyle(20);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetTitle("#Delta R_{min}(#tau,tag1)");
   dRmin_taujet1->GetXaxis()->SetRange(1,33);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.1);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.12);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetTitle("Data/MC");
   dRmin_taujet1->GetYaxis()->SetNdivisions(505);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.1);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.12);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(0.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   dRmin_taujet1->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
