{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:51:20 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-1.336709,-2.432787,7.017722,0.9833807);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(4.256677);
   
   TH1F *dRmin_taujet1_stack_12 = new TH1F("dRmin_taujet1_stack_12","stack",50,0,10);
   dRmin_taujet1_stack_12->SetBinContent(51,0.0420392);
   dRmin_taujet1_stack_12->SetBinError(51,0.0420392);
   dRmin_taujet1_stack_12->SetMinimum(0.004320522);
   dRmin_taujet1_stack_12->SetMaximum(6.494898);
   dRmin_taujet1_stack_12->SetEntries(1);
   dRmin_taujet1_stack_12->SetStats(0);
   dRmin_taujet1_stack_12->SetFillColor(4);
   dRmin_taujet1_stack_12->SetLineColor(4);
   dRmin_taujet1_stack_12->SetLineWidth(2);
   dRmin_taujet1_stack_12->SetMarkerColor(4);
   dRmin_taujet1_stack_12->SetMarkerStyle(21);
   dRmin_taujet1_stack_12->SetMarkerSize(0.8);
   dRmin_taujet1_stack_12->GetXaxis()->SetTitle("#Delta R_{min}(#tau,tag1)");
   dRmin_taujet1_stack_12->GetXaxis()->SetRange(1,33);
   dRmin_taujet1_stack_12->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1_stack_12->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1_stack_12->GetXaxis()->SetLabelSize(0);
   dRmin_taujet1_stack_12->GetXaxis()->SetTitleSize(0);
   dRmin_taujet1_stack_12->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1_stack_12->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1_stack_12->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1_stack_12->GetYaxis()->SetTitle("Events");
   dRmin_taujet1_stack_12->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1_stack_12->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1_stack_12->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1_stack_12->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1_stack_12->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1_stack_12->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1_stack_12->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1_stack_12->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1_stack_12->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1_stack_12->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1_stack_12->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1_stack_12->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1_stack_12->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(dRmin_taujet1_stack_12);
   
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(51,0.0420392);
   dRmin_taujet1->SetBinError(51,0.0420392);
   dRmin_taujet1->SetMinimum(0.01);
   dRmin_taujet1->SetMaximum(150);
   dRmin_taujet1->SetEntries(1);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(4);
   dRmin_taujet1->SetLineColor(4);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(4);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetTitle("#Delta R_{min}(#tau,tag1)");
   dRmin_taujet1->GetXaxis()->SetRange(1,33);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetTitle("Events");
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"HIST");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(51,12.91685);
   dRmin_taujet1->SetBinError(51,2.987882);
   dRmin_taujet1->SetEntries(21);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(5);
   dRmin_taujet1->SetLineColor(5);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(5);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(51,31.20149);
   dRmin_taujet1->SetBinError(51,3.757844);
   dRmin_taujet1->SetEntries(81);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(6);
   dRmin_taujet1->SetLineColor(6);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(6);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(13,0.02782504);
   dRmin_taujet1->SetBinContent(15,0.01882598);
   dRmin_taujet1->SetBinContent(17,0.02160406);
   dRmin_taujet1->SetBinContent(20,0.01315865);
   dRmin_taujet1->SetBinContent(24,0.005496214);
   dRmin_taujet1->SetBinContent(28,0.01924418);
   dRmin_taujet1->SetBinContent(51,4.718822);
   dRmin_taujet1->SetBinError(13,0.01971936);
   dRmin_taujet1->SetBinError(15,0.01882598);
   dRmin_taujet1->SetBinError(17,0.02160406);
   dRmin_taujet1->SetBinError(20,0.01315865);
   dRmin_taujet1->SetBinError(24,0.005496214);
   dRmin_taujet1->SetBinError(28,0.01924418);
   dRmin_taujet1->SetBinError(51,0.3046681);
   dRmin_taujet1->SetEntries(292);
   dRmin_taujet1->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   dRmin_taujet1->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   dRmin_taujet1->SetLineColor(ci);
   dRmin_taujet1->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   dRmin_taujet1->SetMarkerColor(ci);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(3);
   dRmin_taujet1->SetLineColor(3);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(3);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(51,0.2058722);
   dRmin_taujet1->SetBinError(51,0.1123522);
   dRmin_taujet1->SetEntries(4);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(3);
   dRmin_taujet1->SetLineColor(3);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(3);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(16,0.003953508);
   dRmin_taujet1->SetBinContent(17,0.006773782);
   dRmin_taujet1->SetBinContent(18,0.006430486);
   dRmin_taujet1->SetBinContent(25,2.186192e-05);
   dRmin_taujet1->SetBinContent(51,0.08551933);
   dRmin_taujet1->SetBinError(16,0.003953508);
   dRmin_taujet1->SetBinError(17,0.006773782);
   dRmin_taujet1->SetBinError(18,0.006255109);
   dRmin_taujet1->SetBinError(25,2.186192e-05);
   dRmin_taujet1->SetBinError(51,0.02198815);
   dRmin_taujet1->SetEntries(22);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(3);
   dRmin_taujet1->SetLineColor(3);
   dRmin_taujet1->SetLineWidth(2);
   dRmin_taujet1->SetMarkerColor(3);
   dRmin_taujet1->SetMarkerStyle(21);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   stack->Add(dRmin_taujet1,"");
   stack->Draw("hist");
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(5,1);
   dRmin_taujet1->SetBinContent(12,1);
   dRmin_taujet1->SetBinContent(19,1);
   dRmin_taujet1->SetBinContent(51,34);
   dRmin_taujet1->SetBinError(5,1);
   dRmin_taujet1->SetBinError(12,1);
   dRmin_taujet1->SetBinError(19,1);
   dRmin_taujet1->SetBinError(51,5.830952);
   dRmin_taujet1->SetEntries(37);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillColor(1);
   dRmin_taujet1->SetFillStyle(0);
   dRmin_taujet1->SetLineWidth(3);
   dRmin_taujet1->SetMarkerStyle(20);
   dRmin_taujet1->SetMarkerSize(1.3);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(1.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   dRmin_taujet1->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiQCD_CJVfail");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("dRmin_taujet1","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("dRmin_taujet1","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet1","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet1","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet1","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("dRmin_taujet1","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-1.336709,-0.653951,7.017722,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *dRmin_taujet1 = new TH1F("dRmin_taujet1","dRmin_taujet1",50,0,10);
   dRmin_taujet1->SetBinContent(51,0.6920618);
   dRmin_taujet1->SetBinError(51,0.1366803);
   dRmin_taujet1->SetMinimum(0);
   dRmin_taujet1->SetMaximum(2);
   dRmin_taujet1->SetStats(0);
   dRmin_taujet1->SetFillStyle(0);
   dRmin_taujet1->SetMarkerStyle(20);
   dRmin_taujet1->SetMarkerSize(0.8);
   dRmin_taujet1->GetXaxis()->SetTitle("#Delta R_{min}(#tau,tag1)");
   dRmin_taujet1->GetXaxis()->SetRange(1,33);
   dRmin_taujet1->GetXaxis()->SetLabelFont(42);
   dRmin_taujet1->GetXaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetXaxis()->SetLabelSize(0.1);
   dRmin_taujet1->GetXaxis()->SetTitleSize(0.12);
   dRmin_taujet1->GetXaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetXaxis()->SetTitleOffset(0.9);
   dRmin_taujet1->GetXaxis()->SetTitleFont(42);
   dRmin_taujet1->GetYaxis()->SetTitle("Data/MC");
   dRmin_taujet1->GetYaxis()->SetNdivisions(505);
   dRmin_taujet1->GetYaxis()->SetLabelFont(42);
   dRmin_taujet1->GetYaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetYaxis()->SetLabelSize(0.1);
   dRmin_taujet1->GetYaxis()->SetTitleSize(0.12);
   dRmin_taujet1->GetYaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetYaxis()->SetTitleOffset(0.55);
   dRmin_taujet1->GetYaxis()->SetTitleFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelFont(42);
   dRmin_taujet1->GetZaxis()->SetLabelOffset(0.007);
   dRmin_taujet1->GetZaxis()->SetLabelSize(0.035);
   dRmin_taujet1->GetZaxis()->SetTitleSize(0.045);
   dRmin_taujet1->GetZaxis()->SetTickLength(0.02);
   dRmin_taujet1->GetZaxis()->SetTitleFont(42);
   dRmin_taujet1->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
