{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:51:50 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-1.405063,-2.943513,1.126582,7.71934);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(5584202);
   
   TH1F *edxy_all_stack_7 = new TH1F("edxy_all_stack_7","stack",100,-1,1);
   edxy_all_stack_7->SetBinContent(50,6.695582);
   edxy_all_stack_7->SetBinContent(51,13.19081);
   edxy_all_stack_7->SetBinError(50,3.229969);
   edxy_all_stack_7->SetBinError(51,5.015892);
   edxy_all_stack_7->SetMinimum(0.001860991);
   edxy_all_stack_7->SetMaximum(1.535316e+07);
   edxy_all_stack_7->SetEntries(43);
   edxy_all_stack_7->SetStats(0);
   edxy_all_stack_7->SetFillColor(4);
   edxy_all_stack_7->SetLineColor(4);
   edxy_all_stack_7->SetLineWidth(2);
   edxy_all_stack_7->SetMarkerColor(4);
   edxy_all_stack_7->SetMarkerStyle(21);
   edxy_all_stack_7->SetMarkerSize(0.8);
   edxy_all_stack_7->GetXaxis()->SetTitle("Electron d_{xy}");
   edxy_all_stack_7->GetXaxis()->SetLabelFont(42);
   edxy_all_stack_7->GetXaxis()->SetLabelOffset(0.007);
   edxy_all_stack_7->GetXaxis()->SetLabelSize(0);
   edxy_all_stack_7->GetXaxis()->SetTitleSize(0);
   edxy_all_stack_7->GetXaxis()->SetTickLength(0.02);
   edxy_all_stack_7->GetXaxis()->SetTitleOffset(0.9);
   edxy_all_stack_7->GetXaxis()->SetTitleFont(42);
   edxy_all_stack_7->GetYaxis()->SetTitle("Events");
   edxy_all_stack_7->GetYaxis()->SetLabelFont(42);
   edxy_all_stack_7->GetYaxis()->SetLabelOffset(0.007);
   edxy_all_stack_7->GetYaxis()->SetLabelSize(0.035);
   edxy_all_stack_7->GetYaxis()->SetTitleSize(0.045);
   edxy_all_stack_7->GetYaxis()->SetTickLength(0.02);
   edxy_all_stack_7->GetYaxis()->SetTitleOffset(1.55);
   edxy_all_stack_7->GetYaxis()->SetTitleFont(42);
   edxy_all_stack_7->GetZaxis()->SetLabelFont(42);
   edxy_all_stack_7->GetZaxis()->SetLabelOffset(0.007);
   edxy_all_stack_7->GetZaxis()->SetLabelSize(0.035);
   edxy_all_stack_7->GetZaxis()->SetTitleSize(0.045);
   edxy_all_stack_7->GetZaxis()->SetTickLength(0.02);
   edxy_all_stack_7->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(edxy_all_stack_7);
   
   
   TH1F *edxy_all = new TH1F("edxy_all","edxy_all",100,-1,1);
   edxy_all->SetBinContent(50,6.695582);
   edxy_all->SetBinContent(51,13.19081);
   edxy_all->SetBinError(50,3.229969);
   edxy_all->SetBinError(51,5.015892);
   edxy_all->SetMinimum(0.01);
   edxy_all->SetMaximum(4500000);
   edxy_all->SetEntries(43);
   edxy_all->SetStats(0);
   edxy_all->SetFillColor(4);
   edxy_all->SetLineColor(4);
   edxy_all->SetLineWidth(2);
   edxy_all->SetMarkerColor(4);
   edxy_all->SetMarkerStyle(21);
   edxy_all->SetMarkerSize(0.8);
   edxy_all->GetXaxis()->SetTitle("Electron d_{xy}");
   edxy_all->GetXaxis()->SetLabelFont(42);
   edxy_all->GetXaxis()->SetLabelOffset(0.007);
   edxy_all->GetXaxis()->SetLabelSize(0);
   edxy_all->GetXaxis()->SetTitleSize(0);
   edxy_all->GetXaxis()->SetTickLength(0.02);
   edxy_all->GetXaxis()->SetTitleOffset(0.9);
   edxy_all->GetXaxis()->SetTitleFont(42);
   edxy_all->GetYaxis()->SetTitle("Events");
   edxy_all->GetYaxis()->SetLabelFont(42);
   edxy_all->GetYaxis()->SetLabelOffset(0.007);
   edxy_all->GetYaxis()->SetLabelSize(0.035);
   edxy_all->GetYaxis()->SetTitleSize(0.045);
   edxy_all->GetYaxis()->SetTickLength(0.02);
   edxy_all->GetYaxis()->SetTitleOffset(1.55);
   edxy_all->GetYaxis()->SetTitleFont(42);
   edxy_all->GetZaxis()->SetLabelFont(42);
   edxy_all->GetZaxis()->SetLabelOffset(0.007);
   edxy_all->GetZaxis()->SetLabelSize(0.035);
   edxy_all->GetZaxis()->SetTitleSize(0.045);
   edxy_all->GetZaxis()->SetTickLength(0.02);
   edxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edxy_all,"HIST");
   
   TH1F *edxy_all = new TH1F("edxy_all","edxy_all",100,-1,1);
   edxy_all->SetBinContent(50,52.43629);
   edxy_all->SetBinContent(51,47.75516);
   edxy_all->SetBinError(50,5.960001);
   edxy_all->SetBinError(51,5.682757);
   edxy_all->SetEntries(187);
   edxy_all->SetStats(0);
   edxy_all->SetFillColor(5);
   edxy_all->SetLineColor(5);
   edxy_all->SetLineWidth(2);
   edxy_all->SetMarkerColor(5);
   edxy_all->SetMarkerStyle(21);
   edxy_all->SetMarkerSize(0.8);
   edxy_all->GetXaxis()->SetLabelFont(42);
   edxy_all->GetXaxis()->SetLabelOffset(0.007);
   edxy_all->GetXaxis()->SetLabelSize(0.035);
   edxy_all->GetXaxis()->SetTitleSize(0.045);
   edxy_all->GetXaxis()->SetTickLength(0.02);
   edxy_all->GetXaxis()->SetTitleOffset(0.9);
   edxy_all->GetXaxis()->SetTitleFont(42);
   edxy_all->GetYaxis()->SetLabelFont(42);
   edxy_all->GetYaxis()->SetLabelOffset(0.007);
   edxy_all->GetYaxis()->SetLabelSize(0.035);
   edxy_all->GetYaxis()->SetTitleSize(0.045);
   edxy_all->GetYaxis()->SetTickLength(0.02);
   edxy_all->GetYaxis()->SetTitleOffset(1.55);
   edxy_all->GetYaxis()->SetTitleFont(42);
   edxy_all->GetZaxis()->SetLabelFont(42);
   edxy_all->GetZaxis()->SetLabelOffset(0.007);
   edxy_all->GetZaxis()->SetLabelSize(0.035);
   edxy_all->GetZaxis()->SetTitleSize(0.045);
   edxy_all->GetZaxis()->SetTickLength(0.02);
   edxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edxy_all,"");
   
   TH1F *edxy_all = new TH1F("edxy_all","edxy_all",100,-1,1);
   edxy_all->SetBinContent(50,170.6668);
   edxy_all->SetBinContent(51,213.7935);
   edxy_all->SetBinError(50,10.8203);
   edxy_all->SetBinError(51,12.01059);
   edxy_all->SetEntries(784);
   edxy_all->SetStats(0);
   edxy_all->SetFillColor(6);
   edxy_all->SetLineColor(6);
   edxy_all->SetLineWidth(2);
   edxy_all->SetMarkerColor(6);
   edxy_all->SetMarkerStyle(21);
   edxy_all->SetMarkerSize(0.8);
   edxy_all->GetXaxis()->SetLabelFont(42);
   edxy_all->GetXaxis()->SetLabelOffset(0.007);
   edxy_all->GetXaxis()->SetLabelSize(0.035);
   edxy_all->GetXaxis()->SetTitleSize(0.045);
   edxy_all->GetXaxis()->SetTickLength(0.02);
   edxy_all->GetXaxis()->SetTitleOffset(0.9);
   edxy_all->GetXaxis()->SetTitleFont(42);
   edxy_all->GetYaxis()->SetLabelFont(42);
   edxy_all->GetYaxis()->SetLabelOffset(0.007);
   edxy_all->GetYaxis()->SetLabelSize(0.035);
   edxy_all->GetYaxis()->SetTitleSize(0.045);
   edxy_all->GetYaxis()->SetTickLength(0.02);
   edxy_all->GetYaxis()->SetTitleOffset(1.55);
   edxy_all->GetYaxis()->SetTitleFont(42);
   edxy_all->GetZaxis()->SetLabelFont(42);
   edxy_all->GetZaxis()->SetLabelOffset(0.007);
   edxy_all->GetZaxis()->SetLabelSize(0.035);
   edxy_all->GetZaxis()->SetTitleSize(0.045);
   edxy_all->GetZaxis()->SetTickLength(0.02);
   edxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edxy_all,"");
   
   TH1F *edxy_all = new TH1F("edxy_all","edxy_all",100,-1,1);
   edxy_all->SetBinContent(50,64.8895);
   edxy_all->SetBinContent(51,93.10602);
   edxy_all->SetBinError(50,1.12941);
   edxy_all->SetBinError(51,1.365679);
   edxy_all->SetEntries(9245);
   edxy_all->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   edxy_all->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   edxy_all->SetLineColor(ci);
   edxy_all->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   edxy_all->SetMarkerColor(ci);
   edxy_all->SetMarkerStyle(21);
   edxy_all->SetMarkerSize(0.8);
   edxy_all->GetXaxis()->SetLabelFont(42);
   edxy_all->GetXaxis()->SetLabelOffset(0.007);
   edxy_all->GetXaxis()->SetLabelSize(0.035);
   edxy_all->GetXaxis()->SetTitleSize(0.045);
   edxy_all->GetXaxis()->SetTickLength(0.02);
   edxy_all->GetXaxis()->SetTitleOffset(0.9);
   edxy_all->GetXaxis()->SetTitleFont(42);
   edxy_all->GetYaxis()->SetLabelFont(42);
   edxy_all->GetYaxis()->SetLabelOffset(0.007);
   edxy_all->GetYaxis()->SetLabelSize(0.035);
   edxy_all->GetYaxis()->SetTitleSize(0.045);
   edxy_all->GetYaxis()->SetTickLength(0.02);
   edxy_all->GetYaxis()->SetTitleOffset(1.55);
   edxy_all->GetYaxis()->SetTitleFont(42);
   edxy_all->GetZaxis()->SetLabelFont(42);
   edxy_all->GetZaxis()->SetLabelOffset(0.007);
   edxy_all->GetZaxis()->SetLabelSize(0.035);
   edxy_all->GetZaxis()->SetTitleSize(0.045);
   edxy_all->GetZaxis()->SetTickLength(0.02);
   edxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edxy_all,"");
   
   TH1F *edxy_all = new TH1F("edxy_all","edxy_all",100,-1,1);
   edxy_all->SetStats(0);
   edxy_all->SetFillColor(3);
   edxy_all->SetLineColor(3);
   edxy_all->SetLineWidth(2);
   edxy_all->SetMarkerColor(3);
   edxy_all->SetMarkerStyle(21);
   edxy_all->SetMarkerSize(0.8);
   edxy_all->GetXaxis()->SetLabelFont(42);
   edxy_all->GetXaxis()->SetLabelOffset(0.007);
   edxy_all->GetXaxis()->SetLabelSize(0.035);
   edxy_all->GetXaxis()->SetTitleSize(0.045);
   edxy_all->GetXaxis()->SetTickLength(0.02);
   edxy_all->GetXaxis()->SetTitleOffset(0.9);
   edxy_all->GetXaxis()->SetTitleFont(42);
   edxy_all->GetYaxis()->SetLabelFont(42);
   edxy_all->GetYaxis()->SetLabelOffset(0.007);
   edxy_all->GetYaxis()->SetLabelSize(0.035);
   edxy_all->GetYaxis()->SetTitleSize(0.045);
   edxy_all->GetYaxis()->SetTickLength(0.02);
   edxy_all->GetYaxis()->SetTitleOffset(1.55);
   edxy_all->GetYaxis()->SetTitleFont(42);
   edxy_all->GetZaxis()->SetLabelFont(42);
   edxy_all->GetZaxis()->SetLabelOffset(0.007);
   edxy_all->GetZaxis()->SetLabelSize(0.035);
   edxy_all->GetZaxis()->SetTitleSize(0.045);
   edxy_all->GetZaxis()->SetTickLength(0.02);
   edxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edxy_all,"");
   
   TH1F *edxy_all = new TH1F("edxy_all","edxy_all",100,-1,1);
   edxy_all->SetBinContent(50,2.797657);
   edxy_all->SetBinContent(51,3.427947);
   edxy_all->SetBinError(50,0.5475149);
   edxy_all->SetBinError(51,0.6691087);
   edxy_all->SetEntries(71);
   edxy_all->SetStats(0);
   edxy_all->SetFillColor(3);
   edxy_all->SetLineColor(3);
   edxy_all->SetLineWidth(2);
   edxy_all->SetMarkerColor(3);
   edxy_all->SetMarkerStyle(21);
   edxy_all->SetMarkerSize(0.8);
   edxy_all->GetXaxis()->SetLabelFont(42);
   edxy_all->GetXaxis()->SetLabelOffset(0.007);
   edxy_all->GetXaxis()->SetLabelSize(0.035);
   edxy_all->GetXaxis()->SetTitleSize(0.045);
   edxy_all->GetXaxis()->SetTickLength(0.02);
   edxy_all->GetXaxis()->SetTitleOffset(0.9);
   edxy_all->GetXaxis()->SetTitleFont(42);
   edxy_all->GetYaxis()->SetLabelFont(42);
   edxy_all->GetYaxis()->SetLabelOffset(0.007);
   edxy_all->GetYaxis()->SetLabelSize(0.035);
   edxy_all->GetYaxis()->SetTitleSize(0.045);
   edxy_all->GetYaxis()->SetTickLength(0.02);
   edxy_all->GetYaxis()->SetTitleOffset(1.55);
   edxy_all->GetYaxis()->SetTitleFont(42);
   edxy_all->GetZaxis()->SetLabelFont(42);
   edxy_all->GetZaxis()->SetLabelOffset(0.007);
   edxy_all->GetZaxis()->SetLabelSize(0.035);
   edxy_all->GetZaxis()->SetTitleSize(0.045);
   edxy_all->GetZaxis()->SetTickLength(0.02);
   edxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edxy_all,"");
   
   TH1F *edxy_all = new TH1F("edxy_all","edxy_all",100,-1,1);
   edxy_all->SetBinContent(50,0.9310251);
   edxy_all->SetBinContent(51,1.006646);
   edxy_all->SetBinError(50,0.07649601);
   edxy_all->SetBinError(51,0.08125621);
   edxy_all->SetEntries(352);
   edxy_all->SetStats(0);
   edxy_all->SetFillColor(3);
   edxy_all->SetLineColor(3);
   edxy_all->SetLineWidth(2);
   edxy_all->SetMarkerColor(3);
   edxy_all->SetMarkerStyle(21);
   edxy_all->SetMarkerSize(0.8);
   edxy_all->GetXaxis()->SetLabelFont(42);
   edxy_all->GetXaxis()->SetLabelOffset(0.007);
   edxy_all->GetXaxis()->SetLabelSize(0.035);
   edxy_all->GetXaxis()->SetTitleSize(0.045);
   edxy_all->GetXaxis()->SetTickLength(0.02);
   edxy_all->GetXaxis()->SetTitleOffset(0.9);
   edxy_all->GetXaxis()->SetTitleFont(42);
   edxy_all->GetYaxis()->SetLabelFont(42);
   edxy_all->GetYaxis()->SetLabelOffset(0.007);
   edxy_all->GetYaxis()->SetLabelSize(0.035);
   edxy_all->GetYaxis()->SetTitleSize(0.045);
   edxy_all->GetYaxis()->SetTickLength(0.02);
   edxy_all->GetYaxis()->SetTitleOffset(1.55);
   edxy_all->GetYaxis()->SetTitleFont(42);
   edxy_all->GetZaxis()->SetLabelFont(42);
   edxy_all->GetZaxis()->SetLabelOffset(0.007);
   edxy_all->GetZaxis()->SetLabelSize(0.035);
   edxy_all->GetZaxis()->SetTitleSize(0.045);
   edxy_all->GetZaxis()->SetTickLength(0.02);
   edxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edxy_all,"");
   stack->Draw("hist");
   
   TH1F *edxy_all = new TH1F("edxy_all","edxy_all",100,-1,1);
   edxy_all->SetBinContent(50,186);
   edxy_all->SetBinContent(51,300);
   edxy_all->SetBinError(50,13.63818);
   edxy_all->SetBinError(51,17.32051);
   edxy_all->SetEntries(486);
   edxy_all->SetStats(0);
   edxy_all->SetFillColor(1);
   edxy_all->SetFillStyle(0);
   edxy_all->SetLineWidth(3);
   edxy_all->SetMarkerStyle(20);
   edxy_all->SetMarkerSize(1.3);
   edxy_all->GetXaxis()->SetLabelFont(42);
   edxy_all->GetXaxis()->SetLabelOffset(0.007);
   edxy_all->GetXaxis()->SetLabelSize(0.035);
   edxy_all->GetXaxis()->SetTitleSize(0.045);
   edxy_all->GetXaxis()->SetTickLength(0.02);
   edxy_all->GetXaxis()->SetTitleOffset(0.9);
   edxy_all->GetXaxis()->SetTitleFont(42);
   edxy_all->GetYaxis()->SetLabelFont(42);
   edxy_all->GetYaxis()->SetLabelOffset(0.007);
   edxy_all->GetYaxis()->SetLabelSize(0.035);
   edxy_all->GetYaxis()->SetTitleSize(0.045);
   edxy_all->GetYaxis()->SetTickLength(0.02);
   edxy_all->GetYaxis()->SetTitleOffset(1.55);
   edxy_all->GetYaxis()->SetTitleFont(42);
   edxy_all->GetZaxis()->SetLabelFont(42);
   edxy_all->GetZaxis()->SetLabelOffset(0.007);
   edxy_all->GetZaxis()->SetLabelSize(0.035);
   edxy_all->GetZaxis()->SetTitleSize(0.045);
   edxy_all->GetZaxis()->SetTickLength(0.02);
   edxy_all->GetZaxis()->SetTitleFont(42);
   edxy_all->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"TightMjj");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("edxy_all","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("edxy_all","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("edxy_all","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("edxy_all","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("edxy_all","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("edxy_all","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-1.405063,-0.653951,1.126582,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *edxy_all = new TH1F("edxy_all","edxy_all",100,-1,1);
   edxy_all->SetBinContent(50,0.6375948);
   edxy_all->SetBinContent(51,0.8354468);
   edxy_all->SetBinError(50,0.05405694);
   edxy_all->SetBinError(51,0.05740007);
   edxy_all->SetMinimum(0);
   edxy_all->SetMaximum(2);
   edxy_all->SetEntries(349.0235);
   edxy_all->SetStats(0);
   edxy_all->SetFillStyle(0);
   edxy_all->SetMarkerStyle(20);
   edxy_all->SetMarkerSize(0.8);
   edxy_all->GetXaxis()->SetTitle("Electron d_{xy}");
   edxy_all->GetXaxis()->SetLabelFont(42);
   edxy_all->GetXaxis()->SetLabelOffset(0.007);
   edxy_all->GetXaxis()->SetLabelSize(0.1);
   edxy_all->GetXaxis()->SetTitleSize(0.12);
   edxy_all->GetXaxis()->SetTickLength(0.02);
   edxy_all->GetXaxis()->SetTitleOffset(0.9);
   edxy_all->GetXaxis()->SetTitleFont(42);
   edxy_all->GetYaxis()->SetTitle("Data/MC");
   edxy_all->GetYaxis()->SetNdivisions(505);
   edxy_all->GetYaxis()->SetLabelFont(42);
   edxy_all->GetYaxis()->SetLabelOffset(0.007);
   edxy_all->GetYaxis()->SetLabelSize(0.1);
   edxy_all->GetYaxis()->SetTitleSize(0.12);
   edxy_all->GetYaxis()->SetTickLength(0.02);
   edxy_all->GetYaxis()->SetTitleOffset(0.55);
   edxy_all->GetYaxis()->SetTitleFont(42);
   edxy_all->GetZaxis()->SetLabelFont(42);
   edxy_all->GetZaxis()->SetLabelOffset(0.007);
   edxy_all->GetZaxis()->SetLabelSize(0.035);
   edxy_all->GetZaxis()->SetTitleSize(0.045);
   edxy_all->GetZaxis()->SetTickLength(0.02);
   edxy_all->GetZaxis()->SetTitleFont(42);
   edxy_all->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
