{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:51:56 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-2.810127,-2.884013,2.253165,6.726379);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(686098.9);
   
   TH1F *edz_all_stack_9 = new TH1F("edz_all_stack_9","stack",100,-2,2);
   edz_all_stack_9->SetBinContent(51,0.1129965);
   edz_all_stack_9->SetBinError(51,0.08247561);
   edz_all_stack_9->SetMinimum(0.002033267);
   edz_all_stack_9->SetMaximum(1761406);
   edz_all_stack_9->SetEntries(2);
   edz_all_stack_9->SetStats(0);
   edz_all_stack_9->SetFillColor(4);
   edz_all_stack_9->SetLineColor(4);
   edz_all_stack_9->SetLineWidth(2);
   edz_all_stack_9->SetMarkerColor(4);
   edz_all_stack_9->SetMarkerStyle(21);
   edz_all_stack_9->SetMarkerSize(0.8);
   edz_all_stack_9->GetXaxis()->SetTitle("Electron d_{z}");
   edz_all_stack_9->GetXaxis()->SetLabelFont(42);
   edz_all_stack_9->GetXaxis()->SetLabelOffset(0.007);
   edz_all_stack_9->GetXaxis()->SetLabelSize(0);
   edz_all_stack_9->GetXaxis()->SetTitleSize(0);
   edz_all_stack_9->GetXaxis()->SetTickLength(0.02);
   edz_all_stack_9->GetXaxis()->SetTitleOffset(0.9);
   edz_all_stack_9->GetXaxis()->SetTitleFont(42);
   edz_all_stack_9->GetYaxis()->SetTitle("Events");
   edz_all_stack_9->GetYaxis()->SetLabelFont(42);
   edz_all_stack_9->GetYaxis()->SetLabelOffset(0.007);
   edz_all_stack_9->GetYaxis()->SetLabelSize(0.035);
   edz_all_stack_9->GetYaxis()->SetTitleSize(0.045);
   edz_all_stack_9->GetYaxis()->SetTickLength(0.02);
   edz_all_stack_9->GetYaxis()->SetTitleOffset(1.55);
   edz_all_stack_9->GetYaxis()->SetTitleFont(42);
   edz_all_stack_9->GetZaxis()->SetLabelFont(42);
   edz_all_stack_9->GetZaxis()->SetLabelOffset(0.007);
   edz_all_stack_9->GetZaxis()->SetLabelSize(0.035);
   edz_all_stack_9->GetZaxis()->SetTitleSize(0.045);
   edz_all_stack_9->GetZaxis()->SetTickLength(0.02);
   edz_all_stack_9->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(edz_all_stack_9);
   
   
   TH1F *edz_all = new TH1F("edz_all","edz_all",100,-2,2);
   edz_all->SetBinContent(51,0.1129965);
   edz_all->SetBinError(51,0.08247561);
   edz_all->SetMinimum(0.01);
   edz_all->SetMaximum(630000);
   edz_all->SetEntries(2);
   edz_all->SetStats(0);
   edz_all->SetFillColor(4);
   edz_all->SetLineColor(4);
   edz_all->SetLineWidth(2);
   edz_all->SetMarkerColor(4);
   edz_all->SetMarkerStyle(21);
   edz_all->SetMarkerSize(0.8);
   edz_all->GetXaxis()->SetTitle("Electron d_{z}");
   edz_all->GetXaxis()->SetLabelFont(42);
   edz_all->GetXaxis()->SetLabelOffset(0.007);
   edz_all->GetXaxis()->SetLabelSize(0);
   edz_all->GetXaxis()->SetTitleSize(0);
   edz_all->GetXaxis()->SetTickLength(0.02);
   edz_all->GetXaxis()->SetTitleOffset(0.9);
   edz_all->GetXaxis()->SetTitleFont(42);
   edz_all->GetYaxis()->SetTitle("Events");
   edz_all->GetYaxis()->SetLabelFont(42);
   edz_all->GetYaxis()->SetLabelOffset(0.007);
   edz_all->GetYaxis()->SetLabelSize(0.035);
   edz_all->GetYaxis()->SetTitleSize(0.045);
   edz_all->GetYaxis()->SetTickLength(0.02);
   edz_all->GetYaxis()->SetTitleOffset(1.55);
   edz_all->GetYaxis()->SetTitleFont(42);
   edz_all->GetZaxis()->SetLabelFont(42);
   edz_all->GetZaxis()->SetLabelOffset(0.007);
   edz_all->GetZaxis()->SetLabelSize(0.035);
   edz_all->GetZaxis()->SetTitleSize(0.045);
   edz_all->GetZaxis()->SetTickLength(0.02);
   edz_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edz_all,"HIST");
   
   TH1F *edz_all = new TH1F("edz_all","edz_all",100,-2,2);
   edz_all->SetBinContent(50,8.183135);
   edz_all->SetBinContent(51,5.384918);
   edz_all->SetBinError(50,2.390685);
   edz_all->SetBinError(51,1.859845);
   edz_all->SetEntries(23);
   edz_all->SetStats(0);
   edz_all->SetFillColor(5);
   edz_all->SetLineColor(5);
   edz_all->SetLineWidth(2);
   edz_all->SetMarkerColor(5);
   edz_all->SetMarkerStyle(21);
   edz_all->SetMarkerSize(0.8);
   edz_all->GetXaxis()->SetLabelFont(42);
   edz_all->GetXaxis()->SetLabelOffset(0.007);
   edz_all->GetXaxis()->SetLabelSize(0.035);
   edz_all->GetXaxis()->SetTitleSize(0.045);
   edz_all->GetXaxis()->SetTickLength(0.02);
   edz_all->GetXaxis()->SetTitleOffset(0.9);
   edz_all->GetXaxis()->SetTitleFont(42);
   edz_all->GetYaxis()->SetLabelFont(42);
   edz_all->GetYaxis()->SetLabelOffset(0.007);
   edz_all->GetYaxis()->SetLabelSize(0.035);
   edz_all->GetYaxis()->SetTitleSize(0.045);
   edz_all->GetYaxis()->SetTickLength(0.02);
   edz_all->GetYaxis()->SetTitleOffset(1.55);
   edz_all->GetYaxis()->SetTitleFont(42);
   edz_all->GetZaxis()->SetLabelFont(42);
   edz_all->GetZaxis()->SetLabelOffset(0.007);
   edz_all->GetZaxis()->SetLabelSize(0.035);
   edz_all->GetZaxis()->SetTitleSize(0.045);
   edz_all->GetZaxis()->SetTickLength(0.02);
   edz_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edz_all,"");
   
   TH1F *edz_all = new TH1F("edz_all","edz_all",100,-2,2);
   edz_all->SetBinContent(49,0.3599512);
   edz_all->SetBinContent(50,24.2129);
   edz_all->SetBinContent(51,28.0563);
   edz_all->SetBinContent(52,0.3945709);
   edz_all->SetBinError(49,0.3599512);
   edz_all->SetBinError(50,3.554439);
   edz_all->SetBinError(51,4.232247);
   edz_all->SetBinError(52,0.3945709);
   edz_all->SetEntries(121);
   edz_all->SetStats(0);
   edz_all->SetFillColor(6);
   edz_all->SetLineColor(6);
   edz_all->SetLineWidth(2);
   edz_all->SetMarkerColor(6);
   edz_all->SetMarkerStyle(21);
   edz_all->SetMarkerSize(0.8);
   edz_all->GetXaxis()->SetLabelFont(42);
   edz_all->GetXaxis()->SetLabelOffset(0.007);
   edz_all->GetXaxis()->SetLabelSize(0.035);
   edz_all->GetXaxis()->SetTitleSize(0.045);
   edz_all->GetXaxis()->SetTickLength(0.02);
   edz_all->GetXaxis()->SetTitleOffset(0.9);
   edz_all->GetXaxis()->SetTitleFont(42);
   edz_all->GetYaxis()->SetLabelFont(42);
   edz_all->GetYaxis()->SetLabelOffset(0.007);
   edz_all->GetYaxis()->SetLabelSize(0.035);
   edz_all->GetYaxis()->SetTitleSize(0.045);
   edz_all->GetYaxis()->SetTickLength(0.02);
   edz_all->GetYaxis()->SetTitleOffset(1.55);
   edz_all->GetYaxis()->SetTitleFont(42);
   edz_all->GetZaxis()->SetLabelFont(42);
   edz_all->GetZaxis()->SetLabelOffset(0.007);
   edz_all->GetZaxis()->SetLabelSize(0.035);
   edz_all->GetZaxis()->SetTitleSize(0.045);
   edz_all->GetZaxis()->SetTickLength(0.02);
   edz_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edz_all,"");
   
   TH1F *edz_all = new TH1F("edz_all","edz_all",100,-2,2);
   edz_all->SetBinContent(49,0.150451);
   edz_all->SetBinContent(50,10.85314);
   edz_all->SetBinContent(51,11.91509);
   edz_all->SetBinContent(52,0.1092584);
   edz_all->SetBinContent(53,0.01838941);
   edz_all->SetBinError(49,0.05413205);
   edz_all->SetBinError(50,0.4581472);
   edz_all->SetBinError(51,0.4810785);
   edz_all->SetBinError(52,0.04339604);
   edz_all->SetBinError(53,0.01838941);
   edz_all->SetEntries(1424);
   edz_all->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   edz_all->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   edz_all->SetLineColor(ci);
   edz_all->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   edz_all->SetMarkerColor(ci);
   edz_all->SetMarkerStyle(21);
   edz_all->SetMarkerSize(0.8);
   edz_all->GetXaxis()->SetLabelFont(42);
   edz_all->GetXaxis()->SetLabelOffset(0.007);
   edz_all->GetXaxis()->SetLabelSize(0.035);
   edz_all->GetXaxis()->SetTitleSize(0.045);
   edz_all->GetXaxis()->SetTickLength(0.02);
   edz_all->GetXaxis()->SetTitleOffset(0.9);
   edz_all->GetXaxis()->SetTitleFont(42);
   edz_all->GetYaxis()->SetLabelFont(42);
   edz_all->GetYaxis()->SetLabelOffset(0.007);
   edz_all->GetYaxis()->SetLabelSize(0.035);
   edz_all->GetYaxis()->SetTitleSize(0.045);
   edz_all->GetYaxis()->SetTickLength(0.02);
   edz_all->GetYaxis()->SetTitleOffset(1.55);
   edz_all->GetYaxis()->SetTitleFont(42);
   edz_all->GetZaxis()->SetLabelFont(42);
   edz_all->GetZaxis()->SetLabelOffset(0.007);
   edz_all->GetZaxis()->SetLabelSize(0.035);
   edz_all->GetZaxis()->SetTitleSize(0.045);
   edz_all->GetZaxis()->SetTickLength(0.02);
   edz_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edz_all,"");
   
   TH1F *edz_all = new TH1F("edz_all","edz_all",100,-2,2);
   edz_all->SetStats(0);
   edz_all->SetFillColor(3);
   edz_all->SetLineColor(3);
   edz_all->SetLineWidth(2);
   edz_all->SetMarkerColor(3);
   edz_all->SetMarkerStyle(21);
   edz_all->SetMarkerSize(0.8);
   edz_all->GetXaxis()->SetLabelFont(42);
   edz_all->GetXaxis()->SetLabelOffset(0.007);
   edz_all->GetXaxis()->SetLabelSize(0.035);
   edz_all->GetXaxis()->SetTitleSize(0.045);
   edz_all->GetXaxis()->SetTickLength(0.02);
   edz_all->GetXaxis()->SetTitleOffset(0.9);
   edz_all->GetXaxis()->SetTitleFont(42);
   edz_all->GetYaxis()->SetLabelFont(42);
   edz_all->GetYaxis()->SetLabelOffset(0.007);
   edz_all->GetYaxis()->SetLabelSize(0.035);
   edz_all->GetYaxis()->SetTitleSize(0.045);
   edz_all->GetYaxis()->SetTickLength(0.02);
   edz_all->GetYaxis()->SetTitleOffset(1.55);
   edz_all->GetYaxis()->SetTitleFont(42);
   edz_all->GetZaxis()->SetLabelFont(42);
   edz_all->GetZaxis()->SetLabelOffset(0.007);
   edz_all->GetZaxis()->SetLabelSize(0.035);
   edz_all->GetZaxis()->SetTitleSize(0.045);
   edz_all->GetZaxis()->SetTickLength(0.02);
   edz_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edz_all,"");
   
   TH1F *edz_all = new TH1F("edz_all","edz_all",100,-2,2);
   edz_all->SetBinContent(50,0.4312102);
   edz_all->SetBinContent(51,0.1685248);
   edz_all->SetBinError(50,0.2353497);
   edz_all->SetBinError(51,0.123209);
   edz_all->SetEntries(7);
   edz_all->SetStats(0);
   edz_all->SetFillColor(3);
   edz_all->SetLineColor(3);
   edz_all->SetLineWidth(2);
   edz_all->SetMarkerColor(3);
   edz_all->SetMarkerStyle(21);
   edz_all->SetMarkerSize(0.8);
   edz_all->GetXaxis()->SetLabelFont(42);
   edz_all->GetXaxis()->SetLabelOffset(0.007);
   edz_all->GetXaxis()->SetLabelSize(0.035);
   edz_all->GetXaxis()->SetTitleSize(0.045);
   edz_all->GetXaxis()->SetTickLength(0.02);
   edz_all->GetXaxis()->SetTitleOffset(0.9);
   edz_all->GetXaxis()->SetTitleFont(42);
   edz_all->GetYaxis()->SetLabelFont(42);
   edz_all->GetYaxis()->SetLabelOffset(0.007);
   edz_all->GetYaxis()->SetLabelSize(0.035);
   edz_all->GetYaxis()->SetTitleSize(0.045);
   edz_all->GetYaxis()->SetTickLength(0.02);
   edz_all->GetYaxis()->SetTitleOffset(1.55);
   edz_all->GetYaxis()->SetTitleFont(42);
   edz_all->GetZaxis()->SetLabelFont(42);
   edz_all->GetZaxis()->SetLabelOffset(0.007);
   edz_all->GetZaxis()->SetLabelSize(0.035);
   edz_all->GetZaxis()->SetTitleSize(0.045);
   edz_all->GetZaxis()->SetTickLength(0.02);
   edz_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edz_all,"");
   
   TH1F *edz_all = new TH1F("edz_all","edz_all",100,-2,2);
   edz_all->SetBinContent(50,0.1237035);
   edz_all->SetBinContent(51,0.1021043);
   edz_all->SetBinError(50,0.02736699);
   edz_all->SetBinError(51,0.02543964);
   edz_all->SetEntries(44);
   edz_all->SetStats(0);
   edz_all->SetFillColor(3);
   edz_all->SetLineColor(3);
   edz_all->SetLineWidth(2);
   edz_all->SetMarkerColor(3);
   edz_all->SetMarkerStyle(21);
   edz_all->SetMarkerSize(0.8);
   edz_all->GetXaxis()->SetLabelFont(42);
   edz_all->GetXaxis()->SetLabelOffset(0.007);
   edz_all->GetXaxis()->SetLabelSize(0.035);
   edz_all->GetXaxis()->SetTitleSize(0.045);
   edz_all->GetXaxis()->SetTickLength(0.02);
   edz_all->GetXaxis()->SetTitleOffset(0.9);
   edz_all->GetXaxis()->SetTitleFont(42);
   edz_all->GetYaxis()->SetLabelFont(42);
   edz_all->GetYaxis()->SetLabelOffset(0.007);
   edz_all->GetYaxis()->SetLabelSize(0.035);
   edz_all->GetYaxis()->SetTitleSize(0.045);
   edz_all->GetYaxis()->SetTickLength(0.02);
   edz_all->GetYaxis()->SetTitleOffset(1.55);
   edz_all->GetYaxis()->SetTitleFont(42);
   edz_all->GetZaxis()->SetLabelFont(42);
   edz_all->GetZaxis()->SetLabelOffset(0.007);
   edz_all->GetZaxis()->SetLabelSize(0.035);
   edz_all->GetZaxis()->SetTitleSize(0.045);
   edz_all->GetZaxis()->SetTickLength(0.02);
   edz_all->GetZaxis()->SetTitleFont(42);
   stack->Add(edz_all,"");
   stack->Draw("hist");
   
   TH1F *edz_all = new TH1F("edz_all","edz_all",100,-2,2);
   edz_all->SetBinContent(50,42);
   edz_all->SetBinContent(51,40);
   edz_all->SetBinError(50,6.480741);
   edz_all->SetBinError(51,6.324555);
   edz_all->SetEntries(82);
   edz_all->SetStats(0);
   edz_all->SetFillColor(1);
   edz_all->SetFillStyle(0);
   edz_all->SetLineWidth(3);
   edz_all->SetMarkerStyle(20);
   edz_all->SetMarkerSize(1.3);
   edz_all->GetXaxis()->SetLabelFont(42);
   edz_all->GetXaxis()->SetLabelOffset(0.007);
   edz_all->GetXaxis()->SetLabelSize(0.035);
   edz_all->GetXaxis()->SetTitleSize(0.045);
   edz_all->GetXaxis()->SetTickLength(0.02);
   edz_all->GetXaxis()->SetTitleOffset(0.9);
   edz_all->GetXaxis()->SetTitleFont(42);
   edz_all->GetYaxis()->SetLabelFont(42);
   edz_all->GetYaxis()->SetLabelOffset(0.007);
   edz_all->GetYaxis()->SetLabelSize(0.035);
   edz_all->GetYaxis()->SetTitleSize(0.045);
   edz_all->GetYaxis()->SetTickLength(0.02);
   edz_all->GetYaxis()->SetTitleOffset(1.55);
   edz_all->GetYaxis()->SetTitleFont(42);
   edz_all->GetZaxis()->SetLabelFont(42);
   edz_all->GetZaxis()->SetLabelOffset(0.007);
   edz_all->GetZaxis()->SetLabelSize(0.035);
   edz_all->GetZaxis()->SetTitleSize(0.045);
   edz_all->GetZaxis()->SetTickLength(0.02);
   edz_all->GetZaxis()->SetTitleFont(42);
   edz_all->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiQCD_noCJV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("edz_all","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("edz_all","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("edz_all","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("edz_all","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("edz_all","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("edz_all","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-2.810127,-0.653951,2.253165,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *edz_all = new TH1F("edz_all","edz_all",100,-2,2);
   edz_all->SetBinContent(50,0.9588144);
   edz_all->SetBinContent(51,0.8766752);
   edz_all->SetBinError(50,0.175521);
   edz_all->SetBinError(51,0.1649089);
   edz_all->SetMinimum(0);
   edz_all->SetMaximum(2);
   edz_all->SetEntries(58.08402);
   edz_all->SetStats(0);
   edz_all->SetFillStyle(0);
   edz_all->SetMarkerStyle(20);
   edz_all->SetMarkerSize(0.8);
   edz_all->GetXaxis()->SetTitle("Electron d_{z}");
   edz_all->GetXaxis()->SetLabelFont(42);
   edz_all->GetXaxis()->SetLabelOffset(0.007);
   edz_all->GetXaxis()->SetLabelSize(0.1);
   edz_all->GetXaxis()->SetTitleSize(0.12);
   edz_all->GetXaxis()->SetTickLength(0.02);
   edz_all->GetXaxis()->SetTitleOffset(0.9);
   edz_all->GetXaxis()->SetTitleFont(42);
   edz_all->GetYaxis()->SetTitle("Data/MC");
   edz_all->GetYaxis()->SetNdivisions(505);
   edz_all->GetYaxis()->SetLabelFont(42);
   edz_all->GetYaxis()->SetLabelOffset(0.007);
   edz_all->GetYaxis()->SetLabelSize(0.1);
   edz_all->GetYaxis()->SetTitleSize(0.12);
   edz_all->GetYaxis()->SetTickLength(0.02);
   edz_all->GetYaxis()->SetTitleOffset(0.55);
   edz_all->GetYaxis()->SetTitleFont(42);
   edz_all->GetZaxis()->SetLabelFont(42);
   edz_all->GetZaxis()->SetLabelOffset(0.007);
   edz_all->GetZaxis()->SetLabelSize(0.035);
   edz_all->GetZaxis()->SetTitleSize(0.045);
   edz_all->GetZaxis()->SetTickLength(0.02);
   edz_all->GetZaxis()->SetTitleFont(42);
   edz_all->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
