{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:50:05 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-85.06329,-0.02150538,446.5823,1.053763);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(0);
   
   TH1F *mt_munu_stack_14 = new TH1F("mt_munu_stack_14","stack",25,0,500);
   mt_munu_stack_14->SetBinContent(0,3.65101);
   mt_munu_stack_14->SetBinError(0,2.515429);
   mt_munu_stack_14->SetMinimum(-0);
   mt_munu_stack_14->SetMaximum(nan);
   mt_munu_stack_14->SetEntries(15);
   mt_munu_stack_14->SetStats(0);
   mt_munu_stack_14->SetFillColor(4);
   mt_munu_stack_14->SetLineColor(4);
   mt_munu_stack_14->SetLineWidth(2);
   mt_munu_stack_14->SetMarkerColor(4);
   mt_munu_stack_14->SetMarkerStyle(21);
   mt_munu_stack_14->SetMarkerSize(0.8);
   mt_munu_stack_14->GetXaxis()->SetTitle("m_{T}(#mu#nu) (GeV)");
   mt_munu_stack_14->GetXaxis()->SetRange(1,21);
   mt_munu_stack_14->GetXaxis()->SetLabelFont(42);
   mt_munu_stack_14->GetXaxis()->SetLabelOffset(0.007);
   mt_munu_stack_14->GetXaxis()->SetLabelSize(0);
   mt_munu_stack_14->GetXaxis()->SetTitleSize(0);
   mt_munu_stack_14->GetXaxis()->SetTickLength(0.02);
   mt_munu_stack_14->GetXaxis()->SetTitleOffset(0.9);
   mt_munu_stack_14->GetXaxis()->SetTitleFont(42);
   mt_munu_stack_14->GetYaxis()->SetTitle("Events");
   mt_munu_stack_14->GetYaxis()->SetLabelFont(42);
   mt_munu_stack_14->GetYaxis()->SetLabelOffset(0.007);
   mt_munu_stack_14->GetYaxis()->SetLabelSize(0.035);
   mt_munu_stack_14->GetYaxis()->SetTitleSize(0.045);
   mt_munu_stack_14->GetYaxis()->SetTickLength(0.02);
   mt_munu_stack_14->GetYaxis()->SetTitleOffset(1.55);
   mt_munu_stack_14->GetYaxis()->SetTitleFont(42);
   mt_munu_stack_14->GetZaxis()->SetLabelFont(42);
   mt_munu_stack_14->GetZaxis()->SetLabelOffset(0.007);
   mt_munu_stack_14->GetZaxis()->SetLabelSize(0.035);
   mt_munu_stack_14->GetZaxis()->SetTitleSize(0.045);
   mt_munu_stack_14->GetZaxis()->SetTickLength(0.02);
   mt_munu_stack_14->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(mt_munu_stack_14);
   
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,3.65101);
   mt_munu->SetBinError(0,2.515429);
   mt_munu->SetMinimum(0.01);
   mt_munu->SetMaximum(0);
   mt_munu->SetEntries(15);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(4);
   mt_munu->SetLineColor(4);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(4);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetTitle("m_{T}(#mu#nu) (GeV)");
   mt_munu->GetXaxis()->SetRange(1,21);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0);
   mt_munu->GetXaxis()->SetTitleSize(0);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetTitle("Events");
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"HIST");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,28.20787);
   mt_munu->SetBinError(0,4.271425);
   mt_munu->SetEntries(55);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(5);
   mt_munu->SetLineColor(5);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(5);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,110.9694);
   mt_munu->SetBinError(0,9.006425);
   mt_munu->SetEntries(214);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(6);
   mt_munu->SetLineColor(6);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(6);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,39.15017);
   mt_munu->SetBinError(0,0.888053);
   mt_munu->SetEntries(2244);
   mt_munu->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   mt_munu->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   mt_munu->SetLineColor(ci);
   mt_munu->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   mt_munu->SetMarkerColor(ci);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(3);
   mt_munu->SetLineColor(3);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(3);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,2.00501);
   mt_munu->SetBinError(0,0.4896062);
   mt_munu->SetEntries(24);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(3);
   mt_munu->SetLineColor(3);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(3);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,0.5065808);
   mt_munu->SetBinError(0,0.05861714);
   mt_munu->SetEntries(86);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(3);
   mt_munu->SetLineColor(3);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(3);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   stack->Draw("hist");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,119);
   mt_munu->SetBinError(0,10.90871);
   mt_munu->SetEntries(119);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(1);
   mt_munu->SetFillStyle(0);
   mt_munu->SetLineWidth(3);
   mt_munu->SetMarkerStyle(20);
   mt_munu->SetMarkerSize(1.3);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   mt_munu->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiSIGNAL_CJVpass");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("mt_munu","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("mt_munu","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_munu","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_munu","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_munu","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_munu","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-85.06329,-0.653951,446.5823,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,0.658044);
   mt_munu->SetBinError(0,0.07048512);
   mt_munu->SetMinimum(0);
   mt_munu->SetMaximum(2);
   mt_munu->SetStats(0);
   mt_munu->SetFillStyle(0);
   mt_munu->SetMarkerStyle(20);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetTitle("m_{T}(#mu#nu) (GeV)");
   mt_munu->GetXaxis()->SetRange(1,21);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.1);
   mt_munu->GetXaxis()->SetTitleSize(0.12);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetTitle("Data/MC");
   mt_munu->GetYaxis()->SetNdivisions(505);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.1);
   mt_munu->GetYaxis()->SetTitleSize(0.12);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(0.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   mt_munu->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
