{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:51:15 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-0.8101265,-2.473424,4.253165,121.1978);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMaximum(109.5373);
   
   TH1F *taggingJetsFlavour_stack_9 = new TH1F("taggingJetsFlavour_stack_9","stack",4,0,4);
   taggingJetsFlavour_stack_9->SetBinContent(1,0.1129965);
   taggingJetsFlavour_stack_9->SetBinError(1,0.08247561);
   taggingJetsFlavour_stack_9->SetMinimum(0);
   taggingJetsFlavour_stack_9->SetMaximum(115.0142);
   taggingJetsFlavour_stack_9->SetEntries(2);
   taggingJetsFlavour_stack_9->SetStats(0);
   taggingJetsFlavour_stack_9->SetFillColor(4);
   taggingJetsFlavour_stack_9->SetLineColor(4);
   taggingJetsFlavour_stack_9->SetLineWidth(2);
   taggingJetsFlavour_stack_9->SetMarkerColor(4);
   taggingJetsFlavour_stack_9->SetMarkerStyle(21);
   taggingJetsFlavour_stack_9->SetMarkerSize(0.8);
   taggingJetsFlavour_stack_9->GetXaxis()->SetTitle("#tau as tagging jet");
   taggingJetsFlavour_stack_9->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour_stack_9->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour_stack_9->GetXaxis()->SetLabelSize(0);
   taggingJetsFlavour_stack_9->GetXaxis()->SetTitleSize(0);
   taggingJetsFlavour_stack_9->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour_stack_9->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour_stack_9->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour_stack_9->GetYaxis()->SetTitle("Events");
   taggingJetsFlavour_stack_9->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour_stack_9->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour_stack_9->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour_stack_9->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour_stack_9->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour_stack_9->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour_stack_9->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour_stack_9->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour_stack_9->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour_stack_9->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour_stack_9->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour_stack_9->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour_stack_9->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(taggingJetsFlavour_stack_9);
   
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,0.1129965);
   taggingJetsFlavour->SetBinError(1,0.08247561);
   taggingJetsFlavour->SetMaximum(99.22);
   taggingJetsFlavour->SetEntries(2);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(4);
   taggingJetsFlavour->SetLineColor(4);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(4);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetTitle("#tau as tagging jet");
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetTitle("Events");
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"HIST");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,13.56805);
   taggingJetsFlavour->SetBinError(1,3.028927);
   taggingJetsFlavour->SetEntries(23);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(5);
   taggingJetsFlavour->SetLineColor(5);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(5);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,53.02372);
   taggingJetsFlavour->SetBinError(1,5.552585);
   taggingJetsFlavour->SetEntries(121);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(6);
   taggingJetsFlavour->SetLineColor(6);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(6);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,22.99641);
   taggingJetsFlavour->SetBinContent(2,0.03240715);
   taggingJetsFlavour->SetBinContent(3,0.01751485);
   taggingJetsFlavour->SetBinError(1,0.6671806);
   taggingJetsFlavour->SetBinError(2,0.03240715);
   taggingJetsFlavour->SetBinError(3,0.01751485);
   taggingJetsFlavour->SetEntries(1424);
   taggingJetsFlavour->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   taggingJetsFlavour->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   taggingJetsFlavour->SetLineColor(ci);
   taggingJetsFlavour->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   taggingJetsFlavour->SetMarkerColor(ci);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(3);
   taggingJetsFlavour->SetLineColor(3);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(3);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,0.599735);
   taggingJetsFlavour->SetBinError(1,0.2656501);
   taggingJetsFlavour->SetEntries(7);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(3);
   taggingJetsFlavour->SetLineColor(3);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(3);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,0.2258078);
   taggingJetsFlavour->SetBinError(1,0.03736479);
   taggingJetsFlavour->SetEntries(44);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(3);
   taggingJetsFlavour->SetLineColor(3);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(3);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   stack->Draw("hist");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,82);
   taggingJetsFlavour->SetBinError(1,9.055385);
   taggingJetsFlavour->SetEntries(82);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(1);
   taggingJetsFlavour->SetFillStyle(0);
   taggingJetsFlavour->SetLineWidth(3);
   taggingJetsFlavour->SetMarkerStyle(20);
   taggingJetsFlavour->SetMarkerSize(1.3);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   taggingJetsFlavour->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiQCD_noCJV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("taggingJetsFlavour","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("taggingJetsFlavour","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-0.8101265,-0.653951,4.253165,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,0.906942);
   taggingJetsFlavour->SetBinError(1,0.1187791);
   taggingJetsFlavour->SetMinimum(0);
   taggingJetsFlavour->SetMaximum(2);
   taggingJetsFlavour->SetEntries(58.30141);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillStyle(0);
   taggingJetsFlavour->SetMarkerStyle(20);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetTitle("#tau as tagging jet");
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.1);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.12);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetTitle("Data/MC");
   taggingJetsFlavour->GetYaxis()->SetNdivisions(505);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.1);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.12);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(0.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   taggingJetsFlavour->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
