{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:50:40 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-85.06329,-2.564402,446.5823,2.344749);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(70.99971);
   
   TH1F *taupt_1_stack_9 = new TH1F("taupt_1_stack_9","stack",50,0,1000);
   taupt_1_stack_9->SetBinContent(0,0.1129965);
   taupt_1_stack_9->SetBinError(0,0.08247561);
   taupt_1_stack_9->SetMinimum(0.003418069);
   taupt_1_stack_9->SetMaximum(125.6873);
   taupt_1_stack_9->SetEntries(2);
   taupt_1_stack_9->SetStats(0);
   taupt_1_stack_9->SetFillColor(4);
   taupt_1_stack_9->SetLineColor(4);
   taupt_1_stack_9->SetLineWidth(2);
   taupt_1_stack_9->SetMarkerColor(4);
   taupt_1_stack_9->SetMarkerStyle(21);
   taupt_1_stack_9->SetMarkerSize(0.8);
   taupt_1_stack_9->GetXaxis()->SetTitle("Leading tau p_{T} [GeV]");
   taupt_1_stack_9->GetXaxis()->SetRange(1,21);
   taupt_1_stack_9->GetXaxis()->SetLabelFont(42);
   taupt_1_stack_9->GetXaxis()->SetLabelOffset(0.007);
   taupt_1_stack_9->GetXaxis()->SetLabelSize(0);
   taupt_1_stack_9->GetXaxis()->SetTitleSize(0);
   taupt_1_stack_9->GetXaxis()->SetTickLength(0.02);
   taupt_1_stack_9->GetXaxis()->SetTitleOffset(0.9);
   taupt_1_stack_9->GetXaxis()->SetTitleFont(42);
   taupt_1_stack_9->GetYaxis()->SetTitle("Events");
   taupt_1_stack_9->GetYaxis()->SetLabelFont(42);
   taupt_1_stack_9->GetYaxis()->SetLabelOffset(0.007);
   taupt_1_stack_9->GetYaxis()->SetLabelSize(0.035);
   taupt_1_stack_9->GetYaxis()->SetTitleSize(0.045);
   taupt_1_stack_9->GetYaxis()->SetTickLength(0.02);
   taupt_1_stack_9->GetYaxis()->SetTitleOffset(1.55);
   taupt_1_stack_9->GetYaxis()->SetTitleFont(42);
   taupt_1_stack_9->GetZaxis()->SetLabelFont(42);
   taupt_1_stack_9->GetZaxis()->SetLabelOffset(0.007);
   taupt_1_stack_9->GetZaxis()->SetLabelSize(0.035);
   taupt_1_stack_9->GetZaxis()->SetTitleSize(0.045);
   taupt_1_stack_9->GetZaxis()->SetTickLength(0.02);
   taupt_1_stack_9->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(taupt_1_stack_9);
   
   
   TH1F *taupt_1 = new TH1F("taupt_1","taupt_1",50,0,1000);
   taupt_1->SetBinContent(0,0.1129965);
   taupt_1->SetBinError(0,0.08247561);
   taupt_1->SetMinimum(0.01);
   taupt_1->SetMaximum(600);
   taupt_1->SetEntries(2);
   taupt_1->SetStats(0);
   taupt_1->SetFillColor(4);
   taupt_1->SetLineColor(4);
   taupt_1->SetLineWidth(2);
   taupt_1->SetMarkerColor(4);
   taupt_1->SetMarkerStyle(21);
   taupt_1->SetMarkerSize(0.8);
   taupt_1->GetXaxis()->SetTitle("Leading tau p_{T} [GeV]");
   taupt_1->GetXaxis()->SetRange(1,21);
   taupt_1->GetXaxis()->SetLabelFont(42);
   taupt_1->GetXaxis()->SetLabelOffset(0.007);
   taupt_1->GetXaxis()->SetLabelSize(0);
   taupt_1->GetXaxis()->SetTitleSize(0);
   taupt_1->GetXaxis()->SetTickLength(0.02);
   taupt_1->GetXaxis()->SetTitleOffset(0.9);
   taupt_1->GetXaxis()->SetTitleFont(42);
   taupt_1->GetYaxis()->SetTitle("Events");
   taupt_1->GetYaxis()->SetLabelFont(42);
   taupt_1->GetYaxis()->SetLabelOffset(0.007);
   taupt_1->GetYaxis()->SetLabelSize(0.035);
   taupt_1->GetYaxis()->SetTitleSize(0.045);
   taupt_1->GetYaxis()->SetTickLength(0.02);
   taupt_1->GetYaxis()->SetTitleOffset(1.55);
   taupt_1->GetYaxis()->SetTitleFont(42);
   taupt_1->GetZaxis()->SetLabelFont(42);
   taupt_1->GetZaxis()->SetLabelOffset(0.007);
   taupt_1->GetZaxis()->SetLabelSize(0.035);
   taupt_1->GetZaxis()->SetTitleSize(0.045);
   taupt_1->GetZaxis()->SetTickLength(0.02);
   taupt_1->GetZaxis()->SetTitleFont(42);
   stack->Add(taupt_1,"HIST");
   
   TH1F *taupt_1 = new TH1F("taupt_1","taupt_1",50,0,1000);
   taupt_1->SetBinContent(0,13.56805);
   taupt_1->SetBinError(0,3.028927);
   taupt_1->SetEntries(23);
   taupt_1->SetStats(0);
   taupt_1->SetFillColor(5);
   taupt_1->SetLineColor(5);
   taupt_1->SetLineWidth(2);
   taupt_1->SetMarkerColor(5);
   taupt_1->SetMarkerStyle(21);
   taupt_1->SetMarkerSize(0.8);
   taupt_1->GetXaxis()->SetLabelFont(42);
   taupt_1->GetXaxis()->SetLabelOffset(0.007);
   taupt_1->GetXaxis()->SetLabelSize(0.035);
   taupt_1->GetXaxis()->SetTitleSize(0.045);
   taupt_1->GetXaxis()->SetTickLength(0.02);
   taupt_1->GetXaxis()->SetTitleOffset(0.9);
   taupt_1->GetXaxis()->SetTitleFont(42);
   taupt_1->GetYaxis()->SetLabelFont(42);
   taupt_1->GetYaxis()->SetLabelOffset(0.007);
   taupt_1->GetYaxis()->SetLabelSize(0.035);
   taupt_1->GetYaxis()->SetTitleSize(0.045);
   taupt_1->GetYaxis()->SetTickLength(0.02);
   taupt_1->GetYaxis()->SetTitleOffset(1.55);
   taupt_1->GetYaxis()->SetTitleFont(42);
   taupt_1->GetZaxis()->SetLabelFont(42);
   taupt_1->GetZaxis()->SetLabelOffset(0.007);
   taupt_1->GetZaxis()->SetLabelSize(0.035);
   taupt_1->GetZaxis()->SetTitleSize(0.045);
   taupt_1->GetZaxis()->SetTickLength(0.02);
   taupt_1->GetZaxis()->SetTitleFont(42);
   stack->Add(taupt_1,"");
   
   TH1F *taupt_1 = new TH1F("taupt_1","taupt_1",50,0,1000);
   taupt_1->SetBinContent(0,53.02372);
   taupt_1->SetBinError(0,5.552585);
   taupt_1->SetEntries(121);
   taupt_1->SetStats(0);
   taupt_1->SetFillColor(6);
   taupt_1->SetLineColor(6);
   taupt_1->SetLineWidth(2);
   taupt_1->SetMarkerColor(6);
   taupt_1->SetMarkerStyle(21);
   taupt_1->SetMarkerSize(0.8);
   taupt_1->GetXaxis()->SetLabelFont(42);
   taupt_1->GetXaxis()->SetLabelOffset(0.007);
   taupt_1->GetXaxis()->SetLabelSize(0.035);
   taupt_1->GetXaxis()->SetTitleSize(0.045);
   taupt_1->GetXaxis()->SetTickLength(0.02);
   taupt_1->GetXaxis()->SetTitleOffset(0.9);
   taupt_1->GetXaxis()->SetTitleFont(42);
   taupt_1->GetYaxis()->SetLabelFont(42);
   taupt_1->GetYaxis()->SetLabelOffset(0.007);
   taupt_1->GetYaxis()->SetLabelSize(0.035);
   taupt_1->GetYaxis()->SetTitleSize(0.045);
   taupt_1->GetYaxis()->SetTickLength(0.02);
   taupt_1->GetYaxis()->SetTitleOffset(1.55);
   taupt_1->GetYaxis()->SetTitleFont(42);
   taupt_1->GetZaxis()->SetLabelFont(42);
   taupt_1->GetZaxis()->SetLabelOffset(0.007);
   taupt_1->GetZaxis()->SetLabelSize(0.035);
   taupt_1->GetZaxis()->SetTitleSize(0.045);
   taupt_1->GetZaxis()->SetTickLength(0.02);
   taupt_1->GetZaxis()->SetTitleFont(42);
   stack->Add(taupt_1,"");
   
   TH1F *taupt_1 = new TH1F("taupt_1","taupt_1",50,0,1000);
   taupt_1->SetBinContent(0,22.68053);
   taupt_1->SetBinContent(2,0.2718278);
   taupt_1->SetBinContent(3,0.03856466);
   taupt_1->SetBinContent(4,0.005496214);
   taupt_1->SetBinContent(6,0.01751485);
   taupt_1->SetBinContent(7,0.03240715);
   taupt_1->SetBinError(0,0.6627972);
   taupt_1->SetBinError(2,0.07102983);
   taupt_1->SetBinError(3,0.0274663);
   taupt_1->SetBinError(4,0.005496214);
   taupt_1->SetBinError(6,0.01751485);
   taupt_1->SetBinError(7,0.03240715);
   taupt_1->SetEntries(1424);
   taupt_1->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   taupt_1->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   taupt_1->SetLineColor(ci);
   taupt_1->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   taupt_1->SetMarkerColor(ci);
   taupt_1->SetMarkerStyle(21);
   taupt_1->SetMarkerSize(0.8);
   taupt_1->GetXaxis()->SetLabelFont(42);
   taupt_1->GetXaxis()->SetLabelOffset(0.007);
   taupt_1->GetXaxis()->SetLabelSize(0.035);
   taupt_1->GetXaxis()->SetTitleSize(0.045);
   taupt_1->GetXaxis()->SetTickLength(0.02);
   taupt_1->GetXaxis()->SetTitleOffset(0.9);
   taupt_1->GetXaxis()->SetTitleFont(42);
   taupt_1->GetYaxis()->SetLabelFont(42);
   taupt_1->GetYaxis()->SetLabelOffset(0.007);
   taupt_1->GetYaxis()->SetLabelSize(0.035);
   taupt_1->GetYaxis()->SetTitleSize(0.045);
   taupt_1->GetYaxis()->SetTickLength(0.02);
   taupt_1->GetYaxis()->SetTitleOffset(1.55);
   taupt_1->GetYaxis()->SetTitleFont(42);
   taupt_1->GetZaxis()->SetLabelFont(42);
   taupt_1->GetZaxis()->SetLabelOffset(0.007);
   taupt_1->GetZaxis()->SetLabelSize(0.035);
   taupt_1->GetZaxis()->SetTitleSize(0.045);
   taupt_1->GetZaxis()->SetTickLength(0.02);
   taupt_1->GetZaxis()->SetTitleFont(42);
   stack->Add(taupt_1,"");
   
   TH1F *taupt_1 = new TH1F("taupt_1","taupt_1",50,0,1000);
   taupt_1->SetStats(0);
   taupt_1->SetFillColor(3);
   taupt_1->SetLineColor(3);
   taupt_1->SetLineWidth(2);
   taupt_1->SetMarkerColor(3);
   taupt_1->SetMarkerStyle(21);
   taupt_1->SetMarkerSize(0.8);
   taupt_1->GetXaxis()->SetLabelFont(42);
   taupt_1->GetXaxis()->SetLabelOffset(0.007);
   taupt_1->GetXaxis()->SetLabelSize(0.035);
   taupt_1->GetXaxis()->SetTitleSize(0.045);
   taupt_1->GetXaxis()->SetTickLength(0.02);
   taupt_1->GetXaxis()->SetTitleOffset(0.9);
   taupt_1->GetXaxis()->SetTitleFont(42);
   taupt_1->GetYaxis()->SetLabelFont(42);
   taupt_1->GetYaxis()->SetLabelOffset(0.007);
   taupt_1->GetYaxis()->SetLabelSize(0.035);
   taupt_1->GetYaxis()->SetTitleSize(0.045);
   taupt_1->GetYaxis()->SetTickLength(0.02);
   taupt_1->GetYaxis()->SetTitleOffset(1.55);
   taupt_1->GetYaxis()->SetTitleFont(42);
   taupt_1->GetZaxis()->SetLabelFont(42);
   taupt_1->GetZaxis()->SetLabelOffset(0.007);
   taupt_1->GetZaxis()->SetLabelSize(0.035);
   taupt_1->GetZaxis()->SetTitleSize(0.045);
   taupt_1->GetZaxis()->SetTickLength(0.02);
   taupt_1->GetZaxis()->SetTitleFont(42);
   stack->Add(taupt_1,"");
   
   TH1F *taupt_1 = new TH1F("taupt_1","taupt_1",50,0,1000);
   taupt_1->SetBinContent(0,0.404484);
   taupt_1->SetBinContent(2,0.195251);
   taupt_1->SetBinError(0,0.1801305);
   taupt_1->SetBinError(2,0.195251);
   taupt_1->SetEntries(7);
   taupt_1->SetStats(0);
   taupt_1->SetFillColor(3);
   taupt_1->SetLineColor(3);
   taupt_1->SetLineWidth(2);
   taupt_1->SetMarkerColor(3);
   taupt_1->SetMarkerStyle(21);
   taupt_1->SetMarkerSize(0.8);
   taupt_1->GetXaxis()->SetLabelFont(42);
   taupt_1->GetXaxis()->SetLabelOffset(0.007);
   taupt_1->GetXaxis()->SetLabelSize(0.035);
   taupt_1->GetXaxis()->SetTitleSize(0.045);
   taupt_1->GetXaxis()->SetTickLength(0.02);
   taupt_1->GetXaxis()->SetTitleOffset(0.9);
   taupt_1->GetXaxis()->SetTitleFont(42);
   taupt_1->GetYaxis()->SetLabelFont(42);
   taupt_1->GetYaxis()->SetLabelOffset(0.007);
   taupt_1->GetYaxis()->SetLabelSize(0.035);
   taupt_1->GetYaxis()->SetTitleSize(0.045);
   taupt_1->GetYaxis()->SetTickLength(0.02);
   taupt_1->GetYaxis()->SetTitleOffset(1.55);
   taupt_1->GetYaxis()->SetTitleFont(42);
   taupt_1->GetZaxis()->SetLabelFont(42);
   taupt_1->GetZaxis()->SetLabelOffset(0.007);
   taupt_1->GetZaxis()->SetLabelSize(0.035);
   taupt_1->GetZaxis()->SetTitleSize(0.045);
   taupt_1->GetZaxis()->SetTickLength(0.02);
   taupt_1->GetZaxis()->SetTitleFont(42);
   stack->Add(taupt_1,"");
   
   TH1F *taupt_1 = new TH1F("taupt_1","taupt_1",50,0,1000);
   taupt_1->SetBinContent(0,0.2086282);
   taupt_1->SetBinContent(2,0.006252578);
   taupt_1->SetBinContent(3,0.01092706);
   taupt_1->SetBinError(0,0.03599286);
   taupt_1->SetBinError(2,0.006252578);
   taupt_1->SetBinError(3,0.007845156);
   taupt_1->SetEntries(44);
   taupt_1->SetStats(0);
   taupt_1->SetFillColor(3);
   taupt_1->SetLineColor(3);
   taupt_1->SetLineWidth(2);
   taupt_1->SetMarkerColor(3);
   taupt_1->SetMarkerStyle(21);
   taupt_1->SetMarkerSize(0.8);
   taupt_1->GetXaxis()->SetLabelFont(42);
   taupt_1->GetXaxis()->SetLabelOffset(0.007);
   taupt_1->GetXaxis()->SetLabelSize(0.035);
   taupt_1->GetXaxis()->SetTitleSize(0.045);
   taupt_1->GetXaxis()->SetTickLength(0.02);
   taupt_1->GetXaxis()->SetTitleOffset(0.9);
   taupt_1->GetXaxis()->SetTitleFont(42);
   taupt_1->GetYaxis()->SetLabelFont(42);
   taupt_1->GetYaxis()->SetLabelOffset(0.007);
   taupt_1->GetYaxis()->SetLabelSize(0.035);
   taupt_1->GetYaxis()->SetTitleSize(0.045);
   taupt_1->GetYaxis()->SetTickLength(0.02);
   taupt_1->GetYaxis()->SetTitleOffset(1.55);
   taupt_1->GetYaxis()->SetTitleFont(42);
   taupt_1->GetZaxis()->SetLabelFont(42);
   taupt_1->GetZaxis()->SetLabelOffset(0.007);
   taupt_1->GetZaxis()->SetLabelSize(0.035);
   taupt_1->GetZaxis()->SetTitleSize(0.045);
   taupt_1->GetZaxis()->SetTickLength(0.02);
   taupt_1->GetZaxis()->SetTitleFont(42);
   stack->Add(taupt_1,"");
   stack->Draw("hist");
   
   TH1F *taupt_1 = new TH1F("taupt_1","taupt_1",50,0,1000);
   taupt_1->SetBinContent(0,78);
   taupt_1->SetBinContent(2,4);
   taupt_1->SetBinError(0,8.831761);
   taupt_1->SetBinError(2,2);
   taupt_1->SetEntries(82);
   taupt_1->SetStats(0);
   taupt_1->SetFillColor(1);
   taupt_1->SetFillStyle(0);
   taupt_1->SetLineWidth(3);
   taupt_1->SetMarkerStyle(20);
   taupt_1->SetMarkerSize(1.3);
   taupt_1->GetXaxis()->SetLabelFont(42);
   taupt_1->GetXaxis()->SetLabelOffset(0.007);
   taupt_1->GetXaxis()->SetLabelSize(0.035);
   taupt_1->GetXaxis()->SetTitleSize(0.045);
   taupt_1->GetXaxis()->SetTickLength(0.02);
   taupt_1->GetXaxis()->SetTitleOffset(0.9);
   taupt_1->GetXaxis()->SetTitleFont(42);
   taupt_1->GetYaxis()->SetLabelFont(42);
   taupt_1->GetYaxis()->SetLabelOffset(0.007);
   taupt_1->GetYaxis()->SetLabelSize(0.035);
   taupt_1->GetYaxis()->SetTitleSize(0.045);
   taupt_1->GetYaxis()->SetTickLength(0.02);
   taupt_1->GetYaxis()->SetTitleOffset(1.55);
   taupt_1->GetYaxis()->SetTitleFont(42);
   taupt_1->GetZaxis()->SetLabelFont(42);
   taupt_1->GetZaxis()->SetLabelOffset(0.007);
   taupt_1->GetZaxis()->SetLabelSize(0.035);
   taupt_1->GetZaxis()->SetTitleSize(0.045);
   taupt_1->GetZaxis()->SetTickLength(0.02);
   taupt_1->GetZaxis()->SetTitleFont(42);
   taupt_1->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiQCD_noCJV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("taupt_1","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("taupt_1","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taupt_1","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taupt_1","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taupt_1","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taupt_1","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-85.06329,-0.653951,446.5823,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *taupt_1 = new TH1F("taupt_1","taupt_1",50,0,1000);
   taupt_1->SetBinContent(0,0.8677715);
   taupt_1->SetBinContent(2,8.450738);
   taupt_1->SetBinError(0,0.1158747);
   taupt_1->SetBinError(2,5.62373);
   taupt_1->SetMinimum(0);
   taupt_1->SetMaximum(2);
   taupt_1->SetEntries(2.258085);
   taupt_1->SetStats(0);
   taupt_1->SetFillStyle(0);
   taupt_1->SetMarkerStyle(20);
   taupt_1->SetMarkerSize(0.8);
   taupt_1->GetXaxis()->SetTitle("Leading tau p_{T} [GeV]");
   taupt_1->GetXaxis()->SetRange(1,21);
   taupt_1->GetXaxis()->SetLabelFont(42);
   taupt_1->GetXaxis()->SetLabelOffset(0.007);
   taupt_1->GetXaxis()->SetLabelSize(0.1);
   taupt_1->GetXaxis()->SetTitleSize(0.12);
   taupt_1->GetXaxis()->SetTickLength(0.02);
   taupt_1->GetXaxis()->SetTitleOffset(0.9);
   taupt_1->GetXaxis()->SetTitleFont(42);
   taupt_1->GetYaxis()->SetTitle("Data/MC");
   taupt_1->GetYaxis()->SetNdivisions(505);
   taupt_1->GetYaxis()->SetLabelFont(42);
   taupt_1->GetYaxis()->SetLabelOffset(0.007);
   taupt_1->GetYaxis()->SetLabelSize(0.1);
   taupt_1->GetYaxis()->SetTitleSize(0.12);
   taupt_1->GetYaxis()->SetTickLength(0.02);
   taupt_1->GetYaxis()->SetTitleOffset(0.55);
   taupt_1->GetYaxis()->SetTitleFont(42);
   taupt_1->GetZaxis()->SetLabelFont(42);
   taupt_1->GetZaxis()->SetLabelOffset(0.007);
   taupt_1->GetZaxis()->SetLabelSize(0.035);
   taupt_1->GetZaxis()->SetTitleSize(0.045);
   taupt_1->GetZaxis()->SetTickLength(0.02);
   taupt_1->GetZaxis()->SetTitleFont(42);
   taupt_1->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
