{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:53:33 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-4.316456,-0.02150538,3.911392,1.053763);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(0);
   
   TH1F *eeta_1_stack_4 = new TH1F("eeta_1_stack_4","stack",20,-5,5);
   eeta_1_stack_4->SetBinContent(0,157.1909);
   eeta_1_stack_4->SetBinError(0,16.5899);
   eeta_1_stack_4->SetMinimum(-0);
   eeta_1_stack_4->SetMaximum(nan);
   eeta_1_stack_4->SetEntries(394);
   eeta_1_stack_4->SetStats(0);
   eeta_1_stack_4->SetFillColor(4);
   eeta_1_stack_4->SetLineColor(4);
   eeta_1_stack_4->SetLineWidth(2);
   eeta_1_stack_4->SetMarkerColor(4);
   eeta_1_stack_4->SetMarkerStyle(21);
   eeta_1_stack_4->SetMarkerSize(0.8);
   eeta_1_stack_4->GetXaxis()->SetTitle("Leading electron #eta");
   eeta_1_stack_4->GetXaxis()->SetRange(5,17);
   eeta_1_stack_4->GetXaxis()->SetLabelFont(42);
   eeta_1_stack_4->GetXaxis()->SetLabelOffset(0.007);
   eeta_1_stack_4->GetXaxis()->SetLabelSize(0);
   eeta_1_stack_4->GetXaxis()->SetTitleSize(0);
   eeta_1_stack_4->GetXaxis()->SetTickLength(0.02);
   eeta_1_stack_4->GetXaxis()->SetTitleOffset(0.9);
   eeta_1_stack_4->GetXaxis()->SetTitleFont(42);
   eeta_1_stack_4->GetYaxis()->SetTitle("Events");
   eeta_1_stack_4->GetYaxis()->SetLabelFont(42);
   eeta_1_stack_4->GetYaxis()->SetLabelOffset(0.007);
   eeta_1_stack_4->GetYaxis()->SetLabelSize(0.035);
   eeta_1_stack_4->GetYaxis()->SetTitleSize(0.045);
   eeta_1_stack_4->GetYaxis()->SetTickLength(0.02);
   eeta_1_stack_4->GetYaxis()->SetTitleOffset(1.55);
   eeta_1_stack_4->GetYaxis()->SetTitleFont(42);
   eeta_1_stack_4->GetZaxis()->SetLabelFont(42);
   eeta_1_stack_4->GetZaxis()->SetLabelOffset(0.007);
   eeta_1_stack_4->GetZaxis()->SetLabelSize(0.035);
   eeta_1_stack_4->GetZaxis()->SetTitleSize(0.045);
   eeta_1_stack_4->GetZaxis()->SetTickLength(0.02);
   eeta_1_stack_4->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(eeta_1_stack_4);
   
   
   TH1F *eeta_1 = new TH1F("eeta_1","eeta_1",20,-5,5);
   eeta_1->SetBinContent(0,157.1909);
   eeta_1->SetBinError(0,16.5899);
   eeta_1->SetMinimum(0.01);
   eeta_1->SetMaximum(0);
   eeta_1->SetEntries(394);
   eeta_1->SetStats(0);
   eeta_1->SetFillColor(4);
   eeta_1->SetLineColor(4);
   eeta_1->SetLineWidth(2);
   eeta_1->SetMarkerColor(4);
   eeta_1->SetMarkerStyle(21);
   eeta_1->SetMarkerSize(0.8);
   eeta_1->GetXaxis()->SetTitle("Leading electron #eta");
   eeta_1->GetXaxis()->SetRange(5,17);
   eeta_1->GetXaxis()->SetLabelFont(42);
   eeta_1->GetXaxis()->SetLabelOffset(0.007);
   eeta_1->GetXaxis()->SetLabelSize(0);
   eeta_1->GetXaxis()->SetTitleSize(0);
   eeta_1->GetXaxis()->SetTickLength(0.02);
   eeta_1->GetXaxis()->SetTitleOffset(0.9);
   eeta_1->GetXaxis()->SetTitleFont(42);
   eeta_1->GetYaxis()->SetTitle("Events");
   eeta_1->GetYaxis()->SetLabelFont(42);
   eeta_1->GetYaxis()->SetLabelOffset(0.007);
   eeta_1->GetYaxis()->SetLabelSize(0.035);
   eeta_1->GetYaxis()->SetTitleSize(0.045);
   eeta_1->GetYaxis()->SetTickLength(0.02);
   eeta_1->GetYaxis()->SetTitleOffset(1.55);
   eeta_1->GetYaxis()->SetTitleFont(42);
   eeta_1->GetZaxis()->SetLabelFont(42);
   eeta_1->GetZaxis()->SetLabelOffset(0.007);
   eeta_1->GetZaxis()->SetLabelSize(0.035);
   eeta_1->GetZaxis()->SetTitleSize(0.045);
   eeta_1->GetZaxis()->SetTickLength(0.02);
   eeta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(eeta_1,"HIST");
   
   TH1F *eeta_1 = new TH1F("eeta_1","eeta_1",20,-5,5);
   eeta_1->SetBinContent(0,784.2059);
   eeta_1->SetBinError(0,23.66579);
   eeta_1->SetEntries(1429);
   eeta_1->SetStats(0);
   eeta_1->SetFillColor(5);
   eeta_1->SetLineColor(5);
   eeta_1->SetLineWidth(2);
   eeta_1->SetMarkerColor(5);
   eeta_1->SetMarkerStyle(21);
   eeta_1->SetMarkerSize(0.8);
   eeta_1->GetXaxis()->SetLabelFont(42);
   eeta_1->GetXaxis()->SetLabelOffset(0.007);
   eeta_1->GetXaxis()->SetLabelSize(0.035);
   eeta_1->GetXaxis()->SetTitleSize(0.045);
   eeta_1->GetXaxis()->SetTickLength(0.02);
   eeta_1->GetXaxis()->SetTitleOffset(0.9);
   eeta_1->GetXaxis()->SetTitleFont(42);
   eeta_1->GetYaxis()->SetLabelFont(42);
   eeta_1->GetYaxis()->SetLabelOffset(0.007);
   eeta_1->GetYaxis()->SetLabelSize(0.035);
   eeta_1->GetYaxis()->SetTitleSize(0.045);
   eeta_1->GetYaxis()->SetTickLength(0.02);
   eeta_1->GetYaxis()->SetTitleOffset(1.55);
   eeta_1->GetYaxis()->SetTitleFont(42);
   eeta_1->GetZaxis()->SetLabelFont(42);
   eeta_1->GetZaxis()->SetLabelOffset(0.007);
   eeta_1->GetZaxis()->SetLabelSize(0.035);
   eeta_1->GetZaxis()->SetTitleSize(0.045);
   eeta_1->GetZaxis()->SetTickLength(0.02);
   eeta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(eeta_1,"");
   
   TH1F *eeta_1 = new TH1F("eeta_1","eeta_1",20,-5,5);
   eeta_1->SetBinContent(0,3540.841);
   eeta_1->SetBinError(0,50.49543);
   eeta_1->SetEntries(7249);
   eeta_1->SetStats(0);
   eeta_1->SetFillColor(6);
   eeta_1->SetLineColor(6);
   eeta_1->SetLineWidth(2);
   eeta_1->SetMarkerColor(6);
   eeta_1->SetMarkerStyle(21);
   eeta_1->SetMarkerSize(0.8);
   eeta_1->GetXaxis()->SetLabelFont(42);
   eeta_1->GetXaxis()->SetLabelOffset(0.007);
   eeta_1->GetXaxis()->SetLabelSize(0.035);
   eeta_1->GetXaxis()->SetTitleSize(0.045);
   eeta_1->GetXaxis()->SetTickLength(0.02);
   eeta_1->GetXaxis()->SetTitleOffset(0.9);
   eeta_1->GetXaxis()->SetTitleFont(42);
   eeta_1->GetYaxis()->SetLabelFont(42);
   eeta_1->GetYaxis()->SetLabelOffset(0.007);
   eeta_1->GetYaxis()->SetLabelSize(0.035);
   eeta_1->GetYaxis()->SetTitleSize(0.045);
   eeta_1->GetYaxis()->SetTickLength(0.02);
   eeta_1->GetYaxis()->SetTitleOffset(1.55);
   eeta_1->GetYaxis()->SetTitleFont(42);
   eeta_1->GetZaxis()->SetLabelFont(42);
   eeta_1->GetZaxis()->SetLabelOffset(0.007);
   eeta_1->GetZaxis()->SetLabelSize(0.035);
   eeta_1->GetZaxis()->SetTitleSize(0.045);
   eeta_1->GetZaxis()->SetTickLength(0.02);
   eeta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(eeta_1,"");
   
   TH1F *eeta_1 = new TH1F("eeta_1","eeta_1",20,-5,5);
   eeta_1->SetBinContent(0,1002.359);
   eeta_1->SetBinError(0,4.519283);
   eeta_1->SetEntries(57337);
   eeta_1->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   eeta_1->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   eeta_1->SetLineColor(ci);
   eeta_1->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   eeta_1->SetMarkerColor(ci);
   eeta_1->SetMarkerStyle(21);
   eeta_1->SetMarkerSize(0.8);
   eeta_1->GetXaxis()->SetLabelFont(42);
   eeta_1->GetXaxis()->SetLabelOffset(0.007);
   eeta_1->GetXaxis()->SetLabelSize(0.035);
   eeta_1->GetXaxis()->SetTitleSize(0.045);
   eeta_1->GetXaxis()->SetTickLength(0.02);
   eeta_1->GetXaxis()->SetTitleOffset(0.9);
   eeta_1->GetXaxis()->SetTitleFont(42);
   eeta_1->GetYaxis()->SetLabelFont(42);
   eeta_1->GetYaxis()->SetLabelOffset(0.007);
   eeta_1->GetYaxis()->SetLabelSize(0.035);
   eeta_1->GetYaxis()->SetTitleSize(0.045);
   eeta_1->GetYaxis()->SetTickLength(0.02);
   eeta_1->GetYaxis()->SetTitleOffset(1.55);
   eeta_1->GetYaxis()->SetTitleFont(42);
   eeta_1->GetZaxis()->SetLabelFont(42);
   eeta_1->GetZaxis()->SetLabelOffset(0.007);
   eeta_1->GetZaxis()->SetLabelSize(0.035);
   eeta_1->GetZaxis()->SetTitleSize(0.045);
   eeta_1->GetZaxis()->SetTickLength(0.02);
   eeta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(eeta_1,"");
   
   TH1F *eeta_1 = new TH1F("eeta_1","eeta_1",20,-5,5);
   eeta_1->SetStats(0);
   eeta_1->SetFillColor(3);
   eeta_1->SetLineColor(3);
   eeta_1->SetLineWidth(2);
   eeta_1->SetMarkerColor(3);
   eeta_1->SetMarkerStyle(21);
   eeta_1->SetMarkerSize(0.8);
   eeta_1->GetXaxis()->SetLabelFont(42);
   eeta_1->GetXaxis()->SetLabelOffset(0.007);
   eeta_1->GetXaxis()->SetLabelSize(0.035);
   eeta_1->GetXaxis()->SetTitleSize(0.045);
   eeta_1->GetXaxis()->SetTickLength(0.02);
   eeta_1->GetXaxis()->SetTitleOffset(0.9);
   eeta_1->GetXaxis()->SetTitleFont(42);
   eeta_1->GetYaxis()->SetLabelFont(42);
   eeta_1->GetYaxis()->SetLabelOffset(0.007);
   eeta_1->GetYaxis()->SetLabelSize(0.035);
   eeta_1->GetYaxis()->SetTitleSize(0.045);
   eeta_1->GetYaxis()->SetTickLength(0.02);
   eeta_1->GetYaxis()->SetTitleOffset(1.55);
   eeta_1->GetYaxis()->SetTitleFont(42);
   eeta_1->GetZaxis()->SetLabelFont(42);
   eeta_1->GetZaxis()->SetLabelOffset(0.007);
   eeta_1->GetZaxis()->SetLabelSize(0.035);
   eeta_1->GetZaxis()->SetTitleSize(0.045);
   eeta_1->GetZaxis()->SetTickLength(0.02);
   eeta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(eeta_1,"");
   
   TH1F *eeta_1 = new TH1F("eeta_1","eeta_1",20,-5,5);
   eeta_1->SetBinContent(0,181.6289);
   eeta_1->SetBinError(0,4.693416);
   eeta_1->SetEntries(2010);
   eeta_1->SetStats(0);
   eeta_1->SetFillColor(3);
   eeta_1->SetLineColor(3);
   eeta_1->SetLineWidth(2);
   eeta_1->SetMarkerColor(3);
   eeta_1->SetMarkerStyle(21);
   eeta_1->SetMarkerSize(0.8);
   eeta_1->GetXaxis()->SetLabelFont(42);
   eeta_1->GetXaxis()->SetLabelOffset(0.007);
   eeta_1->GetXaxis()->SetLabelSize(0.035);
   eeta_1->GetXaxis()->SetTitleSize(0.045);
   eeta_1->GetXaxis()->SetTickLength(0.02);
   eeta_1->GetXaxis()->SetTitleOffset(0.9);
   eeta_1->GetXaxis()->SetTitleFont(42);
   eeta_1->GetYaxis()->SetLabelFont(42);
   eeta_1->GetYaxis()->SetLabelOffset(0.007);
   eeta_1->GetYaxis()->SetLabelSize(0.035);
   eeta_1->GetYaxis()->SetTitleSize(0.045);
   eeta_1->GetYaxis()->SetTickLength(0.02);
   eeta_1->GetYaxis()->SetTitleOffset(1.55);
   eeta_1->GetYaxis()->SetTitleFont(42);
   eeta_1->GetZaxis()->SetLabelFont(42);
   eeta_1->GetZaxis()->SetLabelOffset(0.007);
   eeta_1->GetZaxis()->SetLabelSize(0.035);
   eeta_1->GetZaxis()->SetTitleSize(0.045);
   eeta_1->GetZaxis()->SetTickLength(0.02);
   eeta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(eeta_1,"");
   
   TH1F *eeta_1 = new TH1F("eeta_1","eeta_1",20,-5,5);
   eeta_1->SetBinContent(0,59.01981);
   eeta_1->SetBinError(0,0.7664306);
   eeta_1->SetEntries(7811);
   eeta_1->SetStats(0);
   eeta_1->SetFillColor(3);
   eeta_1->SetLineColor(3);
   eeta_1->SetLineWidth(2);
   eeta_1->SetMarkerColor(3);
   eeta_1->SetMarkerStyle(21);
   eeta_1->SetMarkerSize(0.8);
   eeta_1->GetXaxis()->SetLabelFont(42);
   eeta_1->GetXaxis()->SetLabelOffset(0.007);
   eeta_1->GetXaxis()->SetLabelSize(0.035);
   eeta_1->GetXaxis()->SetTitleSize(0.045);
   eeta_1->GetXaxis()->SetTickLength(0.02);
   eeta_1->GetXaxis()->SetTitleOffset(0.9);
   eeta_1->GetXaxis()->SetTitleFont(42);
   eeta_1->GetYaxis()->SetLabelFont(42);
   eeta_1->GetYaxis()->SetLabelOffset(0.007);
   eeta_1->GetYaxis()->SetLabelSize(0.035);
   eeta_1->GetYaxis()->SetTitleSize(0.045);
   eeta_1->GetYaxis()->SetTickLength(0.02);
   eeta_1->GetYaxis()->SetTitleOffset(1.55);
   eeta_1->GetYaxis()->SetTitleFont(42);
   eeta_1->GetZaxis()->SetLabelFont(42);
   eeta_1->GetZaxis()->SetLabelOffset(0.007);
   eeta_1->GetZaxis()->SetLabelSize(0.035);
   eeta_1->GetZaxis()->SetTitleSize(0.045);
   eeta_1->GetZaxis()->SetTickLength(0.02);
   eeta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(eeta_1,"");
   stack->Draw("hist");
   
   TH1F *eeta_1 = new TH1F("eeta_1","eeta_1",20,-5,5);
   eeta_1->SetBinContent(0,4130);
   eeta_1->SetBinError(0,64.26508);
   eeta_1->SetEntries(4130);
   eeta_1->SetStats(0);
   eeta_1->SetFillColor(1);
   eeta_1->SetFillStyle(0);
   eeta_1->SetLineWidth(3);
   eeta_1->SetMarkerStyle(20);
   eeta_1->SetMarkerSize(1.3);
   eeta_1->GetXaxis()->SetLabelFont(42);
   eeta_1->GetXaxis()->SetLabelOffset(0.007);
   eeta_1->GetXaxis()->SetLabelSize(0.035);
   eeta_1->GetXaxis()->SetTitleSize(0.045);
   eeta_1->GetXaxis()->SetTickLength(0.02);
   eeta_1->GetXaxis()->SetTitleOffset(0.9);
   eeta_1->GetXaxis()->SetTitleFont(42);
   eeta_1->GetYaxis()->SetLabelFont(42);
   eeta_1->GetYaxis()->SetLabelOffset(0.007);
   eeta_1->GetYaxis()->SetLabelSize(0.035);
   eeta_1->GetYaxis()->SetTitleSize(0.045);
   eeta_1->GetYaxis()->SetTickLength(0.02);
   eeta_1->GetYaxis()->SetTitleOffset(1.55);
   eeta_1->GetYaxis()->SetTitleFont(42);
   eeta_1->GetZaxis()->SetLabelFont(42);
   eeta_1->GetZaxis()->SetLabelOffset(0.007);
   eeta_1->GetZaxis()->SetLabelSize(0.035);
   eeta_1->GetZaxis()->SetTitleSize(0.045);
   eeta_1->GetZaxis()->SetTickLength(0.02);
   eeta_1->GetZaxis()->SetTitleFont(42);
   eeta_1->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"AN");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("eeta_1","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("eeta_1","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("eeta_1","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("eeta_1","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("eeta_1","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("eeta_1","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-4.316456,-0.653951,3.911392,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *eeta_1 = new TH1F("eeta_1","eeta_1",20,-5,5);
   eeta_1->SetBinContent(0,0.7417313);
   eeta_1->SetBinError(0,0.0137536);
   eeta_1->SetMinimum(0);
   eeta_1->SetMaximum(2);
   eeta_1->SetStats(0);
   eeta_1->SetFillStyle(0);
   eeta_1->SetMarkerStyle(20);
   eeta_1->SetMarkerSize(0.8);
   eeta_1->GetXaxis()->SetTitle("Leading electron #eta");
   eeta_1->GetXaxis()->SetRange(5,17);
   eeta_1->GetXaxis()->SetLabelFont(42);
   eeta_1->GetXaxis()->SetLabelOffset(0.007);
   eeta_1->GetXaxis()->SetLabelSize(0.1);
   eeta_1->GetXaxis()->SetTitleSize(0.12);
   eeta_1->GetXaxis()->SetTickLength(0.02);
   eeta_1->GetXaxis()->SetTitleOffset(0.9);
   eeta_1->GetXaxis()->SetTitleFont(42);
   eeta_1->GetYaxis()->SetTitle("Data/MC");
   eeta_1->GetYaxis()->SetNdivisions(505);
   eeta_1->GetYaxis()->SetLabelFont(42);
   eeta_1->GetYaxis()->SetLabelOffset(0.007);
   eeta_1->GetYaxis()->SetLabelSize(0.1);
   eeta_1->GetYaxis()->SetTitleSize(0.12);
   eeta_1->GetYaxis()->SetTickLength(0.02);
   eeta_1->GetYaxis()->SetTitleOffset(0.55);
   eeta_1->GetYaxis()->SetTitleFont(42);
   eeta_1->GetZaxis()->SetLabelFont(42);
   eeta_1->GetZaxis()->SetLabelOffset(0.007);
   eeta_1->GetZaxis()->SetLabelSize(0.035);
   eeta_1->GetZaxis()->SetTitleSize(0.045);
   eeta_1->GetZaxis()->SetTickLength(0.02);
   eeta_1->GetZaxis()->SetTitleFont(42);
   eeta_1->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
