{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:53:09 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-85.06329,-0.02150538,446.5823,1.053763);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(0);
   
   TH1F *mt_enu_stack_15 = new TH1F("mt_enu_stack_15","stack",25,0,500);
   mt_enu_stack_15->SetBinContent(0,15.86491);
   mt_enu_stack_15->SetBinError(0,5.728998);
   mt_enu_stack_15->SetMinimum(-0);
   mt_enu_stack_15->SetMaximum(nan);
   mt_enu_stack_15->SetEntries(25);
   mt_enu_stack_15->SetStats(0);
   mt_enu_stack_15->SetFillColor(4);
   mt_enu_stack_15->SetLineColor(4);
   mt_enu_stack_15->SetLineWidth(2);
   mt_enu_stack_15->SetMarkerColor(4);
   mt_enu_stack_15->SetMarkerStyle(21);
   mt_enu_stack_15->SetMarkerSize(0.8);
   mt_enu_stack_15->GetXaxis()->SetTitle("m_{T}(e#nu) (GeV)");
   mt_enu_stack_15->GetXaxis()->SetRange(1,21);
   mt_enu_stack_15->GetXaxis()->SetLabelFont(42);
   mt_enu_stack_15->GetXaxis()->SetLabelOffset(0.007);
   mt_enu_stack_15->GetXaxis()->SetLabelSize(0);
   mt_enu_stack_15->GetXaxis()->SetTitleSize(0);
   mt_enu_stack_15->GetXaxis()->SetTickLength(0.02);
   mt_enu_stack_15->GetXaxis()->SetTitleOffset(0.9);
   mt_enu_stack_15->GetXaxis()->SetTitleFont(42);
   mt_enu_stack_15->GetYaxis()->SetTitle("Events");
   mt_enu_stack_15->GetYaxis()->SetLabelFont(42);
   mt_enu_stack_15->GetYaxis()->SetLabelOffset(0.007);
   mt_enu_stack_15->GetYaxis()->SetLabelSize(0.035);
   mt_enu_stack_15->GetYaxis()->SetTitleSize(0.045);
   mt_enu_stack_15->GetYaxis()->SetTickLength(0.02);
   mt_enu_stack_15->GetYaxis()->SetTitleOffset(1.55);
   mt_enu_stack_15->GetYaxis()->SetTitleFont(42);
   mt_enu_stack_15->GetZaxis()->SetLabelFont(42);
   mt_enu_stack_15->GetZaxis()->SetLabelOffset(0.007);
   mt_enu_stack_15->GetZaxis()->SetLabelSize(0.035);
   mt_enu_stack_15->GetZaxis()->SetTitleSize(0.045);
   mt_enu_stack_15->GetZaxis()->SetTickLength(0.02);
   mt_enu_stack_15->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(mt_enu_stack_15);
   
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,15.86491);
   mt_enu->SetBinError(0,5.728998);
   mt_enu->SetMinimum(0.01);
   mt_enu->SetMaximum(0);
   mt_enu->SetEntries(25);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(4);
   mt_enu->SetLineColor(4);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(4);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetTitle("m_{T}(e#nu) (GeV)");
   mt_enu->GetXaxis()->SetRange(1,21);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0);
   mt_enu->GetXaxis()->SetTitleSize(0);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetTitle("Events");
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"HIST");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,51.21121);
   mt_enu->SetBinError(0,6.002522);
   mt_enu->SetEntries(93);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(5);
   mt_enu->SetLineColor(5);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(5);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,299.278);
   mt_enu->SetBinError(0,15.12703);
   mt_enu->SetEntries(586);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(6);
   mt_enu->SetLineColor(6);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(6);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,106.7736);
   mt_enu->SetBinError(0,1.46323);
   mt_enu->SetEntries(6175);
   mt_enu->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   mt_enu->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   mt_enu->SetLineColor(ci);
   mt_enu->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   mt_enu->SetMarkerColor(ci);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(3);
   mt_enu->SetLineColor(3);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(3);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,14.30372);
   mt_enu->SetBinError(0,1.363886);
   mt_enu->SetEntries(159);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(3);
   mt_enu->SetLineColor(3);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(3);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,5.653256);
   mt_enu->SetBinError(0,0.2369064);
   mt_enu->SetEntries(756);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(3);
   mt_enu->SetLineColor(3);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(3);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   stack->Draw("hist");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,355);
   mt_enu->SetBinError(0,18.84144);
   mt_enu->SetEntries(355);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(1);
   mt_enu->SetFillStyle(0);
   mt_enu->SetLineWidth(3);
   mt_enu->SetMarkerStyle(20);
   mt_enu->SetMarkerSize(1.3);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   mt_enu->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiQCD_CJVpass");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("mt_enu","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("mt_enu","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_enu","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_enu","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_enu","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_enu","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-85.06329,-0.653951,446.5823,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,0.7438921);
   mt_enu->SetBinError(0,0.04703436);
   mt_enu->SetMinimum(0);
   mt_enu->SetMaximum(2);
   mt_enu->SetStats(0);
   mt_enu->SetFillStyle(0);
   mt_enu->SetMarkerStyle(20);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetTitle("m_{T}(e#nu) (GeV)");
   mt_enu->GetXaxis()->SetRange(1,21);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.1);
   mt_enu->GetXaxis()->SetTitleSize(0.12);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetTitle("Data/MC");
   mt_enu->GetYaxis()->SetNdivisions(505);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.1);
   mt_enu->GetYaxis()->SetTitleSize(0.12);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(0.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   mt_enu->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
