{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:54:33 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-1.405063,-2.932601,1.126582,7.533008);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(3766414);
   
   TH1F *mudxy_all_stack_15 = new TH1F("mudxy_all_stack_15","stack",100,-1,1);
   mudxy_all_stack_15->SetBinContent(50,10.66735);
   mudxy_all_stack_15->SetBinContent(51,5.197567);
   mudxy_all_stack_15->SetBinError(50,4.537996);
   mudxy_all_stack_15->SetBinError(51,3.496858);
   mudxy_all_stack_15->SetMinimum(0.001891087);
   mudxy_all_stack_15->SetMaximum(1.022651e+07);
   mudxy_all_stack_15->SetEntries(25);
   mudxy_all_stack_15->SetStats(0);
   mudxy_all_stack_15->SetFillColor(4);
   mudxy_all_stack_15->SetLineColor(4);
   mudxy_all_stack_15->SetLineWidth(2);
   mudxy_all_stack_15->SetMarkerColor(4);
   mudxy_all_stack_15->SetMarkerStyle(21);
   mudxy_all_stack_15->SetMarkerSize(0.8);
   mudxy_all_stack_15->GetXaxis()->SetTitle("Muon d_{xy}");
   mudxy_all_stack_15->GetXaxis()->SetLabelFont(42);
   mudxy_all_stack_15->GetXaxis()->SetLabelOffset(0.007);
   mudxy_all_stack_15->GetXaxis()->SetLabelSize(0);
   mudxy_all_stack_15->GetXaxis()->SetTitleSize(0);
   mudxy_all_stack_15->GetXaxis()->SetTickLength(0.02);
   mudxy_all_stack_15->GetXaxis()->SetTitleOffset(0.9);
   mudxy_all_stack_15->GetXaxis()->SetTitleFont(42);
   mudxy_all_stack_15->GetYaxis()->SetTitle("Events");
   mudxy_all_stack_15->GetYaxis()->SetLabelFont(42);
   mudxy_all_stack_15->GetYaxis()->SetLabelOffset(0.007);
   mudxy_all_stack_15->GetYaxis()->SetLabelSize(0.035);
   mudxy_all_stack_15->GetYaxis()->SetTitleSize(0.045);
   mudxy_all_stack_15->GetYaxis()->SetTickLength(0.02);
   mudxy_all_stack_15->GetYaxis()->SetTitleOffset(1.55);
   mudxy_all_stack_15->GetYaxis()->SetTitleFont(42);
   mudxy_all_stack_15->GetZaxis()->SetLabelFont(42);
   mudxy_all_stack_15->GetZaxis()->SetLabelOffset(0.007);
   mudxy_all_stack_15->GetZaxis()->SetLabelSize(0.035);
   mudxy_all_stack_15->GetZaxis()->SetTitleSize(0.045);
   mudxy_all_stack_15->GetZaxis()->SetTickLength(0.02);
   mudxy_all_stack_15->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(mudxy_all_stack_15);
   
   
   TH1F *mudxy_all = new TH1F("mudxy_all","mudxy_all",100,-1,1);
   mudxy_all->SetBinContent(50,10.66735);
   mudxy_all->SetBinContent(51,5.197567);
   mudxy_all->SetBinError(50,4.537996);
   mudxy_all->SetBinError(51,3.496858);
   mudxy_all->SetMinimum(0.01);
   mudxy_all->SetMaximum(3120000);
   mudxy_all->SetEntries(25);
   mudxy_all->SetStats(0);
   mudxy_all->SetFillColor(4);
   mudxy_all->SetLineColor(4);
   mudxy_all->SetLineWidth(2);
   mudxy_all->SetMarkerColor(4);
   mudxy_all->SetMarkerStyle(21);
   mudxy_all->SetMarkerSize(0.8);
   mudxy_all->GetXaxis()->SetTitle("Muon d_{xy}");
   mudxy_all->GetXaxis()->SetLabelFont(42);
   mudxy_all->GetXaxis()->SetLabelOffset(0.007);
   mudxy_all->GetXaxis()->SetLabelSize(0);
   mudxy_all->GetXaxis()->SetTitleSize(0);
   mudxy_all->GetXaxis()->SetTickLength(0.02);
   mudxy_all->GetXaxis()->SetTitleOffset(0.9);
   mudxy_all->GetXaxis()->SetTitleFont(42);
   mudxy_all->GetYaxis()->SetTitle("Events");
   mudxy_all->GetYaxis()->SetLabelFont(42);
   mudxy_all->GetYaxis()->SetLabelOffset(0.007);
   mudxy_all->GetYaxis()->SetLabelSize(0.035);
   mudxy_all->GetYaxis()->SetTitleSize(0.045);
   mudxy_all->GetYaxis()->SetTickLength(0.02);
   mudxy_all->GetYaxis()->SetTitleOffset(1.55);
   mudxy_all->GetYaxis()->SetTitleFont(42);
   mudxy_all->GetZaxis()->SetLabelFont(42);
   mudxy_all->GetZaxis()->SetLabelOffset(0.007);
   mudxy_all->GetZaxis()->SetLabelSize(0.035);
   mudxy_all->GetZaxis()->SetTitleSize(0.045);
   mudxy_all->GetZaxis()->SetTickLength(0.02);
   mudxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(mudxy_all,"HIST");
   
   TH1F *mudxy_all = new TH1F("mudxy_all","mudxy_all",100,-1,1);
   mudxy_all->SetBinContent(50,25.83015);
   mudxy_all->SetBinContent(51,25.38106);
   mudxy_all->SetBinError(50,4.319259);
   mudxy_all->SetBinError(51,4.168246);
   mudxy_all->SetEntries(93);
   mudxy_all->SetStats(0);
   mudxy_all->SetFillColor(5);
   mudxy_all->SetLineColor(5);
   mudxy_all->SetLineWidth(2);
   mudxy_all->SetMarkerColor(5);
   mudxy_all->SetMarkerStyle(21);
   mudxy_all->SetMarkerSize(0.8);
   mudxy_all->GetXaxis()->SetLabelFont(42);
   mudxy_all->GetXaxis()->SetLabelOffset(0.007);
   mudxy_all->GetXaxis()->SetLabelSize(0.035);
   mudxy_all->GetXaxis()->SetTitleSize(0.045);
   mudxy_all->GetXaxis()->SetTickLength(0.02);
   mudxy_all->GetXaxis()->SetTitleOffset(0.9);
   mudxy_all->GetXaxis()->SetTitleFont(42);
   mudxy_all->GetYaxis()->SetLabelFont(42);
   mudxy_all->GetYaxis()->SetLabelOffset(0.007);
   mudxy_all->GetYaxis()->SetLabelSize(0.035);
   mudxy_all->GetYaxis()->SetTitleSize(0.045);
   mudxy_all->GetYaxis()->SetTickLength(0.02);
   mudxy_all->GetYaxis()->SetTitleOffset(1.55);
   mudxy_all->GetYaxis()->SetTitleFont(42);
   mudxy_all->GetZaxis()->SetLabelFont(42);
   mudxy_all->GetZaxis()->SetLabelOffset(0.007);
   mudxy_all->GetZaxis()->SetLabelSize(0.035);
   mudxy_all->GetZaxis()->SetTitleSize(0.045);
   mudxy_all->GetZaxis()->SetTickLength(0.02);
   mudxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(mudxy_all,"");
   
   TH1F *mudxy_all = new TH1F("mudxy_all","mudxy_all",100,-1,1);
   mudxy_all->SetBinContent(49,0.3076004);
   mudxy_all->SetBinContent(50,151.194);
   mudxy_all->SetBinContent(51,146.9107);
   mudxy_all->SetBinContent(52,0.8656403);
   mudxy_all->SetBinError(49,0.3076004);
   mudxy_all->SetBinError(50,10.02568);
   mudxy_all->SetBinError(51,11.30678);
   mudxy_all->SetBinError(52,0.6121317);
   mudxy_all->SetEntries(586);
   mudxy_all->SetStats(0);
   mudxy_all->SetFillColor(6);
   mudxy_all->SetLineColor(6);
   mudxy_all->SetLineWidth(2);
   mudxy_all->SetMarkerColor(6);
   mudxy_all->SetMarkerStyle(21);
   mudxy_all->SetMarkerSize(0.8);
   mudxy_all->GetXaxis()->SetLabelFont(42);
   mudxy_all->GetXaxis()->SetLabelOffset(0.007);
   mudxy_all->GetXaxis()->SetLabelSize(0.035);
   mudxy_all->GetXaxis()->SetTitleSize(0.045);
   mudxy_all->GetXaxis()->SetTickLength(0.02);
   mudxy_all->GetXaxis()->SetTitleOffset(0.9);
   mudxy_all->GetXaxis()->SetTitleFont(42);
   mudxy_all->GetYaxis()->SetLabelFont(42);
   mudxy_all->GetYaxis()->SetLabelOffset(0.007);
   mudxy_all->GetYaxis()->SetLabelSize(0.035);
   mudxy_all->GetYaxis()->SetTitleSize(0.045);
   mudxy_all->GetYaxis()->SetTickLength(0.02);
   mudxy_all->GetYaxis()->SetTitleOffset(1.55);
   mudxy_all->GetYaxis()->SetTitleFont(42);
   mudxy_all->GetZaxis()->SetLabelFont(42);
   mudxy_all->GetZaxis()->SetLabelOffset(0.007);
   mudxy_all->GetZaxis()->SetLabelSize(0.035);
   mudxy_all->GetZaxis()->SetTitleSize(0.045);
   mudxy_all->GetZaxis()->SetTickLength(0.02);
   mudxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(mudxy_all,"");
   
   TH1F *mudxy_all = new TH1F("mudxy_all","mudxy_all",100,-1,1);
   mudxy_all->SetBinContent(49,0.2691633);
   mudxy_all->SetBinContent(50,53.77159);
   mudxy_all->SetBinContent(51,52.59379);
   mudxy_all->SetBinContent(52,0.1389985);
   mudxy_all->SetBinError(49,0.0784897);
   mudxy_all->SetBinError(50,1.033681);
   mudxy_all->SetBinError(51,1.031036);
   mudxy_all->SetBinError(52,0.05788366);
   mudxy_all->SetEntries(6175);
   mudxy_all->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   mudxy_all->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   mudxy_all->SetLineColor(ci);
   mudxy_all->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   mudxy_all->SetMarkerColor(ci);
   mudxy_all->SetMarkerStyle(21);
   mudxy_all->SetMarkerSize(0.8);
   mudxy_all->GetXaxis()->SetLabelFont(42);
   mudxy_all->GetXaxis()->SetLabelOffset(0.007);
   mudxy_all->GetXaxis()->SetLabelSize(0.035);
   mudxy_all->GetXaxis()->SetTitleSize(0.045);
   mudxy_all->GetXaxis()->SetTickLength(0.02);
   mudxy_all->GetXaxis()->SetTitleOffset(0.9);
   mudxy_all->GetXaxis()->SetTitleFont(42);
   mudxy_all->GetYaxis()->SetLabelFont(42);
   mudxy_all->GetYaxis()->SetLabelOffset(0.007);
   mudxy_all->GetYaxis()->SetLabelSize(0.035);
   mudxy_all->GetYaxis()->SetTitleSize(0.045);
   mudxy_all->GetYaxis()->SetTickLength(0.02);
   mudxy_all->GetYaxis()->SetTitleOffset(1.55);
   mudxy_all->GetYaxis()->SetTitleFont(42);
   mudxy_all->GetZaxis()->SetLabelFont(42);
   mudxy_all->GetZaxis()->SetLabelOffset(0.007);
   mudxy_all->GetZaxis()->SetLabelSize(0.035);
   mudxy_all->GetZaxis()->SetTitleSize(0.045);
   mudxy_all->GetZaxis()->SetTickLength(0.02);
   mudxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(mudxy_all,"");
   
   TH1F *mudxy_all = new TH1F("mudxy_all","mudxy_all",100,-1,1);
   mudxy_all->SetStats(0);
   mudxy_all->SetFillColor(3);
   mudxy_all->SetLineColor(3);
   mudxy_all->SetLineWidth(2);
   mudxy_all->SetMarkerColor(3);
   mudxy_all->SetMarkerStyle(21);
   mudxy_all->SetMarkerSize(0.8);
   mudxy_all->GetXaxis()->SetLabelFont(42);
   mudxy_all->GetXaxis()->SetLabelOffset(0.007);
   mudxy_all->GetXaxis()->SetLabelSize(0.035);
   mudxy_all->GetXaxis()->SetTitleSize(0.045);
   mudxy_all->GetXaxis()->SetTickLength(0.02);
   mudxy_all->GetXaxis()->SetTitleOffset(0.9);
   mudxy_all->GetXaxis()->SetTitleFont(42);
   mudxy_all->GetYaxis()->SetLabelFont(42);
   mudxy_all->GetYaxis()->SetLabelOffset(0.007);
   mudxy_all->GetYaxis()->SetLabelSize(0.035);
   mudxy_all->GetYaxis()->SetTitleSize(0.045);
   mudxy_all->GetYaxis()->SetTickLength(0.02);
   mudxy_all->GetYaxis()->SetTitleOffset(1.55);
   mudxy_all->GetYaxis()->SetTitleFont(42);
   mudxy_all->GetZaxis()->SetLabelFont(42);
   mudxy_all->GetZaxis()->SetLabelOffset(0.007);
   mudxy_all->GetZaxis()->SetLabelSize(0.035);
   mudxy_all->GetZaxis()->SetTitleSize(0.045);
   mudxy_all->GetZaxis()->SetTickLength(0.02);
   mudxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(mudxy_all,"");
   
   TH1F *mudxy_all = new TH1F("mudxy_all","mudxy_all",100,-1,1);
   mudxy_all->SetBinContent(49,0.2097036);
   mudxy_all->SetBinContent(50,6.907229);
   mudxy_all->SetBinContent(51,7.103679);
   mudxy_all->SetBinContent(52,0.08310858);
   mudxy_all->SetBinError(49,0.2097036);
   mudxy_all->SetBinError(50,1.006736);
   mudxy_all->SetBinError(51,0.8920681);
   mudxy_all->SetBinError(52,0.08310858);
   mudxy_all->SetEntries(159);
   mudxy_all->SetStats(0);
   mudxy_all->SetFillColor(3);
   mudxy_all->SetLineColor(3);
   mudxy_all->SetLineWidth(2);
   mudxy_all->SetMarkerColor(3);
   mudxy_all->SetMarkerStyle(21);
   mudxy_all->SetMarkerSize(0.8);
   mudxy_all->GetXaxis()->SetLabelFont(42);
   mudxy_all->GetXaxis()->SetLabelOffset(0.007);
   mudxy_all->GetXaxis()->SetLabelSize(0.035);
   mudxy_all->GetXaxis()->SetTitleSize(0.045);
   mudxy_all->GetXaxis()->SetTickLength(0.02);
   mudxy_all->GetXaxis()->SetTitleOffset(0.9);
   mudxy_all->GetXaxis()->SetTitleFont(42);
   mudxy_all->GetYaxis()->SetLabelFont(42);
   mudxy_all->GetYaxis()->SetLabelOffset(0.007);
   mudxy_all->GetYaxis()->SetLabelSize(0.035);
   mudxy_all->GetYaxis()->SetTitleSize(0.045);
   mudxy_all->GetYaxis()->SetTickLength(0.02);
   mudxy_all->GetYaxis()->SetTitleOffset(1.55);
   mudxy_all->GetYaxis()->SetTitleFont(42);
   mudxy_all->GetZaxis()->SetLabelFont(42);
   mudxy_all->GetZaxis()->SetLabelOffset(0.007);
   mudxy_all->GetZaxis()->SetLabelSize(0.035);
   mudxy_all->GetZaxis()->SetTitleSize(0.045);
   mudxy_all->GetZaxis()->SetTickLength(0.02);
   mudxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(mudxy_all,"");
   
   TH1F *mudxy_all = new TH1F("mudxy_all","mudxy_all",100,-1,1);
   mudxy_all->SetBinContent(48,0.006474282);
   mudxy_all->SetBinContent(49,0.005546494);
   mudxy_all->SetBinContent(50,2.723918);
   mudxy_all->SetBinContent(51,2.916079);
   mudxy_all->SetBinContent(53,0.001235729);
   mudxy_all->SetBinError(48,0.006474282);
   mudxy_all->SetBinError(49,0.005546494);
   mudxy_all->SetBinError(50,0.1660361);
   mudxy_all->SetBinError(51,0.1687674);
   mudxy_all->SetBinError(53,0.001235729);
   mudxy_all->SetEntries(756);
   mudxy_all->SetStats(0);
   mudxy_all->SetFillColor(3);
   mudxy_all->SetLineColor(3);
   mudxy_all->SetLineWidth(2);
   mudxy_all->SetMarkerColor(3);
   mudxy_all->SetMarkerStyle(21);
   mudxy_all->SetMarkerSize(0.8);
   mudxy_all->GetXaxis()->SetLabelFont(42);
   mudxy_all->GetXaxis()->SetLabelOffset(0.007);
   mudxy_all->GetXaxis()->SetLabelSize(0.035);
   mudxy_all->GetXaxis()->SetTitleSize(0.045);
   mudxy_all->GetXaxis()->SetTickLength(0.02);
   mudxy_all->GetXaxis()->SetTitleOffset(0.9);
   mudxy_all->GetXaxis()->SetTitleFont(42);
   mudxy_all->GetYaxis()->SetLabelFont(42);
   mudxy_all->GetYaxis()->SetLabelOffset(0.007);
   mudxy_all->GetYaxis()->SetLabelSize(0.035);
   mudxy_all->GetYaxis()->SetTitleSize(0.045);
   mudxy_all->GetYaxis()->SetTickLength(0.02);
   mudxy_all->GetYaxis()->SetTitleOffset(1.55);
   mudxy_all->GetYaxis()->SetTitleFont(42);
   mudxy_all->GetZaxis()->SetLabelFont(42);
   mudxy_all->GetZaxis()->SetLabelOffset(0.007);
   mudxy_all->GetZaxis()->SetLabelSize(0.035);
   mudxy_all->GetZaxis()->SetTitleSize(0.045);
   mudxy_all->GetZaxis()->SetTickLength(0.02);
   mudxy_all->GetZaxis()->SetTitleFont(42);
   stack->Add(mudxy_all,"");
   stack->Draw("hist");
   
   TH1F *mudxy_all = new TH1F("mudxy_all","mudxy_all",100,-1,1);
   mudxy_all->SetBinContent(50,147);
   mudxy_all->SetBinContent(51,208);
   mudxy_all->SetBinError(50,12.12436);
   mudxy_all->SetBinError(51,14.42221);
   mudxy_all->SetEntries(355);
   mudxy_all->SetStats(0);
   mudxy_all->SetFillColor(1);
   mudxy_all->SetFillStyle(0);
   mudxy_all->SetLineWidth(3);
   mudxy_all->SetMarkerStyle(20);
   mudxy_all->SetMarkerSize(1.3);
   mudxy_all->GetXaxis()->SetLabelFont(42);
   mudxy_all->GetXaxis()->SetLabelOffset(0.007);
   mudxy_all->GetXaxis()->SetLabelSize(0.035);
   mudxy_all->GetXaxis()->SetTitleSize(0.045);
   mudxy_all->GetXaxis()->SetTickLength(0.02);
   mudxy_all->GetXaxis()->SetTitleOffset(0.9);
   mudxy_all->GetXaxis()->SetTitleFont(42);
   mudxy_all->GetYaxis()->SetLabelFont(42);
   mudxy_all->GetYaxis()->SetLabelOffset(0.007);
   mudxy_all->GetYaxis()->SetLabelSize(0.035);
   mudxy_all->GetYaxis()->SetTitleSize(0.045);
   mudxy_all->GetYaxis()->SetTickLength(0.02);
   mudxy_all->GetYaxis()->SetTitleOffset(1.55);
   mudxy_all->GetYaxis()->SetTitleFont(42);
   mudxy_all->GetZaxis()->SetLabelFont(42);
   mudxy_all->GetZaxis()->SetLabelOffset(0.007);
   mudxy_all->GetZaxis()->SetLabelSize(0.035);
   mudxy_all->GetZaxis()->SetTitleSize(0.045);
   mudxy_all->GetZaxis()->SetTickLength(0.02);
   mudxy_all->GetZaxis()->SetTitleFont(42);
   mudxy_all->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiQCD_CJVpass");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("mudxy_all","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("mudxy_all","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mudxy_all","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mudxy_all","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mudxy_all","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mudxy_all","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-1.405063,-0.653951,1.126582,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *mudxy_all = new TH1F("mudxy_all","mudxy_all",100,-1,1);
   mudxy_all->SetBinContent(50,0.6114125);
   mudxy_all->SetBinContent(51,0.8854632);
   mudxy_all->SetBinError(50,0.05768314);
   mudxy_all->SetBinError(51,0.07654817);
   mudxy_all->SetMinimum(0);
   mudxy_all->SetMaximum(2);
   mudxy_all->SetEntries(243.893);
   mudxy_all->SetStats(0);
   mudxy_all->SetFillStyle(0);
   mudxy_all->SetMarkerStyle(20);
   mudxy_all->SetMarkerSize(0.8);
   mudxy_all->GetXaxis()->SetTitle("Muon d_{xy}");
   mudxy_all->GetXaxis()->SetLabelFont(42);
   mudxy_all->GetXaxis()->SetLabelOffset(0.007);
   mudxy_all->GetXaxis()->SetLabelSize(0.1);
   mudxy_all->GetXaxis()->SetTitleSize(0.12);
   mudxy_all->GetXaxis()->SetTickLength(0.02);
   mudxy_all->GetXaxis()->SetTitleOffset(0.9);
   mudxy_all->GetXaxis()->SetTitleFont(42);
   mudxy_all->GetYaxis()->SetTitle("Data/MC");
   mudxy_all->GetYaxis()->SetNdivisions(505);
   mudxy_all->GetYaxis()->SetLabelFont(42);
   mudxy_all->GetYaxis()->SetLabelOffset(0.007);
   mudxy_all->GetYaxis()->SetLabelSize(0.1);
   mudxy_all->GetYaxis()->SetTitleSize(0.12);
   mudxy_all->GetYaxis()->SetTickLength(0.02);
   mudxy_all->GetYaxis()->SetTitleOffset(0.55);
   mudxy_all->GetYaxis()->SetTitleFont(42);
   mudxy_all->GetZaxis()->SetLabelFont(42);
   mudxy_all->GetZaxis()->SetLabelOffset(0.007);
   mudxy_all->GetZaxis()->SetLabelSize(0.035);
   mudxy_all->GetZaxis()->SetTitleSize(0.045);
   mudxy_all->GetZaxis()->SetTickLength(0.02);
   mudxy_all->GetZaxis()->SetTitleFont(42);
   mudxy_all->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
