{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:54:13 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-0.8101265,-196.1141,4.253165,9609.591);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMaximum(8685.053);
   
   TH1F *taggingJetsFlavour_stack_5 = new TH1F("taggingJetsFlavour_stack_5","stack",4,0,4);
   taggingJetsFlavour_stack_5->SetBinContent(1,194.5911);
   taggingJetsFlavour_stack_5->SetBinContent(3,0.7005188);
   taggingJetsFlavour_stack_5->SetBinError(1,16.72067);
   taggingJetsFlavour_stack_5->SetBinError(3,0.5725071);
   taggingJetsFlavour_stack_5->SetMinimum(0);
   taggingJetsFlavour_stack_5->SetMaximum(9119.305);
   taggingJetsFlavour_stack_5->SetEntries(812);
   taggingJetsFlavour_stack_5->SetStats(0);
   taggingJetsFlavour_stack_5->SetFillColor(4);
   taggingJetsFlavour_stack_5->SetLineColor(4);
   taggingJetsFlavour_stack_5->SetLineWidth(2);
   taggingJetsFlavour_stack_5->SetMarkerColor(4);
   taggingJetsFlavour_stack_5->SetMarkerStyle(21);
   taggingJetsFlavour_stack_5->SetMarkerSize(0.8);
   taggingJetsFlavour_stack_5->GetXaxis()->SetTitle("#tau as tagging jet");
   taggingJetsFlavour_stack_5->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour_stack_5->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour_stack_5->GetXaxis()->SetLabelSize(0);
   taggingJetsFlavour_stack_5->GetXaxis()->SetTitleSize(0);
   taggingJetsFlavour_stack_5->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour_stack_5->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour_stack_5->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour_stack_5->GetYaxis()->SetTitle("Events");
   taggingJetsFlavour_stack_5->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour_stack_5->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour_stack_5->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour_stack_5->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour_stack_5->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour_stack_5->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour_stack_5->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour_stack_5->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour_stack_5->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour_stack_5->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour_stack_5->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour_stack_5->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour_stack_5->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(taggingJetsFlavour_stack_5);
   
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,194.5911);
   taggingJetsFlavour->SetBinContent(3,0.7005188);
   taggingJetsFlavour->SetBinError(1,16.72067);
   taggingJetsFlavour->SetBinError(3,0.5725071);
   taggingJetsFlavour->SetMaximum(7251.53);
   taggingJetsFlavour->SetEntries(812);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(4);
   taggingJetsFlavour->SetLineColor(4);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(4);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetTitle("#tau as tagging jet");
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetTitle("Events");
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"HIST");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,772.5975);
   taggingJetsFlavour->SetBinContent(2,1.210812);
   taggingJetsFlavour->SetBinContent(3,0.867489);
   taggingJetsFlavour->SetBinError(1,20.62481);
   taggingJetsFlavour->SetBinError(2,1.056614);
   taggingJetsFlavour->SetBinError(3,0.7065865);
   taggingJetsFlavour->SetEntries(2229);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(5);
   taggingJetsFlavour->SetLineColor(5);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(5);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,4659.106);
   taggingJetsFlavour->SetBinContent(2,9.501887);
   taggingJetsFlavour->SetBinContent(3,6.901939);
   taggingJetsFlavour->SetBinError(1,54.19114);
   taggingJetsFlavour->SetBinError(2,3.195673);
   taggingJetsFlavour->SetBinError(3,1.788418);
   taggingJetsFlavour->SetEntries(12858);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(6);
   taggingJetsFlavour->SetLineColor(6);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(6);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,1136.809);
   taggingJetsFlavour->SetBinContent(2,1.167504);
   taggingJetsFlavour->SetBinContent(3,1.283707);
   taggingJetsFlavour->SetBinError(1,4.445058);
   taggingJetsFlavour->SetBinError(2,0.1392505);
   taggingJetsFlavour->SetBinError(3,0.1432823);
   taggingJetsFlavour->SetEntries(83601);
   taggingJetsFlavour->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   taggingJetsFlavour->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   taggingJetsFlavour->SetLineColor(ci);
   taggingJetsFlavour->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   taggingJetsFlavour->SetMarkerColor(ci);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,0.05156378);
   taggingJetsFlavour->SetBinError(1,0.05156378);
   taggingJetsFlavour->SetEntries(1);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(3);
   taggingJetsFlavour->SetLineColor(3);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(3);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,334.6755);
   taggingJetsFlavour->SetBinContent(3,0.3872895);
   taggingJetsFlavour->SetBinError(1,5.722617);
   taggingJetsFlavour->SetBinError(3,0.1541596);
   taggingJetsFlavour->SetEntries(5525);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(3);
   taggingJetsFlavour->SetLineColor(3);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(3);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,79.89825);
   taggingJetsFlavour->SetBinContent(2,0.1137225);
   taggingJetsFlavour->SetBinContent(3,0.1510944);
   taggingJetsFlavour->SetBinError(1,0.8100053);
   taggingJetsFlavour->SetBinError(2,0.0291294);
   taggingJetsFlavour->SetBinError(3,0.03521574);
   taggingJetsFlavour->SetEntries(14070);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(3);
   taggingJetsFlavour->SetLineColor(3);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(3);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   stack->Draw("hist");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,5993);
   taggingJetsFlavour->SetBinContent(2,9);
   taggingJetsFlavour->SetBinContent(3,5);
   taggingJetsFlavour->SetBinError(1,77.41447);
   taggingJetsFlavour->SetBinError(2,3);
   taggingJetsFlavour->SetBinError(3,2.236068);
   taggingJetsFlavour->SetEntries(6007);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(1);
   taggingJetsFlavour->SetFillStyle(0);
   taggingJetsFlavour->SetLineWidth(3);
   taggingJetsFlavour->SetMarkerStyle(20);
   taggingJetsFlavour->SetMarkerSize(1.3);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   taggingJetsFlavour->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DEta");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("taggingJetsFlavour","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("taggingJetsFlavour","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-0.8101265,-0.653951,4.253165,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,0.8582101);
   taggingJetsFlavour->SetBinContent(2,0.7503797);
   taggingJetsFlavour->SetBinContent(3,0.5212939);
   taggingJetsFlavour->SetBinError(1,0.0132091);
   taggingJetsFlavour->SetBinError(2,0.3270859);
   taggingJetsFlavour->SetBinError(3,0.2557469);
   taggingJetsFlavour->SetMinimum(0);
   taggingJetsFlavour->SetMaximum(2);
   taggingJetsFlavour->SetEntries(26.28792);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillStyle(0);
   taggingJetsFlavour->SetMarkerStyle(20);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetTitle("#tau as tagging jet");
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.1);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.12);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetTitle("Data/MC");
   taggingJetsFlavour->GetYaxis()->SetNdivisions(505);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.1);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.12);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(0.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   taggingJetsFlavour->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
