{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:56:07 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-85.06329,-0.02150538,446.5823,1.053763);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(0);
   
   TH1F *mt_enu_stack_10 = new TH1F("mt_enu_stack_10","stack",25,0,500);
   mt_enu_stack_10->SetBinContent(0,5.277979);
   mt_enu_stack_10->SetBinError(0,3.039767);
   mt_enu_stack_10->SetMinimum(-0);
   mt_enu_stack_10->SetMaximum(nan);
   mt_enu_stack_10->SetEntries(14);
   mt_enu_stack_10->SetStats(0);
   mt_enu_stack_10->SetFillColor(4);
   mt_enu_stack_10->SetLineColor(4);
   mt_enu_stack_10->SetLineWidth(2);
   mt_enu_stack_10->SetMarkerColor(4);
   mt_enu_stack_10->SetMarkerStyle(21);
   mt_enu_stack_10->SetMarkerSize(0.8);
   mt_enu_stack_10->GetXaxis()->SetTitle("m_{T}(e#nu) (GeV)");
   mt_enu_stack_10->GetXaxis()->SetRange(1,21);
   mt_enu_stack_10->GetXaxis()->SetLabelFont(42);
   mt_enu_stack_10->GetXaxis()->SetLabelOffset(0.007);
   mt_enu_stack_10->GetXaxis()->SetLabelSize(0);
   mt_enu_stack_10->GetXaxis()->SetTitleSize(0);
   mt_enu_stack_10->GetXaxis()->SetTickLength(0.02);
   mt_enu_stack_10->GetXaxis()->SetTitleOffset(0.9);
   mt_enu_stack_10->GetXaxis()->SetTitleFont(42);
   mt_enu_stack_10->GetYaxis()->SetTitle("Events");
   mt_enu_stack_10->GetYaxis()->SetLabelFont(42);
   mt_enu_stack_10->GetYaxis()->SetLabelOffset(0.007);
   mt_enu_stack_10->GetYaxis()->SetLabelSize(0.035);
   mt_enu_stack_10->GetYaxis()->SetTitleSize(0.045);
   mt_enu_stack_10->GetYaxis()->SetTickLength(0.02);
   mt_enu_stack_10->GetYaxis()->SetTitleOffset(1.55);
   mt_enu_stack_10->GetYaxis()->SetTitleFont(42);
   mt_enu_stack_10->GetZaxis()->SetLabelFont(42);
   mt_enu_stack_10->GetZaxis()->SetLabelOffset(0.007);
   mt_enu_stack_10->GetZaxis()->SetLabelSize(0.035);
   mt_enu_stack_10->GetZaxis()->SetTitleSize(0.045);
   mt_enu_stack_10->GetZaxis()->SetTickLength(0.02);
   mt_enu_stack_10->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(mt_enu_stack_10);
   
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,5.277979);
   mt_enu->SetBinError(0,3.039767);
   mt_enu->SetMinimum(0.01);
   mt_enu->SetMaximum(0);
   mt_enu->SetEntries(14);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(4);
   mt_enu->SetLineColor(4);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(4);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetTitle("m_{T}(e#nu) (GeV)");
   mt_enu->GetXaxis()->SetRange(1,21);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0);
   mt_enu->GetXaxis()->SetTitleSize(0);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetTitle("Events");
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"HIST");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,25.607);
   mt_enu->SetBinError(0,4.144481);
   mt_enu->SetEntries(47);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(5);
   mt_enu->SetLineColor(5);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(5);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,79.61528);
   mt_enu->SetBinError(0,7.319564);
   mt_enu->SetEntries(161);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(6);
   mt_enu->SetLineColor(6);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(6);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,34.00943);
   mt_enu->SetBinError(0,0.8335851);
   mt_enu->SetEntries(1917);
   mt_enu->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   mt_enu->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   mt_enu->SetLineColor(ci);
   mt_enu->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   mt_enu->SetMarkerColor(ci);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,2.166359);
   mt_enu->SetBinError(0,0.5546873);
   mt_enu->SetEntries(18);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(3);
   mt_enu->SetLineColor(3);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(3);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,4.682396);
   mt_enu->SetBinError(0,0.7397661);
   mt_enu->SetEntries(51);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(3);
   mt_enu->SetLineColor(3);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(3);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,1.3684);
   mt_enu->SetBinError(0,0.0968774);
   mt_enu->SetEntries(237);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(3);
   mt_enu->SetLineColor(3);
   mt_enu->SetLineWidth(2);
   mt_enu->SetMarkerColor(3);
   mt_enu->SetMarkerStyle(21);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_enu,"");
   stack->Draw("hist");
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,140);
   mt_enu->SetBinError(0,11.83216);
   mt_enu->SetEntries(140);
   mt_enu->SetStats(0);
   mt_enu->SetFillColor(1);
   mt_enu->SetFillStyle(0);
   mt_enu->SetLineWidth(3);
   mt_enu->SetMarkerStyle(20);
   mt_enu->SetMarkerSize(1.3);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.035);
   mt_enu->GetXaxis()->SetTitleSize(0.045);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.035);
   mt_enu->GetYaxis()->SetTitleSize(0.045);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(1.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   mt_enu->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"CJVfail");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("mt_enu","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("mt_enu","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_enu","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_enu","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_enu","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_enu","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-85.06329,-0.653951,446.5823,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *mt_enu = new TH1F("mt_enu","mt_enu",25,0,500);
   mt_enu->SetBinContent(0,0.9494818);
   mt_enu->SetBinError(0,0.09714871);
   mt_enu->SetMinimum(0);
   mt_enu->SetMaximum(2);
   mt_enu->SetStats(0);
   mt_enu->SetFillStyle(0);
   mt_enu->SetMarkerStyle(20);
   mt_enu->SetMarkerSize(0.8);
   mt_enu->GetXaxis()->SetTitle("m_{T}(e#nu) (GeV)");
   mt_enu->GetXaxis()->SetRange(1,21);
   mt_enu->GetXaxis()->SetLabelFont(42);
   mt_enu->GetXaxis()->SetLabelOffset(0.007);
   mt_enu->GetXaxis()->SetLabelSize(0.1);
   mt_enu->GetXaxis()->SetTitleSize(0.12);
   mt_enu->GetXaxis()->SetTickLength(0.02);
   mt_enu->GetXaxis()->SetTitleOffset(0.9);
   mt_enu->GetXaxis()->SetTitleFont(42);
   mt_enu->GetYaxis()->SetTitle("Data/MC");
   mt_enu->GetYaxis()->SetNdivisions(505);
   mt_enu->GetYaxis()->SetLabelFont(42);
   mt_enu->GetYaxis()->SetLabelOffset(0.007);
   mt_enu->GetYaxis()->SetLabelSize(0.1);
   mt_enu->GetYaxis()->SetTitleSize(0.12);
   mt_enu->GetYaxis()->SetTickLength(0.02);
   mt_enu->GetYaxis()->SetTitleOffset(0.55);
   mt_enu->GetYaxis()->SetTitleFont(42);
   mt_enu->GetZaxis()->SetLabelFont(42);
   mt_enu->GetZaxis()->SetLabelOffset(0.007);
   mt_enu->GetZaxis()->SetLabelSize(0.035);
   mt_enu->GetZaxis()->SetTitleSize(0.045);
   mt_enu->GetZaxis()->SetTickLength(0.02);
   mt_enu->GetZaxis()->SetTitleFont(42);
   mt_enu->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
