{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:56:01 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-85.06329,-2.748953,446.5823,4.681234);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(9301.341);
   
   TH1F *mt_munu_stack_2 = new TH1F("mt_munu_stack_2","stack",25,0,500);
   mt_munu_stack_2->SetBinContent(0,72.13567);
   mt_munu_stack_2->SetBinError(0,7.421538);
   mt_munu_stack_2->SetMinimum(0.002509868);
   mt_munu_stack_2->SetMaximum(20404.44);
   mt_munu_stack_2->SetEntries(1588);
   mt_munu_stack_2->SetStats(0);
   mt_munu_stack_2->SetFillColor(4);
   mt_munu_stack_2->SetLineColor(4);
   mt_munu_stack_2->SetLineWidth(2);
   mt_munu_stack_2->SetMarkerColor(4);
   mt_munu_stack_2->SetMarkerStyle(21);
   mt_munu_stack_2->SetMarkerSize(0.8);
   mt_munu_stack_2->GetXaxis()->SetTitle("m_{T}(#mu#nu) (GeV)");
   mt_munu_stack_2->GetXaxis()->SetRange(1,21);
   mt_munu_stack_2->GetXaxis()->SetLabelFont(42);
   mt_munu_stack_2->GetXaxis()->SetLabelOffset(0.007);
   mt_munu_stack_2->GetXaxis()->SetLabelSize(0);
   mt_munu_stack_2->GetXaxis()->SetTitleSize(0);
   mt_munu_stack_2->GetXaxis()->SetTickLength(0.02);
   mt_munu_stack_2->GetXaxis()->SetTitleOffset(0.9);
   mt_munu_stack_2->GetXaxis()->SetTitleFont(42);
   mt_munu_stack_2->GetYaxis()->SetTitle("Events");
   mt_munu_stack_2->GetYaxis()->SetLabelFont(42);
   mt_munu_stack_2->GetYaxis()->SetLabelOffset(0.007);
   mt_munu_stack_2->GetYaxis()->SetLabelSize(0.035);
   mt_munu_stack_2->GetYaxis()->SetTitleSize(0.045);
   mt_munu_stack_2->GetYaxis()->SetTickLength(0.02);
   mt_munu_stack_2->GetYaxis()->SetTitleOffset(1.55);
   mt_munu_stack_2->GetYaxis()->SetTitleFont(42);
   mt_munu_stack_2->GetZaxis()->SetLabelFont(42);
   mt_munu_stack_2->GetZaxis()->SetLabelOffset(0.007);
   mt_munu_stack_2->GetZaxis()->SetLabelSize(0.035);
   mt_munu_stack_2->GetZaxis()->SetTitleSize(0.045);
   mt_munu_stack_2->GetZaxis()->SetTickLength(0.02);
   mt_munu_stack_2->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(mt_munu_stack_2);
   
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,72.13567);
   mt_munu->SetBinError(0,7.421538);
   mt_munu->SetMinimum(0.01);
   mt_munu->SetMaximum(9301.341);
   mt_munu->SetEntries(1588);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(4);
   mt_munu->SetLineColor(4);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(4);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetTitle("m_{T}(#mu#nu) (GeV)");
   mt_munu->GetXaxis()->SetRange(1,21);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0);
   mt_munu->GetXaxis()->SetTitleSize(0);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetTitle("Events");
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"HIST");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,476.4586);
   mt_munu->SetBinError(0,12.67543);
   mt_munu->SetEntries(2945);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(5);
   mt_munu->SetLineColor(5);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(5);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,1717.201);
   mt_munu->SetBinError(0,32.71397);
   mt_munu->SetEntries(10124);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(6);
   mt_munu->SetLineColor(6);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(6);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,208.2005);
   mt_munu->SetBinError(0,1.741251);
   mt_munu->SetEntries(22233);
   mt_munu->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   mt_munu->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   mt_munu->SetLineColor(ci);
   mt_munu->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   mt_munu->SetMarkerColor(ci);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,61.64389);
   mt_munu->SetBinError(0,3.300468);
   mt_munu->SetEntries(1140);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(3);
   mt_munu->SetLineColor(3);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(3);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,141.999);
   mt_munu->SetBinError(0,3.630653);
   mt_munu->SetEntries(4888);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(3);
   mt_munu->SetLineColor(3);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(3);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,11.84899);
   mt_munu->SetBinContent(1,0.6200894);
   mt_munu->SetBinContent(2,0.4228187);
   mt_munu->SetBinContent(3,0.1900256);
   mt_munu->SetBinContent(4,0.0533557);
   mt_munu->SetBinContent(5,0.01111889);
   mt_munu->SetBinContent(6,0.006260193);
   mt_munu->SetBinContent(7,0.005568065);
   mt_munu->SetBinError(0,0.2247554);
   mt_munu->SetBinError(1,0.075195);
   mt_munu->SetBinError(2,0.0617969);
   mt_munu->SetBinError(3,0.041108);
   mt_munu->SetBinError(4,0.02020372);
   mt_munu->SetBinError(5,0.00786253);
   mt_munu->SetBinError(6,0.006260194);
   mt_munu->SetBinError(7,0.005568065);
   mt_munu->SetEntries(4561);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(3);
   mt_munu->SetLineColor(3);
   mt_munu->SetLineWidth(2);
   mt_munu->SetMarkerColor(3);
   mt_munu->SetMarkerStyle(21);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   stack->Add(mt_munu,"");
   stack->Draw("hist");
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,12222);
   mt_munu->SetBinError(0,110.5532);
   mt_munu->SetEntries(12222);
   mt_munu->SetStats(0);
   mt_munu->SetFillColor(1);
   mt_munu->SetFillStyle(0);
   mt_munu->SetLineWidth(3);
   mt_munu->SetMarkerStyle(20);
   mt_munu->SetMarkerSize(1.3);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.035);
   mt_munu->GetXaxis()->SetTitleSize(0.045);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.035);
   mt_munu->GetYaxis()->SetTitleSize(0.045);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(1.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   mt_munu->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"WSelection");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("mt_munu","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("mt_munu","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_munu","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_munu","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_munu","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mt_munu","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-85.06329,-0.653951,446.5823,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *mt_munu = new TH1F("mt_munu","mt_munu",25,0,500);
   mt_munu->SetBinContent(0,4.669605);
   mt_munu->SetBinError(0,0.07608147);
   mt_munu->SetMinimum(0);
   mt_munu->SetMaximum(2);
   mt_munu->SetStats(0);
   mt_munu->SetFillStyle(0);
   mt_munu->SetMarkerStyle(20);
   mt_munu->SetMarkerSize(0.8);
   mt_munu->GetXaxis()->SetTitle("m_{T}(#mu#nu) (GeV)");
   mt_munu->GetXaxis()->SetRange(1,21);
   mt_munu->GetXaxis()->SetLabelFont(42);
   mt_munu->GetXaxis()->SetLabelOffset(0.007);
   mt_munu->GetXaxis()->SetLabelSize(0.1);
   mt_munu->GetXaxis()->SetTitleSize(0.12);
   mt_munu->GetXaxis()->SetTickLength(0.02);
   mt_munu->GetXaxis()->SetTitleOffset(0.9);
   mt_munu->GetXaxis()->SetTitleFont(42);
   mt_munu->GetYaxis()->SetTitle("Data/MC");
   mt_munu->GetYaxis()->SetNdivisions(505);
   mt_munu->GetYaxis()->SetLabelFont(42);
   mt_munu->GetYaxis()->SetLabelOffset(0.007);
   mt_munu->GetYaxis()->SetLabelSize(0.1);
   mt_munu->GetYaxis()->SetTitleSize(0.12);
   mt_munu->GetYaxis()->SetTickLength(0.02);
   mt_munu->GetYaxis()->SetTitleOffset(0.55);
   mt_munu->GetYaxis()->SetTitleFont(42);
   mt_munu->GetZaxis()->SetLabelFont(42);
   mt_munu->GetZaxis()->SetLabelOffset(0.007);
   mt_munu->GetZaxis()->SetLabelSize(0.035);
   mt_munu->GetZaxis()->SetTitleSize(0.045);
   mt_munu->GetZaxis()->SetTickLength(0.02);
   mt_munu->GetZaxis()->SetTitleFont(42);
   mt_munu->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
