{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:56:23 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-4.316456,-2.613459,3.911392,2.915656);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(232.589);
   
   TH1F *mueta_1_stack_11 = new TH1F("mueta_1_stack_11","stack",20,-5,5);
   mueta_1_stack_11->SetBinContent(0,2.600504);
   mueta_1_stack_11->SetBinError(0,2.254928);
   mueta_1_stack_11->SetMinimum(0.003141399);
   mueta_1_stack_11->SetMaximum(435.7131);
   mueta_1_stack_11->SetEntries(5);
   mueta_1_stack_11->SetStats(0);
   mueta_1_stack_11->SetFillColor(4);
   mueta_1_stack_11->SetLineColor(4);
   mueta_1_stack_11->SetLineWidth(2);
   mueta_1_stack_11->SetMarkerColor(4);
   mueta_1_stack_11->SetMarkerStyle(21);
   mueta_1_stack_11->SetMarkerSize(0.8);
   mueta_1_stack_11->GetXaxis()->SetTitle("Leading muon #eta");
   mueta_1_stack_11->GetXaxis()->SetRange(5,17);
   mueta_1_stack_11->GetXaxis()->SetLabelFont(42);
   mueta_1_stack_11->GetXaxis()->SetLabelOffset(0.007);
   mueta_1_stack_11->GetXaxis()->SetLabelSize(0);
   mueta_1_stack_11->GetXaxis()->SetTitleSize(0);
   mueta_1_stack_11->GetXaxis()->SetTickLength(0.02);
   mueta_1_stack_11->GetXaxis()->SetTitleOffset(0.9);
   mueta_1_stack_11->GetXaxis()->SetTitleFont(42);
   mueta_1_stack_11->GetYaxis()->SetTitle("Events");
   mueta_1_stack_11->GetYaxis()->SetLabelFont(42);
   mueta_1_stack_11->GetYaxis()->SetLabelOffset(0.007);
   mueta_1_stack_11->GetYaxis()->SetLabelSize(0.035);
   mueta_1_stack_11->GetYaxis()->SetTitleSize(0.045);
   mueta_1_stack_11->GetYaxis()->SetTickLength(0.02);
   mueta_1_stack_11->GetYaxis()->SetTitleOffset(1.55);
   mueta_1_stack_11->GetYaxis()->SetTitleFont(42);
   mueta_1_stack_11->GetZaxis()->SetLabelFont(42);
   mueta_1_stack_11->GetZaxis()->SetLabelOffset(0.007);
   mueta_1_stack_11->GetZaxis()->SetLabelSize(0.035);
   mueta_1_stack_11->GetZaxis()->SetTitleSize(0.045);
   mueta_1_stack_11->GetZaxis()->SetTickLength(0.02);
   mueta_1_stack_11->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(mueta_1_stack_11);
   
   
   TH1F *mueta_1 = new TH1F("mueta_1","mueta_1",20,-5,5);
   mueta_1->SetBinContent(0,2.600504);
   mueta_1->SetBinError(0,2.254928);
   mueta_1->SetMinimum(0.01);
   mueta_1->SetMaximum(232.589);
   mueta_1->SetEntries(5);
   mueta_1->SetStats(0);
   mueta_1->SetFillColor(4);
   mueta_1->SetLineColor(4);
   mueta_1->SetLineWidth(2);
   mueta_1->SetMarkerColor(4);
   mueta_1->SetMarkerStyle(21);
   mueta_1->SetMarkerSize(0.8);
   mueta_1->GetXaxis()->SetTitle("Leading muon #eta");
   mueta_1->GetXaxis()->SetRange(5,17);
   mueta_1->GetXaxis()->SetLabelFont(42);
   mueta_1->GetXaxis()->SetLabelOffset(0.007);
   mueta_1->GetXaxis()->SetLabelSize(0);
   mueta_1->GetXaxis()->SetTitleSize(0);
   mueta_1->GetXaxis()->SetTickLength(0.02);
   mueta_1->GetXaxis()->SetTitleOffset(0.9);
   mueta_1->GetXaxis()->SetTitleFont(42);
   mueta_1->GetYaxis()->SetTitle("Events");
   mueta_1->GetYaxis()->SetLabelFont(42);
   mueta_1->GetYaxis()->SetLabelOffset(0.007);
   mueta_1->GetYaxis()->SetLabelSize(0.035);
   mueta_1->GetYaxis()->SetTitleSize(0.045);
   mueta_1->GetYaxis()->SetTickLength(0.02);
   mueta_1->GetYaxis()->SetTitleOffset(1.55);
   mueta_1->GetYaxis()->SetTitleFont(42);
   mueta_1->GetZaxis()->SetLabelFont(42);
   mueta_1->GetZaxis()->SetLabelOffset(0.007);
   mueta_1->GetZaxis()->SetLabelSize(0.035);
   mueta_1->GetZaxis()->SetTitleSize(0.045);
   mueta_1->GetZaxis()->SetTickLength(0.02);
   mueta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(mueta_1,"HIST");
   
   TH1F *mueta_1 = new TH1F("mueta_1","mueta_1",20,-5,5);
   mueta_1->SetBinContent(0,9.551828);
   mueta_1->SetBinError(0,2.322635);
   mueta_1->SetEntries(22);
   mueta_1->SetStats(0);
   mueta_1->SetFillColor(5);
   mueta_1->SetLineColor(5);
   mueta_1->SetLineWidth(2);
   mueta_1->SetMarkerColor(5);
   mueta_1->SetMarkerStyle(21);
   mueta_1->SetMarkerSize(0.8);
   mueta_1->GetXaxis()->SetLabelFont(42);
   mueta_1->GetXaxis()->SetLabelOffset(0.007);
   mueta_1->GetXaxis()->SetLabelSize(0.035);
   mueta_1->GetXaxis()->SetTitleSize(0.045);
   mueta_1->GetXaxis()->SetTickLength(0.02);
   mueta_1->GetXaxis()->SetTitleOffset(0.9);
   mueta_1->GetXaxis()->SetTitleFont(42);
   mueta_1->GetYaxis()->SetLabelFont(42);
   mueta_1->GetYaxis()->SetLabelOffset(0.007);
   mueta_1->GetYaxis()->SetLabelSize(0.035);
   mueta_1->GetYaxis()->SetTitleSize(0.045);
   mueta_1->GetYaxis()->SetTickLength(0.02);
   mueta_1->GetYaxis()->SetTitleOffset(1.55);
   mueta_1->GetYaxis()->SetTitleFont(42);
   mueta_1->GetZaxis()->SetLabelFont(42);
   mueta_1->GetZaxis()->SetLabelOffset(0.007);
   mueta_1->GetZaxis()->SetLabelSize(0.035);
   mueta_1->GetZaxis()->SetTitleSize(0.045);
   mueta_1->GetZaxis()->SetTickLength(0.02);
   mueta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(mueta_1,"");
   
   TH1F *mueta_1 = new TH1F("mueta_1","mueta_1",20,-5,5);
   mueta_1->SetBinContent(0,18.0032);
   mueta_1->SetBinError(0,3.374263);
   mueta_1->SetEntries(37);
   mueta_1->SetStats(0);
   mueta_1->SetFillColor(6);
   mueta_1->SetLineColor(6);
   mueta_1->SetLineWidth(2);
   mueta_1->SetMarkerColor(6);
   mueta_1->SetMarkerStyle(21);
   mueta_1->SetMarkerSize(0.8);
   mueta_1->GetXaxis()->SetLabelFont(42);
   mueta_1->GetXaxis()->SetLabelOffset(0.007);
   mueta_1->GetXaxis()->SetLabelSize(0.035);
   mueta_1->GetXaxis()->SetTitleSize(0.045);
   mueta_1->GetXaxis()->SetTickLength(0.02);
   mueta_1->GetXaxis()->SetTitleOffset(0.9);
   mueta_1->GetXaxis()->SetTitleFont(42);
   mueta_1->GetYaxis()->SetLabelFont(42);
   mueta_1->GetYaxis()->SetLabelOffset(0.007);
   mueta_1->GetYaxis()->SetLabelSize(0.035);
   mueta_1->GetYaxis()->SetTitleSize(0.045);
   mueta_1->GetYaxis()->SetTickLength(0.02);
   mueta_1->GetYaxis()->SetTitleOffset(1.55);
   mueta_1->GetYaxis()->SetTitleFont(42);
   mueta_1->GetZaxis()->SetLabelFont(42);
   mueta_1->GetZaxis()->SetLabelOffset(0.007);
   mueta_1->GetZaxis()->SetLabelSize(0.035);
   mueta_1->GetZaxis()->SetTitleSize(0.045);
   mueta_1->GetZaxis()->SetTickLength(0.02);
   mueta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(mueta_1,"");
   
   TH1F *mueta_1 = new TH1F("mueta_1","mueta_1",20,-5,5);
   mueta_1->SetBinContent(0,8.020505);
   mueta_1->SetBinError(0,0.4105582);
   mueta_1->SetEntries(441);
   mueta_1->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   mueta_1->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   mueta_1->SetLineColor(ci);
   mueta_1->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   mueta_1->SetMarkerColor(ci);
   mueta_1->SetMarkerStyle(21);
   mueta_1->SetMarkerSize(0.8);
   mueta_1->GetXaxis()->SetLabelFont(42);
   mueta_1->GetXaxis()->SetLabelOffset(0.007);
   mueta_1->GetXaxis()->SetLabelSize(0.035);
   mueta_1->GetXaxis()->SetTitleSize(0.045);
   mueta_1->GetXaxis()->SetTickLength(0.02);
   mueta_1->GetXaxis()->SetTitleOffset(0.9);
   mueta_1->GetXaxis()->SetTitleFont(42);
   mueta_1->GetYaxis()->SetLabelFont(42);
   mueta_1->GetYaxis()->SetLabelOffset(0.007);
   mueta_1->GetYaxis()->SetLabelSize(0.035);
   mueta_1->GetYaxis()->SetTitleSize(0.045);
   mueta_1->GetYaxis()->SetTickLength(0.02);
   mueta_1->GetYaxis()->SetTitleOffset(1.55);
   mueta_1->GetYaxis()->SetTitleFont(42);
   mueta_1->GetZaxis()->SetLabelFont(42);
   mueta_1->GetZaxis()->SetLabelOffset(0.007);
   mueta_1->GetZaxis()->SetLabelSize(0.035);
   mueta_1->GetZaxis()->SetTitleSize(0.045);
   mueta_1->GetZaxis()->SetTickLength(0.02);
   mueta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(mueta_1,"");
   
   TH1F *mueta_1 = new TH1F("mueta_1","mueta_1",20,-5,5);
   mueta_1->SetBinContent(0,0.6906731);
   mueta_1->SetBinError(0,0.3271085);
   mueta_1->SetEntries(6);
   mueta_1->SetStats(0);
   mueta_1->SetFillColor(3);
   mueta_1->SetLineColor(3);
   mueta_1->SetLineWidth(2);
   mueta_1->SetMarkerColor(3);
   mueta_1->SetMarkerStyle(21);
   mueta_1->SetMarkerSize(0.8);
   mueta_1->GetXaxis()->SetLabelFont(42);
   mueta_1->GetXaxis()->SetLabelOffset(0.007);
   mueta_1->GetXaxis()->SetLabelSize(0.035);
   mueta_1->GetXaxis()->SetTitleSize(0.045);
   mueta_1->GetXaxis()->SetTickLength(0.02);
   mueta_1->GetXaxis()->SetTitleOffset(0.9);
   mueta_1->GetXaxis()->SetTitleFont(42);
   mueta_1->GetYaxis()->SetLabelFont(42);
   mueta_1->GetYaxis()->SetLabelOffset(0.007);
   mueta_1->GetYaxis()->SetLabelSize(0.035);
   mueta_1->GetYaxis()->SetTitleSize(0.045);
   mueta_1->GetYaxis()->SetTickLength(0.02);
   mueta_1->GetYaxis()->SetTitleOffset(1.55);
   mueta_1->GetYaxis()->SetTitleFont(42);
   mueta_1->GetZaxis()->SetLabelFont(42);
   mueta_1->GetZaxis()->SetLabelOffset(0.007);
   mueta_1->GetZaxis()->SetLabelSize(0.035);
   mueta_1->GetZaxis()->SetTitleSize(0.045);
   mueta_1->GetZaxis()->SetTickLength(0.02);
   mueta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(mueta_1,"");
   
   TH1F *mueta_1 = new TH1F("mueta_1","mueta_1",20,-5,5);
   mueta_1->SetBinContent(0,0.5484747);
   mueta_1->SetBinError(0,0.2284437);
   mueta_1->SetEntries(7);
   mueta_1->SetStats(0);
   mueta_1->SetFillColor(3);
   mueta_1->SetLineColor(3);
   mueta_1->SetLineWidth(2);
   mueta_1->SetMarkerColor(3);
   mueta_1->SetMarkerStyle(21);
   mueta_1->SetMarkerSize(0.8);
   mueta_1->GetXaxis()->SetLabelFont(42);
   mueta_1->GetXaxis()->SetLabelOffset(0.007);
   mueta_1->GetXaxis()->SetLabelSize(0.035);
   mueta_1->GetXaxis()->SetTitleSize(0.045);
   mueta_1->GetXaxis()->SetTickLength(0.02);
   mueta_1->GetXaxis()->SetTitleOffset(0.9);
   mueta_1->GetXaxis()->SetTitleFont(42);
   mueta_1->GetYaxis()->SetLabelFont(42);
   mueta_1->GetYaxis()->SetLabelOffset(0.007);
   mueta_1->GetYaxis()->SetLabelSize(0.035);
   mueta_1->GetYaxis()->SetTitleSize(0.045);
   mueta_1->GetYaxis()->SetTickLength(0.02);
   mueta_1->GetYaxis()->SetTitleOffset(1.55);
   mueta_1->GetYaxis()->SetTitleFont(42);
   mueta_1->GetZaxis()->SetLabelFont(42);
   mueta_1->GetZaxis()->SetLabelOffset(0.007);
   mueta_1->GetZaxis()->SetLabelSize(0.035);
   mueta_1->GetZaxis()->SetTitleSize(0.045);
   mueta_1->GetZaxis()->SetTickLength(0.02);
   mueta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(mueta_1,"");
   
   TH1F *mueta_1 = new TH1F("mueta_1","mueta_1",20,-5,5);
   mueta_1->SetBinContent(0,0.2672483);
   mueta_1->SetBinContent(12,0.01550593);
   mueta_1->SetBinError(0,0.04108216);
   mueta_1->SetBinError(12,0.01191655);
   mueta_1->SetEntries(53);
   mueta_1->SetStats(0);
   mueta_1->SetFillColor(3);
   mueta_1->SetLineColor(3);
   mueta_1->SetLineWidth(2);
   mueta_1->SetMarkerColor(3);
   mueta_1->SetMarkerStyle(21);
   mueta_1->SetMarkerSize(0.8);
   mueta_1->GetXaxis()->SetLabelFont(42);
   mueta_1->GetXaxis()->SetLabelOffset(0.007);
   mueta_1->GetXaxis()->SetLabelSize(0.035);
   mueta_1->GetXaxis()->SetTitleSize(0.045);
   mueta_1->GetXaxis()->SetTickLength(0.02);
   mueta_1->GetXaxis()->SetTitleOffset(0.9);
   mueta_1->GetXaxis()->SetTitleFont(42);
   mueta_1->GetYaxis()->SetLabelFont(42);
   mueta_1->GetYaxis()->SetLabelOffset(0.007);
   mueta_1->GetYaxis()->SetLabelSize(0.035);
   mueta_1->GetYaxis()->SetTitleSize(0.045);
   mueta_1->GetYaxis()->SetTickLength(0.02);
   mueta_1->GetYaxis()->SetTitleOffset(1.55);
   mueta_1->GetYaxis()->SetTitleFont(42);
   mueta_1->GetZaxis()->SetLabelFont(42);
   mueta_1->GetZaxis()->SetLabelOffset(0.007);
   mueta_1->GetZaxis()->SetLabelSize(0.035);
   mueta_1->GetZaxis()->SetTitleSize(0.045);
   mueta_1->GetZaxis()->SetTickLength(0.02);
   mueta_1->GetZaxis()->SetTitleFont(42);
   stack->Add(mueta_1,"");
   stack->Draw("hist");
   
   TH1F *mueta_1 = new TH1F("mueta_1","mueta_1",20,-5,5);
   mueta_1->SetBinContent(0,26);
   mueta_1->SetBinError(0,5.09902);
   mueta_1->SetEntries(26);
   mueta_1->SetStats(0);
   mueta_1->SetFillColor(1);
   mueta_1->SetFillStyle(0);
   mueta_1->SetLineWidth(3);
   mueta_1->SetMarkerStyle(20);
   mueta_1->SetMarkerSize(1.3);
   mueta_1->GetXaxis()->SetLabelFont(42);
   mueta_1->GetXaxis()->SetLabelOffset(0.007);
   mueta_1->GetXaxis()->SetLabelSize(0.035);
   mueta_1->GetXaxis()->SetTitleSize(0.045);
   mueta_1->GetXaxis()->SetTickLength(0.02);
   mueta_1->GetXaxis()->SetTitleOffset(0.9);
   mueta_1->GetXaxis()->SetTitleFont(42);
   mueta_1->GetYaxis()->SetLabelFont(42);
   mueta_1->GetYaxis()->SetLabelOffset(0.007);
   mueta_1->GetYaxis()->SetLabelSize(0.035);
   mueta_1->GetYaxis()->SetTitleSize(0.045);
   mueta_1->GetYaxis()->SetTickLength(0.02);
   mueta_1->GetYaxis()->SetTitleOffset(1.55);
   mueta_1->GetYaxis()->SetTitleFont(42);
   mueta_1->GetZaxis()->SetLabelFont(42);
   mueta_1->GetZaxis()->SetLabelOffset(0.007);
   mueta_1->GetZaxis()->SetLabelSize(0.035);
   mueta_1->GetZaxis()->SetTitleSize(0.045);
   mueta_1->GetZaxis()->SetTickLength(0.02);
   mueta_1->GetZaxis()->SetTitleFont(42);
   mueta_1->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiSIGNAL_CJVfail");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("mueta_1","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("mueta_1","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mueta_1","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mueta_1","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mueta_1","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mueta_1","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-4.316456,-0.653951,3.911392,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *mueta_1 = new TH1F("mueta_1","mueta_1",20,-5,5);
   mueta_1->SetBinContent(0,0.70115);
   mueta_1->SetBinError(0,0.1581934);
   mueta_1->SetMinimum(0);
   mueta_1->SetMaximum(2);
   mueta_1->SetStats(0);
   mueta_1->SetFillStyle(0);
   mueta_1->SetMarkerStyle(20);
   mueta_1->SetMarkerSize(0.8);
   mueta_1->GetXaxis()->SetTitle("Leading muon #eta");
   mueta_1->GetXaxis()->SetRange(5,17);
   mueta_1->GetXaxis()->SetLabelFont(42);
   mueta_1->GetXaxis()->SetLabelOffset(0.007);
   mueta_1->GetXaxis()->SetLabelSize(0.1);
   mueta_1->GetXaxis()->SetTitleSize(0.12);
   mueta_1->GetXaxis()->SetTickLength(0.02);
   mueta_1->GetXaxis()->SetTitleOffset(0.9);
   mueta_1->GetXaxis()->SetTitleFont(42);
   mueta_1->GetYaxis()->SetTitle("Data/MC");
   mueta_1->GetYaxis()->SetNdivisions(505);
   mueta_1->GetYaxis()->SetLabelFont(42);
   mueta_1->GetYaxis()->SetLabelOffset(0.007);
   mueta_1->GetYaxis()->SetLabelSize(0.1);
   mueta_1->GetYaxis()->SetTitleSize(0.12);
   mueta_1->GetYaxis()->SetTickLength(0.02);
   mueta_1->GetYaxis()->SetTitleOffset(0.55);
   mueta_1->GetYaxis()->SetTitleFont(42);
   mueta_1->GetZaxis()->SetLabelFont(42);
   mueta_1->GetZaxis()->SetLabelOffset(0.007);
   mueta_1->GetZaxis()->SetLabelSize(0.035);
   mueta_1->GetZaxis()->SetTitleSize(0.045);
   mueta_1->GetZaxis()->SetTickLength(0.02);
   mueta_1->GetZaxis()->SetTitleFont(42);
   mueta_1->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
