{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:55:41 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-1.21519,-2.955771,6.379747,7.930929);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(8734970);
   
   TH1F *n_electrons_stack_5 = new TH1F("n_electrons_stack_5","stack",10,0,10);
   n_electrons_stack_5->SetBinContent(1,10.86905);
   n_electrons_stack_5->SetBinError(1,3.719117);
   n_electrons_stack_5->SetMinimum(0.001827943);
   n_electrons_stack_5->SetMaximum(2.43553e+07);
   n_electrons_stack_5->SetEntries(86);
   n_electrons_stack_5->SetStats(0);
   n_electrons_stack_5->SetFillColor(4);
   n_electrons_stack_5->SetLineColor(4);
   n_electrons_stack_5->SetLineWidth(2);
   n_electrons_stack_5->SetMarkerColor(4);
   n_electrons_stack_5->SetMarkerStyle(21);
   n_electrons_stack_5->SetMarkerSize(0.8);
   n_electrons_stack_5->GetXaxis()->SetTitle("Number of electrons");
   n_electrons_stack_5->GetXaxis()->SetRange(1,6);
   n_electrons_stack_5->GetXaxis()->SetLabelFont(42);
   n_electrons_stack_5->GetXaxis()->SetLabelOffset(0.007);
   n_electrons_stack_5->GetXaxis()->SetLabelSize(0);
   n_electrons_stack_5->GetXaxis()->SetTitleSize(0);
   n_electrons_stack_5->GetXaxis()->SetTickLength(0.02);
   n_electrons_stack_5->GetXaxis()->SetTitleOffset(0.9);
   n_electrons_stack_5->GetXaxis()->SetTitleFont(42);
   n_electrons_stack_5->GetYaxis()->SetTitle("Events");
   n_electrons_stack_5->GetYaxis()->SetLabelFont(42);
   n_electrons_stack_5->GetYaxis()->SetLabelOffset(0.007);
   n_electrons_stack_5->GetYaxis()->SetLabelSize(0.035);
   n_electrons_stack_5->GetYaxis()->SetTitleSize(0.045);
   n_electrons_stack_5->GetYaxis()->SetTickLength(0.02);
   n_electrons_stack_5->GetYaxis()->SetTitleOffset(1.55);
   n_electrons_stack_5->GetYaxis()->SetTitleFont(42);
   n_electrons_stack_5->GetZaxis()->SetLabelFont(42);
   n_electrons_stack_5->GetZaxis()->SetLabelOffset(0.007);
   n_electrons_stack_5->GetZaxis()->SetLabelSize(0.035);
   n_electrons_stack_5->GetZaxis()->SetTitleSize(0.045);
   n_electrons_stack_5->GetZaxis()->SetTickLength(0.02);
   n_electrons_stack_5->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(n_electrons_stack_5);
   
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,10.86905);
   n_electrons->SetBinError(1,3.719117);
   n_electrons->SetMinimum(0.01);
   n_electrons->SetMaximum(4.8345e+07);
   n_electrons->SetEntries(86);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(4);
   n_electrons->SetLineColor(4);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(4);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetTitle("Number of electrons");
   n_electrons->GetXaxis()->SetRange(1,6);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0);
   n_electrons->GetXaxis()->SetTitleSize(0);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetTitle("Events");
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"HIST");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,78.92046);
   n_electrons->SetBinError(1,6.289136);
   n_electrons->SetEntries(242);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(5);
   n_electrons->SetLineColor(5);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(5);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,350.4835);
   n_electrons->SetBinError(1,15.10316);
   n_electrons->SetEntries(1034);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(6);
   n_electrons->SetLineColor(6);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(6);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,93.13949);
   n_electrons->SetBinError(1,1.238639);
   n_electrons->SetEntries(7302);
   n_electrons->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   n_electrons->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   n_electrons->SetLineColor(ci);
   n_electrons->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   n_electrons->SetMarkerColor(ci);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,18.26875);
   n_electrons->SetBinError(1,2.265807);
   n_electrons->SetEntries(142);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(3);
   n_electrons->SetLineColor(3);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(3);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,25.08348);
   n_electrons->SetBinError(1,1.850195);
   n_electrons->SetEntries(406);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(3);
   n_electrons->SetLineColor(3);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(3);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,5.566658);
   n_electrons->SetBinError(1,0.1740935);
   n_electrons->SetEntries(1384);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(3);
   n_electrons->SetLineColor(3);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(3);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   stack->Draw("hist");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,3223);
   n_electrons->SetBinError(1,56.77147);
   n_electrons->SetEntries(3223);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(1);
   n_electrons->SetFillStyle(0);
   n_electrons->SetLineWidth(3);
   n_electrons->SetMarkerStyle(20);
   n_electrons->SetMarkerSize(1.3);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   n_electrons->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DEta");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("n_electrons","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("n_electrons","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("n_electrons","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("n_electrons","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("n_electrons","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("n_electrons","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-1.21519,-0.653951,6.379747,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,5.639917);
   n_electrons->SetBinError(1,0.1921609);
   n_electrons->SetMinimum(0);
   n_electrons->SetMaximum(2);
   n_electrons->SetEntries(861.4213);
   n_electrons->SetStats(0);
   n_electrons->SetFillStyle(0);
   n_electrons->SetMarkerStyle(20);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetTitle("Number of electrons");
   n_electrons->GetXaxis()->SetRange(1,6);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.1);
   n_electrons->GetXaxis()->SetTitleSize(0.12);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetTitle("Data/MC");
   n_electrons->GetYaxis()->SetNdivisions(505);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.1);
   n_electrons->GetYaxis()->SetTitleSize(0.12);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(0.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   n_electrons->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
