{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:55:41 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-1.21519,-2.883278,6.379747,6.714464);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetLogy();
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMinimum(0.01);
   stack->SetMaximum(669073);
   
   TH1F *n_electrons_stack_8 = new TH1F("n_electrons_stack_8","stack",10,0,10);
   n_electrons_stack_8->SetBinContent(1,2.628311);
   n_electrons_stack_8->SetBinError(1,2.2551);
   n_electrons_stack_8->SetMinimum(0.002035525);
   n_electrons_stack_8->SetMaximum(1716236);
   n_electrons_stack_8->SetEntries(6);
   n_electrons_stack_8->SetStats(0);
   n_electrons_stack_8->SetFillColor(4);
   n_electrons_stack_8->SetLineColor(4);
   n_electrons_stack_8->SetLineWidth(2);
   n_electrons_stack_8->SetMarkerColor(4);
   n_electrons_stack_8->SetMarkerStyle(21);
   n_electrons_stack_8->SetMarkerSize(0.8);
   n_electrons_stack_8->GetXaxis()->SetTitle("Number of electrons");
   n_electrons_stack_8->GetXaxis()->SetRange(1,6);
   n_electrons_stack_8->GetXaxis()->SetLabelFont(42);
   n_electrons_stack_8->GetXaxis()->SetLabelOffset(0.007);
   n_electrons_stack_8->GetXaxis()->SetLabelSize(0);
   n_electrons_stack_8->GetXaxis()->SetTitleSize(0);
   n_electrons_stack_8->GetXaxis()->SetTickLength(0.02);
   n_electrons_stack_8->GetXaxis()->SetTitleOffset(0.9);
   n_electrons_stack_8->GetXaxis()->SetTitleFont(42);
   n_electrons_stack_8->GetYaxis()->SetTitle("Events");
   n_electrons_stack_8->GetYaxis()->SetLabelFont(42);
   n_electrons_stack_8->GetYaxis()->SetLabelOffset(0.007);
   n_electrons_stack_8->GetYaxis()->SetLabelSize(0.035);
   n_electrons_stack_8->GetYaxis()->SetTitleSize(0.045);
   n_electrons_stack_8->GetYaxis()->SetTickLength(0.02);
   n_electrons_stack_8->GetYaxis()->SetTitleOffset(1.55);
   n_electrons_stack_8->GetYaxis()->SetTitleFont(42);
   n_electrons_stack_8->GetZaxis()->SetLabelFont(42);
   n_electrons_stack_8->GetZaxis()->SetLabelOffset(0.007);
   n_electrons_stack_8->GetZaxis()->SetLabelSize(0.035);
   n_electrons_stack_8->GetZaxis()->SetTitleSize(0.045);
   n_electrons_stack_8->GetZaxis()->SetTickLength(0.02);
   n_electrons_stack_8->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(n_electrons_stack_8);
   
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,2.628311);
   n_electrons->SetBinError(1,2.2551);
   n_electrons->SetMinimum(0.01);
   n_electrons->SetMaximum(480000);
   n_electrons->SetEntries(6);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(4);
   n_electrons->SetLineColor(4);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(4);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetTitle("Number of electrons");
   n_electrons->GetXaxis()->SetRange(1,6);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0);
   n_electrons->GetXaxis()->SetTitleSize(0);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetTitle("Events");
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"HIST");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,9.551828);
   n_electrons->SetBinError(1,2.322635);
   n_electrons->SetEntries(22);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(5);
   n_electrons->SetLineColor(5);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(5);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,20.43743);
   n_electrons->SetBinError(1,3.603177);
   n_electrons->SetEntries(44);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(6);
   n_electrons->SetLineColor(6);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(6);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,9.457597);
   n_electrons->SetBinError(1,0.4453863);
   n_electrons->SetEntries(522);
   n_electrons->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   n_electrons->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   n_electrons->SetLineColor(ci);
   n_electrons->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   n_electrons->SetMarkerColor(ci);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,1.535982);
   n_electrons->SetBinError(1,0.811734);
   n_electrons->SetEntries(8);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(3);
   n_electrons->SetLineColor(3);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(3);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,0.6587428);
   n_electrons->SetBinError(1,0.2536643);
   n_electrons->SetEntries(8);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(3);
   n_electrons->SetLineColor(3);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(3);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,0.3349832);
   n_electrons->SetBinError(1,0.0479628);
   n_electrons->SetEntries(60);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(3);
   n_electrons->SetLineColor(3);
   n_electrons->SetLineWidth(2);
   n_electrons->SetMarkerColor(3);
   n_electrons->SetMarkerStyle(21);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   stack->Add(n_electrons,"");
   stack->Draw("hist");
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,32);
   n_electrons->SetBinError(1,5.656854);
   n_electrons->SetEntries(32);
   n_electrons->SetStats(0);
   n_electrons->SetFillColor(1);
   n_electrons->SetFillStyle(0);
   n_electrons->SetLineWidth(3);
   n_electrons->SetMarkerStyle(20);
   n_electrons->SetMarkerSize(1.3);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.035);
   n_electrons->GetXaxis()->SetTitleSize(0.045);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.035);
   n_electrons->GetYaxis()->SetTitleSize(0.045);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(1.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   n_electrons->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiSIGNAL_noCJV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("n_electrons","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("n_electrons","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("n_electrons","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("n_electrons","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("n_electrons","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("n_electrons","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-1.21519,-0.653951,6.379747,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *n_electrons = new TH1F("n_electrons","n_electrons",10,0,10);
   n_electrons->SetBinContent(1,0.7623302);
   n_electrons->SetBinError(1,0.1566103);
   n_electrons->SetMinimum(0);
   n_electrons->SetMaximum(2);
   n_electrons->SetEntries(23.69439);
   n_electrons->SetStats(0);
   n_electrons->SetFillStyle(0);
   n_electrons->SetMarkerStyle(20);
   n_electrons->SetMarkerSize(0.8);
   n_electrons->GetXaxis()->SetTitle("Number of electrons");
   n_electrons->GetXaxis()->SetRange(1,6);
   n_electrons->GetXaxis()->SetLabelFont(42);
   n_electrons->GetXaxis()->SetLabelOffset(0.007);
   n_electrons->GetXaxis()->SetLabelSize(0.1);
   n_electrons->GetXaxis()->SetTitleSize(0.12);
   n_electrons->GetXaxis()->SetTickLength(0.02);
   n_electrons->GetXaxis()->SetTitleOffset(0.9);
   n_electrons->GetXaxis()->SetTitleFont(42);
   n_electrons->GetYaxis()->SetTitle("Data/MC");
   n_electrons->GetYaxis()->SetNdivisions(505);
   n_electrons->GetYaxis()->SetLabelFont(42);
   n_electrons->GetYaxis()->SetLabelOffset(0.007);
   n_electrons->GetYaxis()->SetLabelSize(0.1);
   n_electrons->GetYaxis()->SetTitleSize(0.12);
   n_electrons->GetYaxis()->SetTickLength(0.02);
   n_electrons->GetYaxis()->SetTitleOffset(0.55);
   n_electrons->GetYaxis()->SetTitleFont(42);
   n_electrons->GetZaxis()->SetLabelFont(42);
   n_electrons->GetZaxis()->SetLabelOffset(0.007);
   n_electrons->GetZaxis()->SetLabelSize(0.035);
   n_electrons->GetZaxis()->SetTitleSize(0.045);
   n_electrons->GetZaxis()->SetTickLength(0.02);
   n_electrons->GetZaxis()->SetTitleFont(42);
   n_electrons->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
