{
//=========Macro generated from canvas: canv/canv
//=========  (Mon Nov 18 17:57:13 2013) by ROOT version5.32/00
   TCanvas *canv = new TCanvas("canv", "canv",0,0,700,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   canv->SetHighLightColor(2);
   canv->Range(0,0,1,1);
   canv->SetFillColor(0);
   canv->SetBorderMode(0);
   canv->SetBorderSize(2);
   canv->SetTickx(1);
   canv->SetTicky(1);
   canv->SetLeftMargin(0.16);
   canv->SetRightMargin(0.05);
   canv->SetTopMargin(0.05);
   canv->SetFrameFillStyle(0);
   canv->SetFrameLineStyle(0);
   canv->SetFrameLineWidth(2);
   canv->SetFrameBorderMode(0);
   canv->SetFrameBorderSize(10);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.26,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-0.8101265,-1.167805,4.253165,57.22243);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.16);
   upper->SetRightMargin(0.05);
   upper->SetTopMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("stack");
   stack->SetMaximum(51.71707);
   
   TH1F *taggingJetsFlavour_stack_14 = new TH1F("taggingJetsFlavour_stack_14","stack",4,0,4);
   taggingJetsFlavour_stack_14->SetBinContent(1,2.600504);
   taggingJetsFlavour_stack_14->SetBinContent(2,0.02780752);
   taggingJetsFlavour_stack_14->SetBinError(1,2.254928);
   taggingJetsFlavour_stack_14->SetBinError(2,0.02780752);
   taggingJetsFlavour_stack_14->SetMinimum(0);
   taggingJetsFlavour_stack_14->SetMaximum(54.30292);
   taggingJetsFlavour_stack_14->SetEntries(6);
   taggingJetsFlavour_stack_14->SetStats(0);
   taggingJetsFlavour_stack_14->SetFillColor(4);
   taggingJetsFlavour_stack_14->SetLineColor(4);
   taggingJetsFlavour_stack_14->SetLineWidth(2);
   taggingJetsFlavour_stack_14->SetMarkerColor(4);
   taggingJetsFlavour_stack_14->SetMarkerStyle(21);
   taggingJetsFlavour_stack_14->SetMarkerSize(0.8);
   taggingJetsFlavour_stack_14->GetXaxis()->SetTitle("#tau as tagging jet");
   taggingJetsFlavour_stack_14->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour_stack_14->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour_stack_14->GetXaxis()->SetLabelSize(0);
   taggingJetsFlavour_stack_14->GetXaxis()->SetTitleSize(0);
   taggingJetsFlavour_stack_14->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour_stack_14->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour_stack_14->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour_stack_14->GetYaxis()->SetTitle("Events");
   taggingJetsFlavour_stack_14->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour_stack_14->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour_stack_14->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour_stack_14->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour_stack_14->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour_stack_14->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour_stack_14->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour_stack_14->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour_stack_14->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour_stack_14->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour_stack_14->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour_stack_14->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour_stack_14->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(taggingJetsFlavour_stack_14);
   
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,2.600504);
   taggingJetsFlavour->SetBinContent(2,0.02780752);
   taggingJetsFlavour->SetBinError(1,2.254928);
   taggingJetsFlavour->SetBinError(2,0.02780752);
   taggingJetsFlavour->SetMaximum(32.67);
   taggingJetsFlavour->SetEntries(6);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(4);
   taggingJetsFlavour->SetLineColor(4);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(4);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetTitle("#tau as tagging jet");
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetTitle("Events");
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"HIST");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,9.551828);
   taggingJetsFlavour->SetBinError(1,2.322635);
   taggingJetsFlavour->SetEntries(22);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(5);
   taggingJetsFlavour->SetLineColor(5);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(5);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,19.60713);
   taggingJetsFlavour->SetBinContent(2,0.4197963);
   taggingJetsFlavour->SetBinContent(3,0.410497);
   taggingJetsFlavour->SetBinError(1,3.555018);
   taggingJetsFlavour->SetBinError(2,0.4197963);
   taggingJetsFlavour->SetBinError(3,0.410497);
   taggingJetsFlavour->SetEntries(44);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(6);
   taggingJetsFlavour->SetLineColor(6);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(6);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,9.321626);
   taggingJetsFlavour->SetBinContent(2,0.08792812);
   taggingJetsFlavour->SetBinContent(3,0.04804298);
   taggingJetsFlavour->SetBinError(1,0.4419903);
   taggingJetsFlavour->SetBinError(2,0.04470934);
   taggingJetsFlavour->SetBinError(3,0.03185327);
   taggingJetsFlavour->SetEntries(522);
   taggingJetsFlavour->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#660099");
   taggingJetsFlavour->SetFillColor(ci);

   ci = TColor::GetColor("#660099");
   taggingJetsFlavour->SetLineColor(ci);
   taggingJetsFlavour->SetLineWidth(2);

   ci = TColor::GetColor("#660099");
   taggingJetsFlavour->SetMarkerColor(ci);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,0.6906731);
   taggingJetsFlavour->SetBinContent(2,0.1106946);
   taggingJetsFlavour->SetBinContent(3,0.7346147);
   taggingJetsFlavour->SetBinError(1,0.3271085);
   taggingJetsFlavour->SetBinError(2,0.1106946);
   taggingJetsFlavour->SetBinError(3,0.7346147);
   taggingJetsFlavour->SetEntries(8);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(3);
   taggingJetsFlavour->SetLineColor(3);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(3);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,0.6587428);
   taggingJetsFlavour->SetBinError(1,0.2536643);
   taggingJetsFlavour->SetEntries(8);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(3);
   taggingJetsFlavour->SetLineColor(3);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(3);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,0.3108751);
   taggingJetsFlavour->SetBinContent(2,0.01164037);
   taggingJetsFlavour->SetBinContent(3,0.01246771);
   taggingJetsFlavour->SetBinError(1,0.04482731);
   taggingJetsFlavour->SetBinError(2,0.01164037);
   taggingJetsFlavour->SetBinError(3,0.01246771);
   taggingJetsFlavour->SetEntries(60);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(3);
   taggingJetsFlavour->SetLineColor(3);
   taggingJetsFlavour->SetLineWidth(2);
   taggingJetsFlavour->SetMarkerColor(3);
   taggingJetsFlavour->SetMarkerStyle(21);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   stack->Add(taggingJetsFlavour,"");
   stack->Draw("hist");
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,27);
   taggingJetsFlavour->SetBinContent(2,3);
   taggingJetsFlavour->SetBinContent(3,2);
   taggingJetsFlavour->SetBinError(1,5.196152);
   taggingJetsFlavour->SetBinError(2,1.732051);
   taggingJetsFlavour->SetBinError(3,1.414214);
   taggingJetsFlavour->SetEntries(32);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillColor(1);
   taggingJetsFlavour->SetFillStyle(0);
   taggingJetsFlavour->SetLineWidth(3);
   taggingJetsFlavour->SetMarkerStyle(20);
   taggingJetsFlavour->SetMarkerSize(1.3);
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(1.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   taggingJetsFlavour->Draw("SAMEPE1");
   TLatex *   tex = new TLatex(0.95,0.965,"DPhiSIGNAL_CJVpass");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.965,"CMS Preliminary 2012, #sqrt{s} = 8 TeV, 19.6 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.65,0.92,0.92,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("taggingJetsFlavour","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry=leg->AddEntry("taggingJetsFlavour","Z+jets,EWK Z","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","EWK W+jets","f");

   ci = TColor::GetColor("#660099");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","QCD W+jets","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","t#bar{t},t,tW","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("taggingJetsFlavour","Dibosons","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   upper->Modified();
   canv->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.26);
   lower->Draw();
   lower->cd();
   lower->Range(-0.8101265,-0.653951,4.253165,2.070845);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.16);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.24);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *taggingJetsFlavour = new TH1F("taggingJetsFlavour","taggingJetsFlavour",4,0,4);
   taggingJetsFlavour->SetBinContent(1,0.672631);
   taggingJetsFlavour->SetBinContent(2,4.761456);
   taggingJetsFlavour->SetBinContent(3,1.658894);
   taggingJetsFlavour->SetBinError(1,0.1480665);
   taggingJetsFlavour->SetBinError(2,4.294576);
   taggingJetsFlavour->SetBinError(3,1.64892);
   taggingJetsFlavour->SetMinimum(0);
   taggingJetsFlavour->SetMaximum(2);
   taggingJetsFlavour->SetEntries(2.374896);
   taggingJetsFlavour->SetStats(0);
   taggingJetsFlavour->SetFillStyle(0);
   taggingJetsFlavour->SetMarkerStyle(20);
   taggingJetsFlavour->SetMarkerSize(0.8);
   taggingJetsFlavour->GetXaxis()->SetTitle("#tau as tagging jet");
   taggingJetsFlavour->GetXaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetXaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetXaxis()->SetLabelSize(0.1);
   taggingJetsFlavour->GetXaxis()->SetTitleSize(0.12);
   taggingJetsFlavour->GetXaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetXaxis()->SetTitleOffset(0.9);
   taggingJetsFlavour->GetXaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetYaxis()->SetTitle("Data/MC");
   taggingJetsFlavour->GetYaxis()->SetNdivisions(505);
   taggingJetsFlavour->GetYaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetYaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetYaxis()->SetLabelSize(0.1);
   taggingJetsFlavour->GetYaxis()->SetTitleSize(0.12);
   taggingJetsFlavour->GetYaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetYaxis()->SetTitleOffset(0.55);
   taggingJetsFlavour->GetYaxis()->SetTitleFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelFont(42);
   taggingJetsFlavour->GetZaxis()->SetLabelOffset(0.007);
   taggingJetsFlavour->GetZaxis()->SetLabelSize(0.035);
   taggingJetsFlavour->GetZaxis()->SetTitleSize(0.045);
   taggingJetsFlavour->GetZaxis()->SetTickLength(0.02);
   taggingJetsFlavour->GetZaxis()->SetTitleFont(42);
   taggingJetsFlavour->Draw("PE1");
   lower->Modified();
   canv->cd();
   canv->Modified();
   canv->cd();
   canv->SetSelected(canv);
}
